### ISSUE TITLE
GitHub VITA repo - general discussion

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#1]
Please leave here your feedback about the project repo and other general issues

**Comment by MortenRUD** [comment]
How are things going with making the change for .NET CORE RC2 ? :-)

**Comment by rivantsov** [comment]
Well, ask MS :) they released RC2, and promise final release by end of June. As they say: 
*The tooling that supports .NET Core and ASP.NET Core, including the new command line tools and bits that plug into Visual Studio & Visual Studio Code, aren’t there yet. It’s going to change before it stabilizes. *
from here: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/
I'd wait another month. And honestly - no time for this right now, busy with other things, seem more urgent. How about you try?! and give a feedback?

**Comment by rubenalves** [comment]
Is there a way for the 'Admin' to reset or set user passwords without the old password?
Regards.

**Comment by rivantsov** [comment]
there's SetTempPassword method, sets one-time pwd for a user

**Comment by jholliday** [comment]
New installation on VS2015 running SQL Server 2014.  All tests passed except one.  It looks like both SetupHelper.Driver and SetupHelper.ConnectionString are null, and that SetupHelper.Reset is never being called.

Test Name:	TestGetSchema
Test FullName:	Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema
Test Source:	C:\Projects\vita-master\5.UnitTests\Vita.UnitTests.Basic\GetSchemaTests.cs : line 18
Test Outcome:	Failed
Test Duration:	0:00:56.6168251

Result StackTrace:	
at Vita.Data.Model.DbModelConfig..ctor(DbDriver driver, DbOptions options, DbNamingPolicy namingPolicy, IDictionary`2 schemaMappings) in C:\Projects\vita-master\1.Framework\Vita.Core\Data\Model\DbModelConfig.cs:line 34
   at Vita.Data.DbSettings..ctor(DbDriver driver, DbOptions options, String connectionString, String schemaManagementConnectionString, DbUpgradeMode upgradeMode, DbUpgradeOptions upgradeOptions, IDbInfoService dbInfoProvider, String dataSourceName, DbNamingPolicy namingPolicy) in C:\Projects\vita-master\1.Framework\Vita.Core\PublicAPI\DbSettings.cs:line 42
   at Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema() in C:\Projects\vita-master\5.UnitTests\Vita.UnitTests.Basic\GetSchemaTests.cs:line 23
Result Message:	
Test method Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by rivantsov** [comment]
will look at it. 
Guys, please create separate issues for bugs like these

**Comment by asd-and-Rizzo** [comment]
Add donate button for yourself or organization/project you care. You are doing cool work by showing people to move from stone age of hibernate to something better!

**Comment by asd-and-Rizzo** [comment]
May be update `VITA ORM Framework` to `VITA ORM Framework for space stations and clouds`:)

**Comment by rivantsov** [comment]
asd - thanks!
