### ISSUE TITLE
[Question] Ordering of Complex Select

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#100]
`TotalDepositAmount = x.Usernames.Sum(z =>
                            z.BankTransaction.Where(bt =>
                                    bt.IsActive && bt.BankTransactionType.Id == BankTransactionType.Deposit && bt.BankAccount.OrganizationBankAccounts.Any(oba => oba.Organization.Id == SessionManager.GetSession.OrganizationId))
                                .Sum(bt => bt.Amount)).ToString("N2")`

Hi, i got a question, i have a complex select (as shown above) from the SearchResults. is it possible to order such column?

**Comment by rivantsov** [comment]
I don't quite understand.. you say 'from SearchResults' - so you built and executed the search query? then you have a collection of objects/entities; since it is collection of entities (in memory, not in db) - then you can execute anything, like expr that you show, because it is Linq-to-Objects already, not Linq2Sql. I am probably missing something here

**Comment by Michaellok1992** [comment]
Let put it into a simpler scenario. 

`public class Customer
	{
		//detail
		
		List<Transaction> Transaction {get; set;}
	}
	
	public class Transaction
	{
		//detail
	}`

Let say, im trying to show list of customer detail with count of transaction has been made by each customer. Is it possible to order <count of transaction>?

**Comment by Michaellok1992** [comment]
@rivantsov , is my scenario given able to understand? or i need to further explain it

**Comment by Michaellok1992** [comment]
Sorry, wrong press of the button.

**Comment by rivantsov** [comment]
yeah, I get it, give me some time to get to it and try

**Comment by rivantsov** [comment]
Ok, I tried it, working with TestLinqEntityListMembers unit test. 
First I added an order-by clause to the last query in the test proc that queries book counts by publisher: 
      var qBookCountByPub = session.EntitySet<IPublisher>()
        .Select(p => new { PubName = p.Name, Id = p.Id, BookCount = p.Books.Count() })
        .OrderBy(pb => pb.BookCount)
        .ToList();

thank worked by generated SQL is clearly sub-optimal: 
SELECT  p0$."Name" AS "PubName", p0$."Id" AS "Id", (SELECT  COUNT_BIG(*)
FROM "books"."Book" b$
WHERE b$."Publisher_Id" = p0$."Id") AS "BookCount"
FROM "books"."Publisher" p0$
ORDER BY (SELECT  COUNT_BIG(*)
FROM "books"."Book" b$
WHERE b$."Publisher_Id" = p0$."Id");

It works, and looks like return correct result. 
Then I tried equivalent, but starting with IBook and grouping: 
      var qBooksCountByPub2 = session.EntitySet<IBook>()
            .GroupBy(b => b.Publisher)
            .Select(g => new { PubName = g.Key.Name, Id = g.Key.Id, BookCount = g.Count() })
            .OrderBy(pb => pb.BookCount).ToList();

then SQL looks much better: 
SELECT  p$."Name" AS "PubName", p$."Id" AS "Id", COUNT_BIG(*) AS "BookCount"
FROM "books"."Book" b0$
     INNER JOIN "books"."Publisher" p$ ON p$."Id" = b0$."Publisher_Id"
GROUP BY p$."Id", p$."Name"
ORDER BY COUNT_BIG(*);

So the answer is YES, it works but needs some improvement, in the future. Not sure if Db server is able to optimize the first query, so it might actually run efficiently, but still, second version is preferable. 
Something to look at in new LINQ translation engine, which is in the works, but it's a long shot now

**Comment by Michaellok1992** [comment]
Thanks. How about im using session.NewPredicate() ? in my case, i returning SearchResult using session.ExecuteSearch(query, param)

**Comment by rivantsov** [comment]
For ExecuteSearch- it doubt it's possible; if you mean - to put aggregate/count on top of query formed inside ExecuteSearch and then sort by aggregated column. Search has its own mechanics of forming the query and executing it.

**Comment by Michaellok1992** [comment]
> So the answer is YES, it works but needs some improvement, in the future. Not sure if Db server is able to optimize the first query, so it might actually run efficiently, but still, second version is preferable.
> Something to look at in new LINQ translation engine, which is in the works, but it's a long shot now

Maybe order by column number?

select col1, col2, col3
from table1
order by 1 desc

**Comment by rivantsov** [comment]
no, that should be simply by out column name

**Comment by Michaellok1992** [comment]
Ok. thanks for the advise.
