### ISSUE TITLE
[Question] Getting second row of result from query

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#101]
https://blog.sqlauthority.com/2019/10/28/sql-server-getting-second-row-from-table/amp/

Just question, does LINQ/Vita able to do such query?

**Comment by rivantsov** [comment]
no, ranking functions not supported. Yet, maybe in the future, thanks for bringing up this case.

But... Honestly, I am having hard time imagining real-life case when you need to get only rows #2,3, 7,9 when ordered in certain order; and why just retrieving rows 2-9 and picking up specific rows from the set, why this wouldn't work.

**Comment by Michaellok1992** [comment]
Yea, Rare case, but sometimes might need it. 

For example, let say user has login into the system, then a record has written into audit. One of the requirement is to get user previous login date & time.

**Comment by rivantsov** [comment]
that should be simple: 
var prevLogin = session.EntitySet<ILoginHistory>().Where(lh => lh.UserId == userId)
                .OrderByDescending(lh => lh.OnDateTime)
                .Skip(1).Take(1).FirstOrDefault();

**Comment by Michaellok1992** [comment]
Yea, this is what i think of also. 

Such requirement of selective row of record, this is a rare case scenario. Lets put it as low priority.
