### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#103]
In EntityApp.InitApp() the message ending with "Vita.Entities.Emit.EntityClassEmitter.CreateProvider()" should end with "Vita.Entities.Emit.EntityClassEmitter.CreateEntityClassProvider()"

**Comment by rivantsov** [comment]
thanks, will fix it

**Comment by rivantsov** [comment]
fixed, kind of - the need for this call is removed in v 3.0
