### ISSUE TITLE
[Question] IList Sorting

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#105]
Hi @rivantsov ,

```
interface IAuthor {
...
IList<IBook> book {get; set;}
...
}
```

```
interface IBook {
...
string Name {get; set;}
...
}
```

from 2 interface above, how can i sort the IBook 's name from IAuthor using `SearchResults<IAuthor >`?
orderby = "book.Name"

**Comment by rivantsov** [comment]
what the meaning of this? author has multiple books, so ordering authors by book.Name - order by which book of each author? What SQL you have in mind, I mean, you want Vita to generate? 
When you have reference prop (not List), like book.Publisher, then you can order books by pub name, using 'Publisher.Name' reference is order-by parameter

**Comment by Michaellok1992** [comment]
Sorry for unclear question.
Yes, i would like VITA to generate follow SQL.

my expected SQL is:
`
select author.Name, book.Name
from author
inner join book on book.author_id = author.id
order by book.name
`

**Comment by rivantsov** [comment]
but then the result is list of books, not authors! there will be multiple rows for each author in the output
so your query should be against IBook entity, and just include book.Author as output

**Comment by Michaellok1992** [comment]
'
 var baseQuery = session.NewPredicate<IAuthor>();

            var query = baseQuery
                .AndIf(condition, x => linq)
                .AndIf(condition, x => linq)
...
...
;
'

the reason i asking this due to i already have an existing function that build/query from IAuthor, and have multiple condition/criteria (like example above).. so if i wan to order the IBook's name, i have to re-write the 'session.NewPredicate<IAuthor>();' to 'session.NewPredicate<IBook>();' to meet my ordering requirement? 

Is it what u saying?

**Comment by rivantsov** [comment]
yes, sort of... it's not just ordering, you need to make it clear, what your function returns.. if it is list of (Author, Book) pairs? - then it is in fact list of books(!) with author attached, not authors, so it must start with Books predicate;

**Comment by Michaellok1992** [comment]
My case kinda complicated. It is possible we have a private platform to talk about this?

**Comment by rivantsov** [comment]
sure, send me email to rivantsov at gmail dot com

**Comment by Michaellok1992** [comment]
Ok. I will denormalize my data
