### ISSUE TITLE
Issue on 2.5 with SQL Lite

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#109]
i get this error on App,Init()

System.Exception: 'EntityApp.EntityClassProvider may not be null. Use Vita.Entities.Emit.EntityClassEmitter.CreateProvider() method from Vita.Entities.Emit assembly to create provider instance.'

What am i doing wrong?
I migrated the code from 1.9 vertion

**Comment by rivantsov** [comment]
hi
add ref to Vita.Entities.Emit and add this line somewhere either in app constructor, or right after you create app instance: 
app.EntityClassProvider = Vita.Entities.Emit.EntityClassEmitter.CreateEntityClassProvider();

**Comment by rubenalves** [comment]
app.EntityClassProvider = Vita.Entities.Emit.EntityClassEmitter.CreateEntityClassProvider();

I canot add this, Vita.Entities.Emit does not exist.
Thanks.

**Comment by rubenalves** [comment]
It Just happens on 2.5.1 on 2.5.0 it is ok.

**Comment by rivantsov** [comment]
try removing package Vita and add it back. Your dependency node should look like this: 
![image](https://user-images.githubusercontent.com/594969/70865691-242e2680-1f15-11ea-8ea4-4e382708a801.png)

it is coming with Vita package. 
I know, this DLL and the whole arrangement is a trouble, it will be gone in next version. 
By the way, did you migrate EncryptedData package?

**Comment by rivantsov** [comment]
I just did 2 experiments, with project in .net standard 2.0, another one with Full .net 4.6.2, I added package Vita from nuget, and was able to add and compile this code: 
            var app = new EntityApp();
            app.EntityClassProvider = Vita.Entities.Emit.EntityClassEmitter.CreateEntityClassProvider();

**Comment by rubenalves** [comment]
I just unistaled and instaled 2.5.1 again and it is working fine.

Thanks

**Comment by rivantsov** [comment]
Hi, quick question - did you migrate EncryptedData (as source code), or you still need it as standard module? I was planning to include it with a label 'legacy', not recommended for new dev, but if you don't need it, I would skip it
thx

**Comment by rubenalves** [comment]
My main application still uses EncryptedData the App i updrated to 2.5 is a small App that i have, the main app is still using 1,9
Thanks

Ruben Alves
________________________________
De: Roman Ivantsov <notifications@github.com>
Enviado: Tuesday, December 17, 2019 11:17:48 AM
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Issue on 2.5 with SQL Lite (#109)


Hi, quick question - did you migrate EncryptedData (as source code), or you still need it as standard module? I was planning to include it with a label 'legacy', not recommended for new dev, but if you don't need it, I would skip it
thx

**Comment by rubenalves** [comment]
I am planing to migrate my main app when you have the encrypted data.


Ruben Alves
________________________________
De: Ruben Alves <ruben.alves@serreta.net>
Enviado: Tuesday, December 17, 2019 11:32:16 AM
Para: rivantsov/vita <reply@reply.github.com>; rivantsov/vita <vita@noreply.github.com>
Cc: Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Issue on 2.5 with SQL Lite (#109)

My main application still uses EncryptedData the App i updrated to 2.5 is a small App that i have, the main app is still using 1,9
Thanks

Ruben Alves
________________________________
De: Roman Ivantsov <notifications@github.com>
Enviado: Tuesday, December 17, 2019 11:17:48 AM
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Issue on 2.5 with SQL Lite (#109)


Hi, quick question - did you migrate EncryptedData (as source code), or you still need it as standard module? I was planning to include it with a label 'legacy', not recommended for new dev, but if you don't need it, I would skip it
thx
