### ISSUE TITLE
Version 3.0 is pushed, packages published to nuget

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#110]
Details will follow. Brief sum up: 
- Visual Studio 2019
-  .NET Core 3.1, .NET Standard 2.0
- integration with ASP.NET Core 3.1 (latest) WebApi, WebTests project showing calls to REST api (uses Arrest package - REST client, published on nuget.org) 
- Vita.Entities.Emit project/assembly is gone, no need to assign EntityClassEmitter/provider in EntityApp constructor. 
- Logging to database, demo-ed in WebTest project
- loooots of internal refactorings and improvements

**Comment by rubenalves** [comment]
I am having a problem converting my app,
This is one of the errors
  var loginService = empresa.Aplicacao.GetService<ILoginService>(); service does not exist.
Another one is 
[Column(DbType = DbType.Date)]
id not correct, what is the new sintax?

Thanks.

**Comment by rivantsov** [comment]
Patch version 3.0.2 pushed, a few bug fixes

**Comment by rivantsov** [comment]
Details here: 
https://github.com/rivantsov/vita/wiki/Code-changes-history

**Comment by rivantsov** [comment]
Patch release 3.0.3 pushed
