### ISSUE TITLE
[Enquiry] Login module with google/facebook sign in

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#112]
Dear Sir,

I have mobile app with vita (rest api) as backend.
I am exploring the google/Facebook sign in,  but I am not sure how to utilize the login module with it.
Could you please enlighten me on that?
Thank you very much.

Jason Law

**Comment by rivantsov** [comment]
Login module and Google/fbook signin are kind of opposites. Login module is for the case when you want to handle login yourself. For G/Fb login, you want other party to handle all this, so first - read about it and how it works.  
You need to look at OAuth2.0/OpenId protocol. The old VITA version 1.9.3, had OAuthClient module with tables for storing info, and sample app (windows desktop app) demoing the the module. Go to 1.9.3 version, here is the page: 
https://github.com/rivantsov/vita/tree/be09639ffeda15e42e27a21cee0a179b80e90ac3
download it as zip, unzip, and look at OAuthClient module and OAuthSample app in samples. You can use almost all of the code as is, except you have to re-implement hit-back controller, SlimApi stuff is not supported anymore

**Comment by jasonlaw** [comment]
Thank you very much!
