### ISSUE TITLE
[Error] Always return null in GetModule

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#118]
Hi @rivantsov ,

I am using 3.0.2, and always get null object from GetModule method.
I have done a debug and found the following code:
![image](https://user-images.githubusercontent.com/107820/72533942-f9871300-38b0-11ea-80f5-052c396701b5.png)

Is it a bug or by intentional? Why it is always returning null?

This is quite urgent issue, really appreciate your help.

Thanks.

**Comment by jasonlaw** [comment]
I had checked previous version code and found it is really a big different.
![image](https://user-images.githubusercontent.com/107820/72534823-6ea71800-38b2-11ea-8c8e-19cef16301a7.png)

**Comment by rivantsov** [comment]
haha, yeah, it is a bug, result of rush refactoring
I don't think it's really urgent - just use your own correct version, Modules list is available there
I will fix it with next push, whenever it comes

**Comment by jasonlaw** [comment]
I use the workaround now by registering the module into Service and use GetService instead of GetModule, do you see any problem with this?

**Comment by rivantsov** [comment]
It is in fact not a workaround but a preferred/recommended way of inter-module communications. Only use some interface implemented by a module to register it as a service, do not register module type itself.

**Comment by jasonlaw** [comment]
cool...thank you very much!

**Comment by Michaellok1992** [comment]
Hi @rivantsov , 

Not sure is it the same issue as per title.

When i perform a query, i put a breakpoint to check is there any return result. There is some return value. Then it enter foreach loop, there is no more value.

as per screenshot.
![image](https://user-images.githubusercontent.com/40017655/73062811-3a49e200-3ed8-11ea-9726-8bf93439d058.png)


My workaround is to put ".ToList()" on the query.

**Comment by rivantsov** [comment]
no, it's not related to this GetModule bug.
maybe I don't quite understand the question, but... here's what's looks like happening. 
The bookAccount does not contain result, it is a query not yet executed. "There is some return value" - not sure, you probably see just the query expression. 
The query is executed when you either call bookAccount.ToList(), or you start 'foreach bk in bookAccount' - in this case ToList is executed automatically. I suggest to explicitly call ToList before the loop. Also it might be that if your increment of sequenceNumber before entering 'for each' actually impacts query execution. If you call ToList() immediately, it executes with sequenceNumber before incr; if you don't do ToList, but go to foreach, then query executes with incremented seqNumber value, and it makes the difference. 
Hope this helps

**Comment by Michaellok1992** [comment]
Thanks @rivantsov
