### ISSUE TITLE
String Comparison when querying database

### ISSUE THREAD

**Issue by adjdred** [rivantsov/vita#12]
Most likely not an issue but struggling to get this to work.

I need to get a record(s) based on a string value however whenever I try to request data when comparing two strings I get the String Comparison error.

I have tried 

```
Dim importJobs = certificateSession.EntitySet(Of IImportJob).Where(Function(s) s.File = data.BatchCode.ToString())

Dim batchCodeString as string = data.BatchCode.Tostring()
Dim importJobs = certificateSession.EntitySet(Of IImportJob).Where(Function(s) s.File = batchCodeString)
```

Exception
```
{"Linq to SQL translation failed: Function CompareString not supported in queries
Possibly facilities you are trying to use are not supported. 
Try to reformulate/simplify the query. Hint: do not use c# functions/methods inside query directly. "}	Vita.Data.Linq.Translation.LinqTranslationException
```

**Comment by rivantsov** [comment]
Hmm.. what is the database server, what is the column type of 'File'? 
Do you have other queries with string parameters, against this or other tables, that work and just this one fails? 
BTW, where's ToList() call - the operators shown create query only, it is not executed yet. 
One thing to look - after the query is executed and fails, stop there in debugger, and look at session.LastLinqQuery property, get its ToString representation from var watch window - this might give a clue, please share it here, it should show the query expression.

**Comment by rivantsov** [comment]
did you resolve it?

**Comment by adjdred** [comment]
Sorry I got pulled onto a different project. I managed to get around it by using startswith and endswith.
