### ISSUE TITLE
LogFileWriter

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#121]
It would be useful if LogFileWriter would be an implementation of an ILogFileWriter interface and I could implement my own.

**Comment by rivantsov** [comment]
just override EntityApp.OnLogBatchProduced and do what you want there, with your own thing. That's actually the idea. Or subscribe directly to ILogBatchingService

**Comment by rivantsov** [comment]
but I see your point, I will probably add interface

**Comment by sapatag** [comment]
Thanks for the tip, I had no time to dug into it.

**Comment by rivantsov** [comment]
added interface
