### ISSUE TITLE
Integer datatype unique running number

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#122]
Hi @rivantsov ,

May I know how to have a auto running number for a non-primary key column?

Thanks in advance.

**Comment by rivantsov** [comment]
use Identity column, or use Sequence, this is special db object, just for this, it is supported by VITA

**Comment by jasonlaw** [comment]
I tried with the following, and hit the error.
```
    [Entity]
    public interface IDefect 
    {
       [PrimaryKey, Auto(AutoType.NewGuid)]
        Guid Key { get; }
        [Identity]
        int DefectId { get; set; }
     }
```
Error:
table "community_Defect" has more than one primary key

**Comment by rivantsov** [comment]
wait... what db is this? SQLite? if it is, then it is not possible, auto-incr can be put only on in PK column, I guess the result is VITA tries to create 2 pk columns

**Comment by jasonlaw** [comment]
You are right, I am using SQLite for local testing, but my production will be MySQL.
I will test again with MySQL later and update the result here.
Thanks for your help, really appreciate it!

**Comment by rivantsov** [comment]
that's a really strange arrangement you have, and unsafe. These 2 things are very different, so you might get a lot of surprises in prod. Why don't you use MS SQL dev edition or local db - they are free

**Comment by jasonlaw** [comment]
Tested and work for Mysql, thank you very much!
