### ISSUE TITLE
Database changing events

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#125]
On my application i hat this
App.GetService<IDataAccessService>().Events.DataSourceStatusChanging += EventsOnDataSourceChange;
so that every user will need to update the app because the database schema had canged
What can detect the database changing event?
I have my aplication working very well on the vertion 3.02
Thanks

**Comment by rubenalves** [comment]
I think i found the solution
App.DataSourceEvents.DbUpgrading += DataSourceEventsOnDbUpgrading;

private void DataSourceEventsOnDbUpgrading(object sender, DbUpgradeEventArgs e)
        {
            if (e.UpgradeInfo.VersionsChanged)
            {
                if (e.UpgradeInfo.Status == UpgradeStatus.HigherVersionDetected)
                {
                    MessageBox.Show(@"Tem de atualizar antes de continuar....");
                    Process.Start("TsUpdate.exe");
                    AppHelper.Variaveis.Encerrar = true;
                    Environment.Exit(33);

                }
            }

        }
There is a bug in vita,
If my app version is 2020.4.5 and i change the version to a biger vertion on DbInfo table to 2020.4.6 the event is not triggerd, if i change to 2020.4.4 it is triggerd, do it is doing the inverse.
Thank You.

**Comment by rivantsov** [comment]
Glad to hear it all works well. 
I think you're on the right track, with detecting if something changed.  Except I don't feel comfortable with this forceful Environment.Exit() - I would prefer more graceful process. 
Have a look at test file SchemaUpdateTests.cs, in BasicTests, around line 287. The code builds upgrade info to check if there are any upgrade actions - you can do the same, manually build upgradeInfo - set of changes, and show message and exit if list is not empty.

As for behavior with version in DbInfo. It actually does not mean much. Main version info that matters is in DbModuleInfo - it is per module. But given that, the behavior you describe seems logical - the version in dbInfo table(s) is the version of the DB, or the version of the app that ran last time. 
If the currently starting app has higher version that what is in db, it means we need to upgrade db to this higher version.

**Comment by rubenalves** [comment]
I have made several testes, if the version is bigger on the database, it does not even triger the event, if it is the same or lower it trigers the event, it shold trigger the event on all cases.
Thanks.

**Comment by rivantsov** [comment]
Ok, I will have a look.. but again, keep in mind that main, real indicators are versions in DbModuleInfo - everything is per module in VITA, in general

**Comment by rubenalves** [comment]
Hello,
I am tying for hours now and canot find a way to check the version from a module
On the App i set the Version 
like this: App.Version = new Version(2020, 4, 5);
How can i set the version on the Module ?
How can i check to see if the Module version is Higher?
is there a way to overside the DbUpgrading so i can see version on the database?
It probably is confusing for you but i do not see a solution here.
On 1.9... it worked that way with no problems.
Sorry for bothering you so much with this.
Thank you very much

**Comment by rivantsov** [comment]
to set version for a module - look at any module coming with VITA as an example, like EncryptedDataModule that you use: 

https://github.com/rivantsov/vita/blob/master/3.Modules/Vita.Modules.Legacy/EncryptedData/EncryptedDataModule.cs

version is a parameter of a base constructor. When you change db schema of the module (entities), you should up the CurrentVersion and pass it base constructor. That should be your standard practice; this actually controls which migration actions to enable during upgrade (migration actions is some extra data initialization that you want to perform on upgrade to next version)

As for detecting if db needs upgrade - if your approach with handling Upgrade event works - go with it for now. I guess I do not have a better story for you now. 
But I am a bit confused about your scenario. Who is this user whom you show this message box that he needs to upgrade the database? How it happens that user got new code but did not get new database schema, and how he can get database with new schema? standard scenario I envisioned is that new code arrives, detects old schema in database, and upgrades it automatically. What is your case?

**Comment by rubenalves** [comment]
My senario is like this,
I update the aplication on one computer, the database gets updated, if i try to open to open the aplication on another computer it cheks to se if the database version is higer than the application version, if so it opens the update aplication and closes the aplication.

**Comment by rivantsov** [comment]
ah, OK, then simply do the following; start the app with UpgradeMode.Never; It will open ok even if there's some schema mismatch. 
then query the DbModuleInfo table for your main module, and compare version there with version of the module running in the app.

**Comment by rubenalves** [comment]
I foung a solution, i used Dapper to connect to database, read the version number from thre database and compare it and exit if it is necessary.
Thanks for your help.

**Comment by rivantsov** [comment]
dapper?! c'mon man, this is embarrassing(for me), you can do exactly the same with VITA itself, without any dappers, just start it without upgrade, then query the DbInfoModule table and that's it

**Comment by rubenalves** [comment]
I am sory if that offended you.
I am a very lame programer and i canot understand the how to query the DbInfoModule and if i disable
the upgrade i have to aply the upgrade again if it has changes.
My problem is that the new version has lots of changes that i canot understand and with this solution i can only check the version and exite if it is bigger.
Thanks for your time and Very Sory about this,

**Comment by rivantsov** [comment]
no problem, nobody offended, whatever works for you
here's what I meant: 
var myModuleInfo = session.EntitySet<IDbModuleInfo>().First(m => m.Name == "MyModule");
var version = myModuleInfo.Version; //or smth
I am closing this item
