### ISSUE TITLE
Vita in a standard mvc application

### ISSUE THREAD

**Issue by Rastas** [rivantsov/vita#13]
I would really like to use Vita in a standard MVC web application, but am a bit concerned with issues like the session life cycle etc. ( the same issues that we have dealt with in EF ). Unfortunately I cant find anywhere in the documentation where you talk to the session lifecycle and in fact to any mvc controller ( not api controller ) implementation. I am wanting to use an ioc container to build and shre the session per request but am just concerned about the above issues. An example would be great but even a simple explanation would work too.

**Comment by rivantsov** [comment]
There's nothing special about entity session. Create, use it, drop it at the end of the request. You don't need to deallocate it, just make sure there's no references to it left behind so it will be picked up by GC. If you put it into IoC container, make sure you remove it at the end of the request. The possible complications can come ONLY if you use some advanced modes/ facilities (like connection reuse, when session holds connection to database open until the end of the request and reuses it) - but for initial try just don't use anything beyond defaults. 
Let me know if you have more specific questions or concerns
