### ISSUE TITLE
Copy Objects

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#130]
Hello Roman,

Sorry if i already asked for somethis like this,
Is the a way to copy a entire object and related object to anothe session?

I am trying to load 2 seperate databases, create a session1 on one database and session2 on another database, and then copy session1 object and attache it on session2
like session2.Attache() ... just an example.

I used it alot on a application i devoloped using Entity Framework, i am convertion it now for Vita was looking for a way to do this.

Thanks.
Ruben

**Comment by rivantsov** [comment]
Try using EntitySessionExtensions.NewCopyOf method, it allows you to create a shallow copy of an entity in another session;

**Comment by rubenalves** [comment]
Thanks.
It will probably resolve my problem, it only copys the entity and not the related entiy, but i am testing to see if it does the jobe.
