### ISSUE TITLE
TimeService

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#131]
Hi @rivantsov ,

In TimeService, we have the following properties:
`
 public DateTime UtcNow {
      get {
        var now = DateTime.UtcNow;
        return _millisecondOffset == 0 ? now : now.AddMilliseconds(_millisecondOffset);
      }
    }
    public DateTime Now {
      get {
        var now = DateTime.Now;
        return _millisecondOffset == 0 ? now : now.AddMilliseconds(_millisecondOffset);
      }
    }

`
Why do we need to add the offset for UtcNow ?

Suppose we have following scenario:

KL +8 hours
NL +2 hours

NL = 10am		UTC = 8am  	(10am - 2hours)
KL =  4pm 		UTC = 8am	( 4pm - 8hours)

KL App hosted in NL
CurrentOffSet = +6    ( 8hours -  2hours)
NL = 10am
KL =  4pm

TimeService
Now 	=  4pm (10am + 6hours) <- Correct
UtcNow	=  2pm ( 8am + 6hours) <- Not correct, expected 8am

Am I understand correctly on how the TimeService works?

Thanks.

**Comment by rivantsov** [comment]
No, that's not what timer service is for.. It is a thin interceptor between your app code and DateTime.Now/UtcNow. It is for easier TESTING of time-related features. It allows you to move TIME at will. 
For ex, you have an expiring token - you create it, and then after 20 minutes it should expire. How to test it? Wait for 20 minutes in test code? Instead, you  create token, check it is valid, then move time forward 25 minutes using the offset, check again - token should be expired. I use this approach in all my projects. The rule is - NEVER use DateTime.UtcNow or Now directly in your code, use TimeService, then your code is testable

**Comment by jasonlaw** [comment]
Ok clear now, thank you very much!
