### ISSUE TITLE
Size default value is not used

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#132]
I have an Entity property with the size defined as following:

[Size("TenantId", 100)]
String TenantId { get; set; }

It hits error when starting the app.

I thought it will be using the default value given if the SizeCode is not found?

``
Entity Model build failed.
Initializing EntityApp MyApp.====================================
  Building entity model...
Size code 'TenantId' not found, entity member: Auth.TenantId
Exception thrown: 'Vita.Entities.StartupFailureException' in Vita.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Resources.ResourceManager.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Text.Encodings.Web.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Diagnostics.StackTrace.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Reflection.Metadata.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Collections.Immutable.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.IO.MemoryMappedFiles.dll'. 
An unhandled exception of type 'Vita.Entities.StartupFailureException' occurred in Vita.dll
Entity Model build failed. : Initializing EntityApp MyApp.====================================
``

**Comment by rivantsov** [comment]
Well, it might be.. I will look at it for the next big push

**Comment by rivantsov** [comment]
should be fixed now, please verify

**Comment by jasonlaw** [comment]
Hmm, I expect the default value will be registered into the SizeCode table as well.
Anyway, that could be out of scope.
For now, the issue is fixed. Thanks!

**Comment by rivantsov** [comment]
about registration in size table - that would be a side effect that will be really surprising and confusing
