### ISSUE TITLE
EntityAppEvents.OnConnected has no reference?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#134]
Hi,

I suppose the  EntityAppEvents.OnConnected event will be triggered when the database connection is established right?

![image](https://user-images.githubusercontent.com/107820/83996216-21753100-a98e-11ea-9a85-7ea41255d217.png)

**Comment by rivantsov** [comment]
no, it's not database connection established, it when App is initialized, connected to db, upgraded its schema and so on, and is ready to use. Is it fired ever? it should be at startup

**Comment by jasonlaw** [comment]
No, it is never get fired.

**Comment by rivantsov** [comment]
ok then, one more thing to fix in the next push

**Comment by rivantsov** [comment]
fixed, added a call

**Comment by jasonlaw** [comment]
It is working now. Thanks.
