### ISSUE TITLE
[Question] How to create new Entity in custom attribute

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#136]
Suppose we have a Entity reference column in an Entity, can we create a new Entity based on the HostMember.DataType?

I am creating a custom attribute to instantiate the reference entity when the host entity is newly created.

**Comment by jasonlaw** [comment]
Here is what I am trying to do, with dynamic creating Entity based on the HostMember.DataType:

        public override void ApplyOnMember(EntityModelBuilder builder)
        {
            HostEntity.Events.New += Events_New;
            HostEntity.Events.Deleting += Events_Deleting;
        }

        private void Events_New(Vita.Entities.Runtime.EntityRecord record, System.EventArgs args)
        {
            if ( HostMember.DataType == typeof( IFileCollection))
            {
                record.SetValueDirect(HostMember, record.Session.NewEntity<IFileCollection>());
            }
            if (HostMember.DataType == typeof(IRating))
            {
                record.SetValueDirect(HostMember, record.Session.NewEntity<IRating>());
            }
            if (HostMember.DataType == typeof(ILikes))
            {
                record.SetValueDirect(HostMember, record.Session.NewEntity<ILikes>());
            }

        }

Btw, I found that the above code will not set the newly created entity into the column, am I missing something?

**Comment by rivantsov** [comment]
I don't quite understand. The property has certain type, let's ISomeEntity; but you want to init it with entity of some other type? what is the meaning of this? the member cannot change its type (and target table in foreign key) dynamically.
 And in general, I usually do not use session.NewEntity directly, I recommend defining static extension methods that create instances, like session.NewPublisher,  publisher.NewBook, etc. These serve as 'constructors'. With this approach, you can put this property setting code into this extension method, and then you'll always have prop initialized properly

**Comment by jasonlaw** [comment]
No, not init it with entity of different type, but to init it with entity of same type.
Anyway, I will take your advice into consideration, to have the "constructor" method for all the entity.
Thank you very much!
