### ISSUE TITLE
DbUpgradeMode.Always slow on remote DataBase

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#140]
Hi,

I use this on my database connection so it is upgraded on any changes on Table definitions,

DbSettings = new DbSettings(driver, MsSqlDbDriver.DefaultMsSqlDbOptions, connectionString, upgradeMode: DbUpgradeMode.Always);

If i am connction to a database server that is on a remote server(on a remote VPN for example) it takes sometines over 1 minute, even if there is no changes on the code.
            
If i use DbUpgradeMode.Never, it opens like 10 times faster, is there a way to speed this?
Only activate the update if there are changes to to the domain model?

Thanks.

**Comment by rubenalves** [comment]
I am using version 1.9.3.x
On version 3.0.3 it was the same.
Thanks.

**Comment by rivantsov** [comment]
oh man, you should move on from v1.9, it should be long gone. 
As for the problem itself - I think this is because with upgrade ALWAYS, it needs to verify if there are any changes - and that means a lot of queries on tables and indexes, and then comparing with 'new/current' schema. That takes time I guess. And it would be much worse on old version, I guess, because there were a LOOOT of stored procedures, to check/compare/ and possibly upgrade. So try somehow set a local flag, to do it once, probably after new version install, smth like this
and please move from old version ASAP

**Comment by rubenalves** [comment]
I managed to laje a flag to ser ir there is anel version or not and the aollocation startup is much better.
Move to the new version is not possível for now.
Thanks.

Ruben Alves
________________________________
De: Roman Ivantsov <notifications@github.com>
Enviado: Sunday, July 19, 2020 12:35:16 AM
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] DbUpgradeMode.Always slow on remote DataBase (#140)


oh man, you should move on from v1.9, it should be long gone.
As for the problem itself - I think this is because with upgrade ALWAYS, it needs to verify if there are any changes - and that means a lot of queries on tables and indexes, and then comparing with 'new/current' schema. That takes time I guess. And it would be much worse on old version, I guess, because there were a LOOOT of stored procedures, to check/compare/ and possibly upgrade. So try somehow set a local flag, to do it once, probably after new version install, smth like this
and please move from old version ASAP

**Comment by rubenalves** [comment]
Auto correct made a messa with my reply.
I managed to make a flag to se id it is a new version or not and the startup is 1o times faster now on remote connections.

Ruben Alves
________________________________
De: Ruben Alves <ruben.alves@serreta.net>
Enviado: Sunday, July 19, 2020 8:20:50 PM
Para: rivantsov/vita <reply@reply.github.com>; rivantsov/vita <vita@noreply.github.com>
Cc: Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] DbUpgradeMode.Always slow on remote DataBase (#140)

I managed to laje a flag to ser ir there is anel version or not and the aollocation startup is much better.
Move to the new version is not possível for now.
Thanks.

Ruben Alves
________________________________
De: Roman Ivantsov <notifications@github.com>
Enviado: Sunday, July 19, 2020 12:35:16 AM
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] DbUpgradeMode.Always slow on remote DataBase (#140)


oh man, you should move on from v1.9, it should be long gone.
As for the problem itself - I think this is because with upgrade ALWAYS, it needs to verify if there are any changes - and that means a lot of queries on tables and indexes, and then comparing with 'new/current' schema. That takes time I guess. And it would be much worse on old version, I guess, because there were a LOOOT of stored procedures, to check/compare/ and possibly upgrade. So try somehow set a local flag, to do it once, probably after new version install, smth like this
and please move from old version ASAP
