### ISSUE TITLE
Announcement - NGraphQL is published

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#144]
I have some exciting news - NGraphQL, a library for building GraphQL APIs in .NET, is finally here. Have a look:
https://github.com/rivantsov/ngraphql

time to finally dump this old REST thing and move on.

**Comment by jasonlaw** [comment]
Congratulations! 
May I know if this a total replacement to vita or a complement to it?

**Comment by rivantsov** [comment]
replacement for VITA? oh no.. it is more like replacement for REST. Expect its direct integration with VITA soon

**Comment by jasonlaw** [comment]
Great! Thanks!

**Comment by jasonlaw** [comment]
Interested to know the progress of integrating nGraphQL with VITA. :)

**Comment by rivantsov** [comment]
Well.. thanks for asking... before the integration, some things need to happen. The NGraphQL should be finalized and released as v1.0, working on it. Also VITA needs some preparation work itself, also in progress. 
Actually, NGraphQL can already be used to build graphQL API on top of VITA, without any special integration module. And I plan the first iteration to be a sample of GraphQL API (with bookstore) without this extra module. What this extra integration will provide is some hooks that would make things easier to code and more efficient, but absence of integration module is not a show stopper at all. NGraphQL is built as a general framework, not VITA or ORM oriented. So you can try playing with it right a way.

**Comment by jasonlaw** [comment]
Thanks for the clarification, looking forward the bookstore sample with NGraphQL, on ASP .Net Core Framework.
