### ISSUE TITLE
"Include" argument in ExecuteSearch

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#145]
Hi,

May I know what is the include expression for in the ExecuteSearch method?

![image](https://user-images.githubusercontent.com/107820/93884318-53c85580-fd15-11ea-967f-773ef28ca9ae.png)

In the BookStore example, SearchBooks method, why passing "b => b.Publisher" as include?
~~~c#
    // Alternative method for author name - results in inefficient query (with subquery for every row)
      //      if(!string.IsNullOrEmpty(authorLastName))
      //         where = where.And(b => b.Authors.Any(a => a.LastName == authorLastName));

      //Use VITA-defined helper method ExecuteSearch - to build query from where predicate, get total count,
      // add clauses for OrderBy, Take, Skip, run query and convert to list of model objects with TotalCount

      var results = session.ExecuteSearch(where, searchParams, include: b => b.Publisher,  nameMapping: _orderByMapping);
      return results;
~~~

**Comment by rivantsov** [comment]
explained here for regular LINQ queries: 
https://github.com/rivantsov/vita/wiki/devguide_linq#include
so it loads automatically all related entities for search results entities

**Comment by jasonlaw** [comment]
Thanks!
