### ISSUE TITLE
System.Exception: Object  is not an Entity, cannot retrieve Record field.

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#146]
Hi,

I encountered the following exception when trying to assign a entity reference field.
`System.Exception: Object  is not an Entity, cannot retrieve Record field.
   at Vita.Entities.Util.Throw(String message, Object[] args)
   at Vita.Entities.EntityHelper.GetRecord(Object entity)
   at Vita.Entities.Model.Construction.MemberValueGettersSetters.MarkTargetToClearLists(EntityRecord record, EntityMemberInfo member, Object newEntityRef)
   at Vita.Entities.Model.Construction.MemberValueGettersSetters.SetEntityRefValue(EntityRecord record, EntityMemberInfo member, Object value)
   at Vita.Entities.Runtime.EntityRecord.SetValue(EntityMemberInfo member, Object value)
   at Vita.Entities.Runtime.EntityRecord.SetValue(Int32 index, Object value)
   at VIQCore.Community.Proxies.User.set_Vendor(IVendor )
   at VIQCore.Community.CommunityExtensions.NewVendor(IUser user, String name, String addressLine1, String addressLine2, String addressCity, String addressState, String addressCountry, String addressPostcode, Double addressLatitue, Double addressLongitude) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Modules\Main\CommunityExtensions.cs:line 95
   at VIQCore.Community.Controllers.SignupController.SignupVendor(NewVendorRequest request) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Controllers\SignupController.cs:line 51
   at lambda_method(Closure , Object , Object[] )`

~~~C#
   public static IVendor NewVendor(this IUser user, string name,
                                        string addressLine1, string addressLine2,
                                        string addressCity, string addressState,
                                        string addressCountry, string addressPostcode,
                                        double addressLatitue, double addressLongitude)
        {
            if (user.Vendor != null) return user.Vendor;
            var session = EntityHelper.GetSession(user);
            var vendor = session.NewEntity<IVendor>();
            user.Vendor = vendor; // <-- Hit error here
            vendor.PersonInCharge = user;
            vendor.Name = name.Trim().ToUpper();
            vendor.AddressLine1 = addressLine1.Trim().ToUpper();
            vendor.AddressLine2 = addressLine2?.Trim()?.ToUpper();
            vendor.AddressCity = addressCity.Trim().ToUpper();
            vendor.AddressState = addressState.Trim().ToUpper();
            vendor.AddressCountry = addressCountry.Trim().ToUpper();
            vendor.AddressPostcode = addressPostcode.Trim().ToUpper();
            vendor.AddressLatitude = addressLatitue;
            vendor.AddressLongitude = addressLongitude;
            return vendor;
        }
~~~

Here is my model objects:
~~~C#
 [Entity]
    public interface IUser
    {
        [PrimaryKey]
        string Id { get; set; }

        IAuth Auth { get; set; }

        string Name { get; set; }
        
        [OneToOne]
        IMember Member { get; }

        [OneToOne]
        IOfficer Officer { get; }

        [Nullable]
        IVendor Vendor { get; set; }       

        IList<ICommunityInReview> CommunityInReviews { get; }
    }

 [Entity]
    public interface IVendor : IAddress
    {
        [PrimaryKey, AutoSequenceNumber()]
        string Id { get; }

        public string Name { get; set; }

        [Nullable, CleanupOnDelete]
        IFile Logo { get; set; }

        IUser PersonInCharge { get; set; }

        IList<IUser> Users { get; }

        IList<IVendorInCommunity> VendorInCommunities { get; }        
    }
~~~

Could you please advise how to fix the error?

Thanks!

**Comment by jasonlaw** [comment]
It works after I removed the user list from IVendor entity, am I missing some annotation?

~~~C#
 [Entity]
    public interface IVendor : IAddress
    {
        [PrimaryKey, AutoSequenceNumber()]
        string Id { get; }

        public string Name { get; set; }

        [Nullable, CleanupOnDelete]
        IFile Logo { get; set; }

        IUser PersonInCharge { get; set; }

        //IList<IUser> Users { get; } // it works after remove this line, am I missing some annotation?

        IList<IVendorInCommunity> VendorInCommunities { get; }        
    }
~~~

**Comment by rivantsov** [comment]
looking at it, yes it looks like smth to do with this Users list... will let you know... but, there are some suspicious things with IVendor. What is AutoSequenceNumber attr - your custom attr for creating IDs? it's not defined in VITA. 
and strangely, it is on string field. Looks like there's some activity going on on-create (inside attribute?). Also CleanupOnDelete? do you initialize/touch field values in any way inside implementations? 
the error we see indicates that some where property value is not null and is NOT of correct type. Strange for new entity

**Comment by rivantsov** [comment]
most likely something broken inside IVendor or IUser object, just ran through this code (where exc happens inside VITA) with my unit tests, appears to be working fine. Need more info on these attr-induced activities

**Comment by jasonlaw** [comment]
Yes, both AutoSequenceNumber and CleanupOnDelete are my custom attributes, however, the same error still occur even after I removed all the custom attributes.

**Comment by jasonlaw** [comment]
Btw, there are few points to be noted:
1. The vendor column in IUser entity is nullable. 
2. For user.Vendor = vendor; while vendor is new entity, user is a saved record.
Hope that will help for your investigation, thanks!

**Comment by jasonlaw** [comment]
From the debugging, it seems the error is due to the IUser object, the IUser.Vendor transient value should be null due to its nullable nature, but it return as { }, which cause the error. Please see the video clip below. 

![ObjectNotEntityError](https://user-images.githubusercontent.com/107820/94083007-c714b900-fe34-11ea-9a5e-1866481b9f2c.gif)

**Comment by jasonlaw** [comment]
The ValueTransient, instead of storing null, it stores System.DBNull.
FYI, I am tested with SQLite.

![image](https://user-images.githubusercontent.com/107820/94083615-3a6afa80-fe36-11ea-85fe-3cf1917f9900.png)

**Comment by jasonlaw** [comment]
Found a very interesting fact, the ValueTransient is actually storing null value, until it as has been referred, I believe this is the lazy load. 
![NullGone](https://user-images.githubusercontent.com/107820/94084401-fed13000-fe37-11ea-8241-5ee81cb8de4a.gif)

**Comment by rivantsov** [comment]
wow, what an investigation, with videos! thanks so much! yes, it has to do with lazy loading, it is a signal to the reading code that the value was not loaded yet. I think I know why it's breaking, it is under-patched fix, this is probably another place I forget to account for null AND DbNull. How urgent you need this? will few days, up to 1 week work? was going to patch several things together
thanks again, really appreciate the investigation!

**Comment by jasonlaw** [comment]
I am glad that help! :)
Not urgent, definitely can wait for another week. 
Thank you so much for this wonderful framework, really enjoy using it. :)

**Comment by rivantsov** [comment]
thanks! will fix it soon
btw, the fix most likely will be in EntityHelper.GetRecord: 

```c#
      if (entity == null || entity == DBNull.Value)
        return null;

```

**Comment by rivantsov** [comment]
should be fixed now, please verify

**Comment by jasonlaw** [comment]
No more exception.
