### ISSUE TITLE
Max length size string

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#149]
Hi @rivantsov ,

May I know how to define a max length size string, I am using MySQL database.

Thanks in advance.

**Comment by rivantsov** [comment]
Use EntityModule.RegisterSize method - for a module,
or directly app.SizeTable[SizeCode]=sizeValue;

**Comment by jasonlaw** [comment]
I guess you have misunderstood the question.
I have a discussion posting module, just like Facebook posting, hence I want the datatype to be something like VARCHAR(MAX) in SQL Server, but I am not sure how to set that in Entity.

**Comment by rivantsov** [comment]
ah, then use Unlimited attribute, it will result in varchar(max) for SQL Server

**Comment by jasonlaw** [comment]
Many thanks!
