### ISSUE TITLE
Generic QueryFilter

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#150]
Hi @rivantsov ,

Can I have something like this for QueryFilter?

~~~c#
interface IMultiTenancy
{
   string TenantId {get; set;}
}

[Entity]
interface ITenantTable : IMultiTenancy
{
  string Id {get; set;}
  string Name {get; set;}
}

// Set the query filter upon login.
context.SetValue( "tenantId", "abc" );
context.QueryFilter.Add<IMultiTenancy, string>((x, tenantId) => x.TenantId == tenantId);

// Expect the query will have tenantId abc filtered
var list = session.EntitySet<ITenantTable>().ToList()
~~~

**Comment by rivantsov** [comment]
No that wouldn't work. I suggest to create a generic static method/wrapper for EntitySet<>() function; inside, you get the EntitySet using the Vita's method; and then check entity type is IMultitenancy; if yes, it adds a Where(e => e.TenantId == currTenId) clause to the returned value

**Comment by jasonlaw** [comment]
The EntitySet seems not working well parent class type.
I have gave up the idea, and use the normal way to do.
Closing this for now since the normal way is working well.
