### ISSUE TITLE
Log doesn't capture the sql query

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#152]
Hi @rivantsov ,

I noticed the log some time doesn't capture the real sql query, but just "**Vita.Entities.Api.RequestInfo**".
Any idea?

Thanks!

~~~C#
 ======== Log Started 10/29/2020 1:19:38 AM ============
SELECT  "Key", "LoginId", "TenantId", "DisplayName", "PictureExternalUrl", "Password", "PhoneNumber", "Email", "Tag", "Flags", "LastSuccessOn", "CreatedOn", "AuthPin", "Picture_Key"
FROM "communityv3devjason"."Auth"
WHERE "LoginId" = @P0 AND ("TenantId" = @P1 OR ("TenantId" IS NULL) AND (@P1 IS NULL))
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='jason.cclaw@gmail.com', @P1='SystemAdmin' 
 -- Time 17.252 ms; 1 row(s), [2020/10/29 01:19:40] 

Vita.Entities.Api.RequestInfo
Vita.Entities.Api.RequestInfo
Vita.Entities.Api.RequestInfo
Vita.Entities.Api.RequestInfo
~~~

**Comment by rivantsov** [comment]
RequestInfo - sounds like API request data, not SQL. Are you sure there should extra SQLs there? btw, if this is test of a kind, make sure you call app.Flush() before shutting down the app
I will look at this asap

**Comment by jasonlaw** [comment]
Thanks for the prompt reply.
I am quite sure there should be extra SQLs here, since the log only contains login query, which doesn't make sense.
Thanks again for looking into this.

**Comment by jasonlaw** [comment]
One thing to note is, the login activity is in a separate dll, as illustrated below:

Base.dll
   Vita.dll

MyApp.dll
   Base.dll
   Vita.Data.MySql.dll

**Comment by rivantsov** [comment]
do you have a single EntityApp class/object? if not this might explain it

**Comment by jasonlaw** [comment]
I do have **single EntityApp** only, which will be kept in a global static variable after created.

**Comment by rivantsov** [comment]
got it, reproduced, wander how it slipped thru... fixing it

**Comment by rivantsov** [comment]
fixed

**Comment by jasonlaw** [comment]
Tested ok now. Thanks.
