### ISSUE TITLE
An exception of type 'Vita.Entities.DataAccessException' occurred in Vita.dll

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#157]
Hi @rivantsov ,

I have following APIs, where BlockMember is working fine, but UnblockMember will hit the error. 
Could you please help to check what did I miss?
Thanks!

_**An exception of type 'Vita.Entities.DataAccessException' occurred in Vita.dll but was not handled in user code
Unknown column 'x.Target_Community_Id' in 'field list'**_

~~~C#
        [HttpPost, Route("block/{id}")]
        public List<User> BlockMember(string id)
        {
            var mic = OpContext.MemberInCommunity();            
            VIQCoreError.ThrowIfMissingContent(mic, "MemberInCommunity");

            var session = OpContext.OpenSession();
            var targetUser = session.GetUser(id);
            VIQCoreError.ThrowIfMissingContent(targetUser, "TargetUser", id);
            
            var community = OpContext.Community();
            var target = session.EntitySet<IMemberInCommunity>().Where(x => x.Community == community && x.Member.User == targetUser).FirstOrDefault();
            VIQCoreError.ThrowIfMissingContent(target, "TargetMemberInCommunity", id);

            var exists = session.EntitySet<IBlockedMember>().Any(x => x.Actor.Community == mic.Community &&
                                                                      x.Actor.Member == mic.Member &&
                                                                      x.Target.Community == target.Community &&
                                                                      x.Target.Member == target.Member);

            VIQCoreError.ThrowIf(exists, $"Target member id {id} already in blocked list.");

            var blocked = session.NewEntity<IBlockedMember>();
            blocked.Actor = mic;
            blocked.Target = target;
            session.SaveChanges();

            return mic.BlockedMemberInCommunityList().Select(x => x.ToUserModel()).ToList();
        }

        [HttpPost, Route("unblock/{id}")]
        public List<User> UnblockMember(string id)
        {
            var mic = OpContext.MemberInCommunity();
            VIQCoreError.ThrowIfMissingContent(mic, "MemberInCommunity");

            var session = OpContext.OpenSession();
            var targetUser = session.GetUser(id);
            VIQCoreError.ThrowIfMissingContent(targetUser, "TargetUser", id);
            
            var community = OpContext.Community();
            var target = session.EntitySet<IMemberInCommunity>().Where(x => x.Community == community && x.Member.User == targetUser).FirstOrDefault();
            VIQCoreError.ThrowIfMissingContent(target, "TargetMemberInCommunity", id);

            var blocked = session.EntitySet<IBlockedMember>().Where(x => x.Actor.Community == mic.Community &&
                                                                         x.Actor.Member == mic.Member && 
                                                                         x.Target.Community == target.Community &&
                                                                         x.Target.Member == target.Member)
                                                             .FirstOrDefault();
            VIQCoreError.ThrowIfEmptyOrNull(blocked, $"Member {id} does not in the blocked list");

            
            session.DeleteEntity(blocked);
            session.SaveChanges();

            return mic.BlockedMemberInCommunityList().Select(x => x.ToUserModel()).ToList();
        }
~~~

Here are my entity definition:
~~~C#
    [Entity]
    [PrimaryKey(MemberNames = "Actor,Target")]
    [Validate( typeof(CommunityModule), nameof(CommunityModule.ValidateBlockedMember))]
    public interface IBlockedMember
    {
        [CascadeDelete]
        IMemberInCommunity Actor { get; set; }

        [CascadeDelete]
        IMemberInCommunity Target { get; set; }
    }

   [Entity]
    [PrimaryKey(MemberNames = "Member,Community")]
    public interface IMemberInCommunity
    {
        [CascadeDelete]
        IMember Member { get; set; }

        [CascadeDelete]
        ICommunity Community { get; set; }

        int Admin { get; set; }

        [Size(100)]
        string Address { get; set; }
    }
~~~

Attached here the log file:
[Log.txt](https://github.com/rivantsov/vita/files/5663411/Log.txt)
[ErrorLog.txt](https://github.com/rivantsov/vita/files/5663412/ErrorLog.txt)

**Comment by rivantsov** [comment]
Well, that's quite some stuff you have there, IBlockedMember's primary key is composite, made from refs to entity that has composite key itself... kinda not surprised Linq engine got lost in all these refs. 
So try the following, either should work
1. In this Where clause: 
.Where(x => x.Actor.Community == mic.Community &&
                                                                         x.Actor.Member == mic.Member && 
                                                                         x.Target.Community == target.Community &&
                                                                         x.Target.Member == target.Member)

change comparing entities to comparing IDs of entities: 
x.Actor.Community.Id == mic.Community.Id 
  (and the same for others); that should reduce number of joins, and hopefully fix the query

2. Create PK object using 
 var pk = session.CreatePrimaryKey<IBlockedMember>(mic.Community.Id, mic.Member.Id, target.Community.Id, target.Member.id);
- make sure you list ID values in exactly the order of columns in PK. 
then retrieve the object: 
var blocked = session.GetEntity<IBlockedMember>(pk);
finally delete the object: 
session.DeleteEntity(blocked); 
session.SaveChanges(); 

this second method is actually a better way to work with entities with composite keys. 
Let me know if it works.
Roman

**Comment by rivantsov** [comment]
Regardless of this fix, I would strongly recommend to avoid such arrangements, when composite key is used as FK, and on top of that the primary key is a composite of composite foreign keys. I would avoid modeling things this way, regardless of potential troubles with Linq. It's just does not look right from point of view relational modeling. If it's not too late - introduce Guid PKs on link tables.

**Comment by jasonlaw** [comment]
Thanks for the suggestion, I have introduced the Guid PKs and it works well now. Thanks again, really appreciate it.
