### ISSUE TITLE
Question on search include argument

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#158]
Hi @rivantsov ,

Suppose i have entities Order and OrderLines, if include order line in search order, eg, x => x.OrderLines, does it means the order lines will be retrieved together with the orders and further traverse on order.OrderLines will not inccur the db call again?

Thanks.

**Comment by rivantsov** [comment]
I am not sure about the details, you better post the code, but if you use ref or list property of the root entity in search expressions, there will be a join  (or subquery). VITA will try to do it in one go; if it cannot, it will throw error (Linq translation failed, smth like that)

**Comment by jasonlaw** [comment]
Here is one of the method I used for searching:

~~~C#
public static SearchResults<IDiscussion> SearchDiscussions(this IEntitySession session, DiscussionSearchParams searchParams)
        {
            var community = session.Context.Community();
            var where = session.NewPredicate<IDiscussion>()
                               .And(x => x.Community == community)
                               .AndIf(searchParams.ReportedOnly, x => x.AbuseReport != null)
                               .AndIf(!searchParams.ReportedOnly, x => x.AbuseReport == null)
                               .AndIfNotEmpty(searchParams.Content, x => x.Content.Contains(searchParams.Content))
                               .AndIfNotEmpty(searchParams.MemberId, x => x.Member.User.Id == searchParams.MemberId);

            if (!searchParams.ReportedOnly)
            {
                var blockedMembers = session.Context.BlockedMemberIds();
                where = where.And(x => !blockedMembers.Contains(x.Member.User.Id));
            }

            searchParams.DefaultIfNull(defaultOrderBy: "CreatedOn:DESC");
            var results = session.ExecuteSearch(where, searchParams, include: x => new { x.UserComments, x.Images, x.UserLikes });
            return results;
        }
~~~

I will traverse the search result of Discussion to it's comment details, I expect there won't be any db call when referring to Discusssion.UserComments, but to my surprise I see multiple db query call on that, but later I found those seems to be empty records.

Could it be the reference of UserComments remained unloaded if no corresponding records found in the include query result?

Thanks

**Comment by rivantsov** [comment]
ok, this is something to work with. So, for includes, engine runs a separate query (right after the main search query), to get ALL related records mentioned in 'include' expr, for all parent records returned by the main search query. 
Now the question, in logs - do you see this query for UserComments? and Images and UserLikes
if not, try include without new, for single related entity: x=>x.UserComments

also pls show the IDiscussion and IUserComments entities definitions

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

The include queries are indeed constructed and run, for those with result rows = 0, it will be causing the lazy query call later.

[Log.txt](https://github.com/rivantsov/vita/files/5706212/Log.txt)

Here are the entities definitions.
~~~C#
    public interface IUserCommentable<T> where T: IUserCommentEntity
    {        
        [OrderBy("CreatedOn")]
        IList<T> UserComments { get; }
    }

    [Entity]
    public interface IDiscussion : ICommunityMemberTable, IUserLikeable, IAbuseReportable, IUserCommentable<IDiscussionComment>
    {
        [PrimaryKey, Auto(AutoType.NewGuid)]
        Guid Key { get; }

        [Unlimited]
        string Content { get; set; }

        //[NoUpdate]
        //IMember Member { get; set; }

        [Auto(AutoType.CreatedOn)]
        DateTime CreatedOn { get; }

        [Auto(AutoType.UpdatedOn)]
        DateTime UpdatedOn { get; }

        [ComputedClientTime]
        DateTime CreatedOnClientTime { get; }

        [ComputedClientTime]
        DateTime UpdatedOnClientTime { get; }

        [AutoInstantiateAndCleanup]
        IFileCollection Images { get; set; }
    }

    [Entity]
    public interface IDiscussionComment : IUserCommentEntity
    {
        [CascadeDelete]
        IDiscussion Discussion { get; set; }
    }
~~~

**Comment by rivantsov** [comment]
well, that kinda sucks, lets call it 'deficiency' (not bug :), will look into this and fix it in the next push.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,
 The include seems doesn't work with 1-1 relationship.

With the following entities,
~~~c#
[Entity]
interface IUser
{
  [PrimaryKey]
  string id {get; set;}

  [OneToOne]
  IMember member {get; set;}
}

[Entity]
interface IMember
{
  [PrimaryKey]
  IUser User {get; set;}
}
~~~

with include definition (also tested with include in either search or EntitySet):
~~~C#
context.AddInclude( (IUser x) => x.Member );
~~~

will hit the following error when query:
~~~c#
Invalid expression in Include query, member Member: must be entity reference or entity list.
~~~

**Comment by rivantsov** [comment]
Looks like this scenario is not supported, and I am not sure if it will come anytime soon; it's just too special case, and easy workarounds exist. 
In general, I would STONGLY advice to think twice before using OneToOne relation; you don't win much, compared if you just had IMember have it's own PK and IUser.Member be a normal FK. So if you have a User and you want to know if he's a member, you don't need extra DB query, you just check IUser.Member if it's null (which is User.Member_id column). In contrast, with OneToOne, if you check IUser.Member, this will run extra query to lookup in Members table. In my long career, and in my 8 years of using VITA with many different databases and apps, I had only 2 or 3 cases when I used 1to1.

**Comment by jasonlaw** [comment]
Alright, thanks for the suggestion, I will change my design accordingly. :)

**Comment by jasonlaw** [comment]
> well, that kinda sucks, lets call it 'deficiency' (not bug :), will look into this and fix it in the next push.

Is this fixed?

**Comment by rivantsov** [comment]
ha, I mistakenly closed this issue, cause the second problem (one to one) appeared to be resolved, and I thought it's all over
Ok I reopen it. Obviously it's not fixed yet. I'm just back to VITA from other stuff, will get to this and see if it's fixable quickly and can get to next push, hopefully within 10 days

**Comment by rivantsov** [comment]
the issue with lazy reload for empty list is fixed in current sources, nuget binaries are not updated yet, continuing testing, will push in a few days

**Comment by rivantsov** [comment]
should be fixed now
