### ISSUE TITLE
OneToManyAttribue with multiple foreign keys

### ISSUE THREAD

**Issue by richardblloyd** [rivantsov/vita#16]
Hi. 

I am trying to understand how the one to many attribute works. 

I have an entity that links to another entity more than once on TWO foreign keys. If I just want to link one foriegn key I can just do the following:- 

Child Entity 

[EntityRef(FKParentId)] 
IParentEntity Parent {get; set;} 

Parent Entity 

IList\<IChildEntity\> children {get; set;} 

This works fine. But I want to link to the same parent on two seperate keys. 

I have tried the following:- 

Child Entity 

[EntityRef(FKParentId1)] 
IParentEntity Parent1 {get; set;} 

[EntityRef(FKParentId2)] 
IParentEntity Parent2 {get; set;} 

Parent Entity 

IList\<IChildEntity\> children1 {get; set;} 
IList\<IChildEntity\> children2 {get; set;} 

But this just throws a generic failed to build entity model error on Init() with no detail. 

If I try and decorate the parent with a one to many attribute thus:- 

[OneToMany("Parent1")] 
IList\<IChildEntity\> children1 {get; set;} 

[OneToMany("Parent2")] 
IList\<IChildEntity\> children2 {get; set;} 

I get a null reference exception on Init() 

Even if I just have a single child reference e.g delete children2 I still get a null reference error. 

Can anyone tell me where I'm going wrong? 

P.S. I know having two foreign keys pointing to the same parent is fairly poor db / architectural design but I have no control over this and am unable to change the database schema at this point. 

Regards, 

Richard Lloyd.

**Comment by rivantsov** [comment]
there's nothing wrong with your design. quite common to have multiple key refs like this. 
It is supported. First of all, when there's an error in model construction, the exception message is general, but inside the exception there's a list of detailed errors - just catch the exception and inspect the exc object in debugger. Or just do "Debug.WriteLine(exc.ToLogString())" - it should print out all these details

Now about entity refs and lists. Is it pseudo code you're showing or real one? the List property on parent should be a generic list: 
[OneToMany("Parent1")]
IList<ChildEntity> Children1 {get;}

and it should have 'get' only
So make the change, see if it still throws exc, then inspect the exc

**Comment by richardblloyd** [comment]
Thanks for the reply. I think it may be something up with the one to many attribute. I did as you suggested and made the IList property read only but still get a NullRefExc. This is with just one link to the child collection from the parent as well.

My actual code:-

Parent Entity:-

[Entity(TableName = "aspnetusers")]
    public interface IAspNetUser
    {
        [PrimaryKey(), Size(128)]
        string Id { get; set; }
      
         - snip -

        [OneToMany("StudentUserId")]
        IList\<ILinkedAccount\> LinkedAccounts { get; }
    }

Child Entity:-

[Entity(TableName = "tblLinkedAccount")]
    public interface ILinkedAccount
    {
        [PrimaryKey(), Identity(), Column("LinkID")]
        int Id { get; set; }

        [Column("FKStudentUserID"), Size(128), Nullable]
        string StudentUserId { get; set; }

         - snip -

         [EntityRef("FKStudentUserID")]
        IAspNetUser StudentAspNetUser { get; set; }
    }

The exception stack trace:-

   at Vita.Entities.OneToManyAttribute.Apply(AttributeContext context, Attribute attribute, EntityMemberInfo member)
   at Vita.Entities.Model.Construction.EntityModelBuilder.FindAndApplyAttribute[TAttr](EntityMemberInfo member)
   at Vita.Entities.Model.Construction.EntityModelBuilder.ProcessSpecialAttributes()
   at Vita.Entities.Model.Construction.EntityModelBuilder.BuildModel()
   at Vita.Entities.EntityApp.Init()
   at DAL.V2.eModule.Setup.Config.Configure(String connectionString) in d:\src\emodule\DAL.V2\eModule\Setup\Config.cs:line 15
   at BAL.Elements.Reports..ctor(String tmpLanguageCode, Guid tmpUserID, IDictionary`2 tmpQueryString, IDictionary`2 tmpFormData, Guid tmpAdminUserID) in D:\src\emodule\BAL\Elements\Reports.vb:line 52

What I actually wanted to do was something like 👎 

Parent Entity:-

[Entity(TableName = "aspnetusers")]
    public interface IAspNetUser
    {
        [PrimaryKey(), Size(128)]
        string Id { get; set; }
      
         - snip -

        [OneToMany("StudentUserId")]
        IList\<ILinkedAccount\> StudentLinkedAccounts { get; }

        [OneToMany("EmployerUserId")]
        IList\<ILinkedAccount\> EmployerLinkedAccounts { get; }
    }

Child Entity:-

[Entity(TableName = "tblLinkedAccount")]
    public interface ILinkedAccount
    {
        [PrimaryKey(), Identity(), Column("LinkID")]
        int Id { get; set; }

        [Column("FKStudentUserID"), Size(128), Nullable]
        string StudentUserId { get; set; }

       [Column("FKEmployerUserID"), Size(128), Nullable]
        string EmployerUserId { get; set; }


         - snip -

         [EntityRef("FKStudentUserID")]
         IAspNetUser StudentAspNetUser { get; set; }

         [EntityRef("FKEmployerUserID")]
         IAspNetUser EmployerAspNetUser { get; set; }
    }

**Comment by rivantsov** [comment]
Ok, here's your problem, this might be the cause of exception - do not declare foreign key columns explicitly, they are there already when you declare entity-type property. It is still wrong that VITA throws NullRef exception, I will investigate this. Let me know if it fixes the problem
One note - it is generally considered a bad thing to declare PrimaryKey as strings, like string(128) - the supporting PK index takes a lot of space, and all secondary indexes and foreign keys also take a lot of space, and performance is much worse. Use int or GUID. I personally strongly recommend GUIDs

**Comment by rivantsov** [comment]
fixed - now declaring FK columns explicitly does not cause exception
