### ISSUE TITLE
Does lazyload support include?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#160]
Hi @rivantsov ,

Suppose we have entities with relation **EntityA -< EntityB -< EntityC** (EntityA has many EntityB, EntityB has many EntityC).
Questions:
1. When we lazy load EntityA.EntitiesB, can we also include EntityC in the query?
2. Otherwise, with EntitySet<EntityA>, how do we configure the include up to EntityC?

Thanks.

**Comment by rivantsov** [comment]
Look at TestLinqInclude test, it shows how to do this, using 'second' form of include

**Comment by jasonlaw** [comment]
That's exactly what I am looking for, thank you very much!
