### ISSUE TITLE
[Question] Extend entity attribute, design thought

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#161]
Hi @rivantsov ,

Is there a way to extend the Entity defined in a generic module?
Eg, suppose I have a Login module which handle the authentication, and in the Login entity, I would like to have a reference to an User entity. However, the attributes of User could be vary from different projects. In that case, how would the project extends the User entity for more attributes?

Thanks.

**Comment by rivantsov** [comment]
there is service IEntityModelCustomizationService, it has method ReplaceEntity; it is for the case you are describing, you replace entity type defined in module with your own extended version (it must derive from original entity). 

There is an example in ModuleIntegrationTests.cs class,

**Comment by jasonlaw** [comment]
Amazing! Exactly what I am looking for! Thank you so much!
