### ISSUE TITLE
Question on async call

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#162]
Hi @rivantsov ,

I have a scenario here.
1. I have a payment gateway will direct the callback to my site when a payment is completed.
2. Based on the callback, I will update my invoice status, and generate the receipt.
3. While the payment gateway only wait for short timeframe for an success status, I want to return success immediately after updating my invoice status, while leaving the generating receipt at background with async call.
4. Since the generated receipt will be stored in database, I will still using the Session to save it into my entity.

Questions:
1. Does this flow sounds OK to you?
2. Is the Session still valid after returning OK to the api call?

Thank you!

**Comment by rivantsov** [comment]
as far as I understand... payment call returns, you update status of invoice entity, do SaveChanges (or not?)
then you want to return 'success' to client essentially completing the web request/response. 
But in the background thread, you want to continue doing some more stuff - generating receipt which involves db operations. 
If this is what you want to do.... I see one potential problem. Asp.NET kills all active leftover threads after request completes. So your generating receipt activity will be killed by aborting the thread. There are ways to schedule some task, don't remember exact API, research it. But you should use this special API. 
In general, I think it's not worth it, all this complications. How long is this task - a second? I don't think it's worth it.

**Comment by jasonlaw** [comment]
Thanks for the explanation, this is very helpful and important information to me.
Again, really appreciate your help. :)
