### ISSUE TITLE
Just pushed new code, preview v 3.1 - GraphQL API sample

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#163]
Packages not pushed, need some more testing. 
This is a preview of a GraphQL server on top of VITA-based app. based on NGraphQL project https://github.com/rivantsov/ngraphql

To see in action: start the project BookStore.GraphQLServer; this will open GraphiQL UI page in browser. Explore the schema, run some ad-hoc queries - get publishers books authors reviews etc.  
You can also run tests in GraphQLTests project. After you run the tests, explore the log file in the bin folder (both Sql log file and GraphQL log file), to see what's going on. 

The biggest addition in VITA - SmartLoad facility, a nickname for set of features that enable the engine to run proper 'Include' queries without explicitly specifying them when you formulate Linq query. Right now it is opt-in feature, you have to enable it when you open session (see BookStoreResolvers.cs, BeginRequest method). This is a solution for handling batching/(N+1 problem) that comes up in GraphQL servers. I will post a document about this later. 

There are also some fixes there for outstanding issues. I will continue testing and will build packages and push them in a few days.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

I have some questions:
1. Does the Resolver similar to the VitaWebMiddleware concept in REST?

2. From the code:
        ~~~C#
        public class BookStoreResolvers: IResolverClass {
            BooksEntityApp _app;
            IEntitySession _session; 
        
            public void BeginRequest(IRequestContext request) {
              // _app = BooksEntityApp.Instance; //this works too
              _app = (BooksEntityApp) request.App; //general case
              _session = _app.OpenSession(EntitySessionOptions.EnableSmartLoad); 
            }
        ~~~
     It seems that we keep EntitySession instead of OperationContext per request, in my REST implemetation, I have stored many data within the OperationContext, how do I keep the same behaviour? 

3. How does this works with the OAuth, in here I mean the VitaJwtTokenHandle? How about the information in operation context like UserInfo?

Thank you.

**Comment by rivantsov** [comment]
1. Resolver vs middleware - different things. VitaWebMiddleware is a generic interceptor in web handling pipeline, provides necessary pre-post processing to the controller-base handling of the request. It is called just once per web request. Resolver handles a single field on the request, a single data element; multiple resolver methods are invoked in one request, sometimes the same one multiple times. Read a bit docs about resolvers in GraphQL in general, the difference will be clear.

2. yes, sample code opens session when resolver class instance is created. But it is just a shortcut, actually op context is created by the open session method. You can do it explicitly - create OpContext first, set it up, then open session. Since multiple resolver methods can be invoked in one request, the session is reused for all of them. It is important for mutations - each mutation resolver makes entity changes which are kept in session, and only at the EndRequest the save changes is called. 

3. Auth and Jwt token. The plan is that Jwt token is handled by dedicated middleware, just standard stuff - token retrieved from request, decrypted, deserialized and the resulting dict of claims, IClaimsPrincipal (name-value pairs) is placed into HttpContext.User property, right here in the HandleRequest method, before call to GraphQLHttpServer: 
   https://github.com/rivantsov/vita/blob/master/src/4.Samples/BookStore.GraphQLServer/GraphQLAspNetServerStartup.cs
This User claims principal is available inside Resolver class through IRequestContext.User property; so this scenario is handled OK I think.

**Comment by rivantsov** [comment]
Regarding authentication, I will add to GraphQL sample authentication calls, in the next iteration.

**Comment by jasonlaw** [comment]
Thanks for the clarification.

In the case of opening session from OpContext, we would required the option of EnableSmartLoad right?
Are we missing the argument for OpContext.OpenSession method?

![image](https://user-images.githubusercontent.com/107820/107866171-ab27b780-6ea8-11eb-87e8-c8c0e7fd9c60.png)

**Comment by rivantsov** [comment]
yeah, you are right, it is missing, I will add it. For now, just use the constructor directly: 

      var session = new EntitySession(context, options: EntitySessionOptions.EnableSmartLoad);

**Comment by rivantsov** [comment]
btw, it is not required option; it just takes care of batch loading (automatic includes), I am writing a doc on this

**Comment by jasonlaw** [comment]
Thanks for the swift response!
I have some more questions, can we use both REST and GraphQL in the same server? If yes, could you please include it in the example? 
Thank you very much!

**Comment by rivantsov** [comment]
of course you can, the current GraphQL configure method just reserves 3 endpoints for GraphQL, any others URLs can be routed to regular REST (API) controllers. So you need just to combine the endpoint configuration from REST and Gql project snippets

**Comment by jasonlaw** [comment]
How about the VitaWebMiddleware? 
So from my current implementation for REST, what I need to do is just create the GraphQLHttpServer and combine the endpoints right?

**Comment by rivantsov** [comment]
that's a good question... I think even with this MiddleWare it will work, it just tracks web context (Vita's extra context) and does some logging. But it might be better to make it ignore graphQL URLs. I will look into this in the next iteration. For now, just explore the GraphQL part and how it works
