### ISSUE TITLE
[GraphQL] Resolver IRequestContext HttpContext - wrong type

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#168]
Hi @rivantsov ,

HttpContext property return GraphQLHttpRequest instance, is it by mistake?
![image](https://user-images.githubusercontent.com/107820/107895463-6403fa00-6f6e-11eb-98af-8e89409d9560.png)

![image](https://user-images.githubusercontent.com/107820/107895502-8f86e480-6f6e-11eb-9bb7-1bb172d38043.png)

**Comment by rivantsov** [comment]
oh, this looks messed up, looking into this..

**Comment by rivantsov** [comment]
fixed in v1.1.1

**Comment by jasonlaw** [comment]
Tested OK! Thanks!
