### ISSUE TITLE
[GraphQL] Question: How to build the mapping?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#169]
Hi @rivantsov ,

I have my (simplify) entity model as below:
~~~C#
    [Entity]
    public interface ICommunity
    {
        [PrimaryKey, Size(10)]
        string Id { get; }

        [Size(300)]
        string Name { get; set; }
	}
	
    [Entity]
    public interface IUser
    {
        [PrimaryKey, Size(nameof(IAuth.LoginId))]
        string Id { get; set; }

        [Nullable]
        ICommunity OfficerCommunity { get; set; }
    }
~~~

The UI model will be:
~~~C#
   public class Community
    {
        public string Id { get; set; }
        public string Name { get; set; }    
    }
   
   public class User 
    {
	public string Id { get; set; }
        public Officer Officer { get; set; }        
    }

    public class Officer
    {
        public Community Community { get; set; }
    }
~~~

Which, when the IUser.OfficerCommunity is null, then the output of User.Officer will be null too.

I have mapping for community
~~~C#
MapEntity<ICommunity>().To<Community>();
~~~

But I have no idea how to map the OfficerCommunity into Officer.Community.
Could you please help give me some guide? Thanks.

**Comment by rivantsov** [comment]
MapEntity<IUser>().To<User>(iu => 
    new User() { 
        Officer = new Officer() { 
           Community = FromMap<Community>(iu.OfficerCommunity)
        }
    }
);

- as far as I could understand. The trick is this FromMap method, allows to map entity (ICommunity) to Gql type (Community) inside mapping expressions. 
You know, as outside observer, the semantics/terms/names of the GraphQL model is quite hard to grasp, I would suggest to tune it a bit. Terms/names matter.

**Comment by jasonlaw** [comment]
Thanks for the answer, I have tested it but it seems always return null.

Here is my mapping:
~~~C#
MapEntity<IUser>().To<User>(x => new User { 
HasMemberRole = x.Member != null, 
HasVendorRole = x.Vendor != null, 
Officer = x.OfficerCommunity == null 
? null
 : new Officer { Name = x.Name, Password = x.OfficerPassword, Community = FromMap<Community>(x.OfficerCommunity) } });
~~~
As you may see, the officer will be null if OfficerCommunity is null.

Here is my query result, since the officer is not null, the Community shouldn't be null. 
Did I miss anything?
![image](https://user-images.githubusercontent.com/107820/107910665-d3411480-6f95-11eb-9f4e-3a77a20536f1.png)

**Comment by jasonlaw** [comment]
Are we expecting the actual implementation in somewhere else or it is just simply a bug with missing implementation?

![image](https://user-images.githubusercontent.com/107820/107912142-ebfef980-6f98-11eb-9e80-a2f4feec3015.png)

**Comment by rivantsov** [comment]
cool, you're already getting some data! two quick notes: 
1. Since User.Officer can be null, it should have [Null] attribute.
2. Keeping passwords in db, and especially returning them to client is a big NO-NO, you should NEVER keep passwords in database. Only hashes (strong hashes like BCrypt), and even they should ever be returned or shown to anybody. You use them to validate pwds by re-hashing.
 
Ok, I misled you, sorry; FromMap works only on top level, not inside other expressions. This empty implementation of FromMap - it is correct, this function should never be actually called, it is used only in expressions to signal to engine to use entity mapping there. 
Let me think a bit, I still do not quite get the semantics of your model. Looks like you introduce different objects in Gql model, not directly matching entities. This is OK, that's the central idea of GraphQL to have model that does not match db model. 
But it seems to me you need to declare Officer type as self-mapped, meaning it is a GraphQL type and at the same type it is part of biz model, so it can be returned from resolvers or fields in mapping expressions. Then you won't need these nested expressions

**Comment by rivantsov** [comment]
about FromMap implementation - I am thinking about throwing exception instead of returning default, exc with message explaining that you used in the wrong place. 
Another thing - in the future pls post GraphQL questions in NGraphQL project.

**Comment by rivantsov** [comment]
let's try just this: 

```csharp
MapEntity<IUser>().To<User>(iu => 
    new User() { 
        Officer = iu.ToOfficer() //using extension method
    }
);

public static Officer ToOfficer(this IUser user) {
    if (user?.OfficerCommunity == null) return null; 
    // produce Officer object
}
```

**Comment by jasonlaw** [comment]
Noted on the issue posting, will post GraphQL question in NGraphQL project in future.

Back to the issue, unfortunately the solution is not working.

{
  "errors": [
    {
      "message": "Object does not match target type.",
      "locations": [],
      "path": [],
      "extensions": {
        "code": "SERVER_ERROR",
        "Details": "System.Reflection.TargetException: Object does not match target type.\r\n   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)\r\n   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)\r\n   at NGraphQL.Model.Construction.ModelBuilder.<>c__DisplayClass25_1.<ProcessMappingForMatchingMembers>b__2(Object ent) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Model\\Construction\\ModelBuilder_EntityMappings.cs:line 91\r\n   at NGraphQL.Server.Execution.OperationFieldExecuter.InvokeFieldReader(FieldContext fieldContext, Object parent) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\OperationFieldExecuter_Invoke.cs:line 80\r\n   at NGraphQL.Server.Execution.OperationFieldExecuter.ExecuteObjectsSelectionSubsetAsync(IList`1 parentScopes, ObjectTypeDef objTypeDef, SelectionSubset subSet) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\OperationFieldExecuter.cs:line 126\r\n   at NGraphQL.Server.Execution.OperationFieldExecuter.ExecuteFieldSelectionSubsetAsync(FieldContext fieldContext) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\OperationFieldExecuter.cs:line 78\r\n   at NGraphQL.Server.Execution.OperationFieldExecuter.ExecuteOperationFieldAsync() in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\OperationFieldExecuter.cs:line 61\r\n   at NGraphQL.Server.Execution.RequestHandler.ExecuteAllNonParallel(IList`1 executers) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\RequestHandler.cs:line 77\r\n   at NGraphQL.Server.Execution.RequestHandler.ExecuteOperationAsync(GraphQLOperation op, OutputObjectScope topScope) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\RequestHandler.cs:line 63\r\n   at NGraphQL.Server.Execution.RequestHandler.ExecuteAsync() in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\Execution\\RequestHandler.cs:line 42\r\n   at NGraphQL.Server.GraphQLServer.ExecuteRequestAsync(RequestContext context) in C:\\JSL\\VIQCore\\2020Net\\ngraphql\\src\\NGraphQL.Server\\Server\\GraphQLServer.cs:line 96"
      }
    }
  ],



~~~C#
MapEntity<IUser>().To<User>(x => new User { HasMemberRole = x.Member != null, HasVendorRole = x.Vendor != null, Officer = x.ToOfficerModel() });
 
 public static Officer ToOfficerModel(this IUser user)
        {
            if (user?.OfficerCommunity == null) return null;
            return new Officer
            {
                Community = user.OfficerCommunity.ToModel(), // this line will cause the error
                Name = user.Name,
                Password = user.OfficerPassword
            };
        }
~~~

**Comment by rivantsov** [comment]
ok, let me think about this

**Comment by rivantsov** [comment]
that error really puzzles me. can you please put a breakpoint in ModelBuilder_EntityMappings.cs, line 91, where the failing call is made, and see the value and type of the ent argument (should be IUser)? somehow runtime does not like it there. Once you stop there, before it fails, explore the iUser value, its OfficerCommunity prop, and then inside it. 
The other place to breakpoint is this ToModel(this ICommunity c) method, but it looks like execution does not get there at all.

as for problem with modeling Officer type in general, yes it looks like a problematic case, and a place for improvement the modeling/mapping methods in NGraphQL. Currently entity-to-GraphQLType mapping is one-to-one, and it should be more like many-to-many I think, but it requires some design rework

**Comment by jasonlaw** [comment]
Somehow the runtime didn't stop at the breakpoint at line 91.

I debug the InvokeFieldReader and it seems trying to call an invalid expression.
![image](https://user-images.githubusercontent.com/107820/107999511-7c355100-7022-11eb-9f8d-466e9f32f7c8.png)

I further check how the invalid expression is built, hope this will help.

![debug_officer_mapping](https://user-images.githubusercontent.com/107820/107999625-cfa79f00-7022-11eb-8920-1ea7cacf5ba8.gif)

**Comment by rivantsov** [comment]
you know that thing drives me crazy, trying to repro it, building similar setup, but so far everything works as it should.. damn...
 looking into this

**Comment by rivantsov** [comment]
up above in one of the listings, you write: 

Community = user.OfficerCommunity.ToModel(), // this line will cause the error

so if you comment out this line all works?!

**Comment by rivantsov** [comment]
that would be strange, since it is method call inside compiled method, and then likely has nothing to do with this expr builder and compilation of expr. Can it be smth wrong with this ToModel call?

**Comment by rivantsov** [comment]
might something to do with Lazy loading of user.Community, it should go to db to lookup the record, maybe this goes wrong. Try playing with it, like explicitly touching this prop, in resolver or somewhere, before returning the data when this invocation happens

**Comment by jasonlaw** [comment]
I don't think it is due to the lazy loading, tried with the following code also hit the same error:
~~~C#
 public static Officer ToOfficerModel(this IUser user)
        {
          //  var community = user?.OfficerCommunity;
            //if (community == null) return null;
            return new Officer
            {
                Community = new Community {
                                    Address = "qq",
                                    City = "aa",
                                    Country = "aa",
                                    Description = "aa",
                                    Id = "aa",
                                    Name = "aa",
                                    Postcode = "aa",
                                    State = "aa",
                                    UseLogoAsBackgroundImage = false,
                                    Logo = null
                            },
                Name = user.Name,
                Password = user.OfficerPassword
            };
        }
~~~

While this one has no error.
~~~C#
 public static Officer ToOfficerModel(this IUser user)
        {
          //  var community = user?.OfficerCommunity;
            //if (community == null) return null;
            return new Officer
            {
                Community = null,//user.OfficerCommunity.ToModel(), // this line will cause the error
                Name = user.Name,
                Password = user.OfficerPassword
            };
        }
~~~

Somehow I think it is due to it try to convert the Community.

I have further testing by removing this mapping.
~~~C#
MapEntity<ICommunity>().To<Community>();
~~~

It is working fine without the mapping definition.

**Comment by jasonlaw** [comment]
~~~C#
  public class CommunityGraphQLModule : GraphQLModule
    {
        public CommunityGraphQLModule()
        {
            ObjectTypes.Add(typeof(Community), typeof(UploadFile), typeof(User), typeof(Member), typeof(Vendor), typeof(Officer));
            QueryType = typeof(ICommunityQuery);            
            ResolverTypes.Add(typeof(CommunityResolvers));

          //  MapEntity<ICommunity>().To<Community>(); // After commenting this line, the officer community can be parsed without error.
            MapEntity<IFile>().To(x => new UploadFile { Url = x.ToUrl() });
            MapEntity<IUser>().To(x => new User { HasMemberRole = x.Member != null, HasVendorRole = x.Vendor != null, HasOfficerRole = x.OfficerCommunity != null, Officer = x.ToOfficerModel() });
            MapEntity<IMemberInCommunity>().To(x => new Member { AdminLevel = x.Admin });

            // Workaround to have 1-1 mapping.
            // MapEntity<IUser_>().To<User>();
            // MapEntity<IOfficer_>().To<Officer>();
            // MapEntity<IMember_>().To<Member>();
        }

    }
~~~

**Comment by rivantsov** [comment]
thanks for the info. wellll, that's really puzzling, it means nothing wrong with expression builder. But somehow this mapping statement messes it all up. let me think about this

**Comment by jasonlaw** [comment]
Just my guess, when we have mapping define, for eg,
MapEntity<ICommunity>.To<Community>();

Any result from expression for Community attribute assignment, it will always go through the mapping process again, even those the result itself is already the final Community type, hence causing the error.

**Comment by rivantsov** [comment]
I think you are right, something like this is happening here; I did not repro it yet, but I think it is the case, I traced/analyzed the code. 
The fix is not trivial, it is more like small redesign of this part, and model mapping in general. I really resist to do some quick ugly patch, the problem is a bit deeper. And you (me actually) are lucky you hit it right from the start. It will take a few days at least.
thank you

**Comment by rivantsov** [comment]
reproduced it.. thinking about fix

**Comment by rivantsov** [comment]
fixed, patched. try it pls

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks for the fixes, it works well now.

Btw, do we still expect many-to-many mapping mechanism in future?

> Currently entity-to-GraphQLType mapping is one-to-one, and it should be more like many-to-many I think, but it requires some design rework.

**Comment by rivantsov** [comment]
yes, this redesign is still in the plans.
