### ISSUE TITLE
Adding NewEntity to ListCollectionView throws Exception

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#17]
ListCollectionView lcv = new ListCollectionView(session.GetEntities<ICustomer>().OrderBy(x => x.CustName).ToList());
ICustomer e = session.NewEntity<ICustomer>();
lcv.AddNewItem(e);

An unhandled exception of type 'System.Exception' occurred in Vita.dll
Additional information: Object {NoNewItem} is not Entity, cannot retrieve Record field.

Test project attached at codeplex. (Uploding here doesn't works...)

**Comment by rivantsov** [comment]
pls post full stack trace

**Comment by sapatag** [comment]
a következő helyen: Vita.Common.Util.Throw(String message, Object[] args)
   a következő helyen: Vita.Entities.EntityHelper.GetRecord(Object entity)
   a következő helyen: Vita.Entities.Runtime.EntityBase.Equals(Object obj)
   a következő helyen: System.Object.Equals(Object objA, Object objB)
   a következő helyen: System.Windows.Data.ListCollectionView.SetNewItem(Object item)
   a következő helyen: System.Windows.Data.ListCollectionView.BeginAddNew(Object newItem, Int32 index)
   a következő helyen: System.Windows.Data.ListCollectionView.<>c__DisplayClass50_0.<AddNewCommon>b__0()
   a következő helyen: MS.Internal.Data.SynchronizationInfo.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   a következő helyen: System.Windows.Data.BindingOperations.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   a következő helyen: System.Windows.Data.ListCollectionView.AddNewCommon(Object newItem)
   a következő helyen: System.Windows.Data.ListCollectionView.AddNewItem(Object newItem)
   a következő helyen: VitaTest.Program.Main(String[] args) hely: D:\Projects\Tests\VitaTest\VitaTest\Program.cs, sor: 22
   a következő helyen: System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   a következő helyen: System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   a következő helyen: Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   a következő helyen: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   a következő helyen: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   a következő helyen: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   a következő helyen: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   a következő helyen: System.Threading.ThreadHelper.ThreadStart()

**Comment by rivantsov** [comment]
first, there's a bug in Vita, in Equals method, it should not throw ever. I will fix that (already did), will be there in next push
Still, from stack trace appears you're not doing it right. You should add the new entity to entity list that is returned from this LINQ expr in constructor parameter, not to ListCollectionView. It tries to check ViewItem or smth to list items.
 Save the returned list in a field and add to it. I guess you need to convert the returned list to observable list, smth like this:

ObservableCollection<ICustomer> _custList; 
_custList = new ObservableCollection<ICustomer>(session.EntitySet<ICustomer>().OrderBy());
var newCust = session.NewEntitty<ICustomer>();
_custList.Add(newCust); 

Sorry, never worked with WPF

**Comment by sapatag** [comment]
Thx for the quick answer. I simplified the simple from a WPF MVVM ViewModel, with observablecollections etc. 
I can avoid the exception with creating a model class and working with the modells, but I like Vita's elegant concept of interfaces.

**Comment by rivantsov** [comment]
should be fixed now (entity comparison)
