### ISSUE TITLE
[Question] Direct from reference vs EntitySet

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#176]
Hi @rivantsov ,

May I know is there any different in performance for the following 2 codes?

EntitySet
```
            var userNameHash = MyApp.GetHashingService().ComputeHash(userName);
            var session = EntityHelper.GetSession(company);
            return session.EntitySet<IAccount>()
                          .Where(x => x.Login.UserNameHash == userNameHash && x.Login.UserName == userName)
                          .FirstOrDefault();

```

Directly from reference
```
 var userNameHash = MyApp.GetHashingService().ComputeHash(userName);
            return company.Accounts
                          .Where(x => x.Login.UserNameHash == userNameHash && x.Login.UserName == userName)
                          .FirstOrDefault();
```

Many thanks.

**Comment by rivantsov** [comment]
of course; the second version, when you touch company.Accounts, it retrieves all Accounts for a company; then it's just Linq-over-objects, search in a LIST. But additional trouble is resolving x.Login reference, each might require query to database as goes thru each account in the list. 

the first version is a  single query delivering exactly the record(s) you need.

**Comment by jasonlaw** [comment]
Clear now, thank you very much!
