### ISSUE TITLE
Is the vdbtool dbfirst supposed to work on sqlite?

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#18]
I can partialy use vita on my existing sqlite db, only the vdbtool does not works.
Partialy means that I can insert perfect new records through manually created entity interfaces, but reading those records throws invalid cast exception on every int (long) and DateTime field. My old existing program reads the vita-inserted records perfectly  through System.Data.SQLite.
String and decimal properties are working fine.

**Comment by rivantsov** [comment]
vdbtool - if you are talking about db-first scenario, constructing entity model from db, the anwser is NO, SQLite database does not have types, all columns are essentially variants/blobs. 
Now, you say if you manually code entities, and then try to use them, it works ok on insert but fails on read back? what are property definitions on these fields. Also note that BookStore app works OK on SQLite, run Extended unit tests for SQLite, then look at book entities, setup, and compare with your project, see what you doing differently

**Comment by rivantsov** [comment]
if you still can't resolve it, pls send me some entity definitions and I'll have a look

**Comment by sapatag** [comment]
Thanks for quick response!
Pragma table_info says about my existing int field's type is "int"
Entity property is:
        [Column]
        int i { get; set; }
Vita can write into it, but fails on read back.
If I let Vita create the table, Pragma table_info says that the field's type is "integer", and Vita can write and read back.
DateTime is similar:
In the existing table it's "date", in the Vita created it's "text".

**Comment by sapatag** [comment]
I tried to solve the int with
[Column(DbType = DbType.Int32)]
int i { get; set; }
Exception info is: 
Failed to convert column value '1', type System.Int32. Converter for column type System.Int64, property type System.Int32.
[Column(DbType = DbType.Int64)]
long i { get; set; } or Int64 i { get; set; } 
throws invalidcastexception

**Comment by sapatag** [comment]
Here is one cr. for an existing table:
CREATE TABLE mdf_item (
    itemid int not null,
    name varchar(70) not null collate hungarian default (''),
    unit varchar(12) null collate hungarian default (''),
    price double not null default (0),
    totprice double not null default (0),
    pricetype int not null default (0),
    salesacccode varchar(12) null collate hungarian,
    vatacccode varchar(12) null collate hungarian,
    vatid int null,
    detailvatid int null,
    vatcode varchar(12) null collate hungarian,
    vtsz varchar(10) null collate hungarian,
    adddate date not null default (CURRENT_TIMESTAMP),
    adduser int not null default (0),
    primary key (itemid)
)
All int fields and the date field produces the error, all strings and doubles works fine.

**Comment by rivantsov** [comment]
and what is the entity definition for this table? 
Try  declaring int props in entities as Int64

**Comment by sapatag** [comment]
I did as I wrote two comments before.

**Comment by rivantsov** [comment]
do you have a small test project that you can share with me, so I can quickly run and debug it?

**Comment by rivantsov** [comment]
All this looks really puzzling to me, unless... one thing. Here's my main question: 
You mention your old app. So, are you starting with empty database? So when VITA fails to read the entities, are these records were just inserted by VITA engine, or these are old records created by your app? Depending on the answer, here is what I think
1 - VITA fails to read old, pre-existing records. That I can explain. The SQLite driver implemented in VITA is quite strict (stupidly) on expected data. For ex, it stroes int data (any size) as Int64 - always, and does not even check when it reads it back (again, stupidly). When all data is created by VITA, it works OK. But when you hit old data which actually can contain int32, it breaks. I missed that scenario, with pre-existing databases - but I can probably quickly fix it. And the same with the data - Vita stores dates as strings, and if old data has binary bytes, it would blow up
2. VITA engine fails to read the records it just created in clean/empty database. In this case I have no idea, we need to look at it more..
So, what's the answer? Again, if it is preexisting data, I can push the fix with next version, coming in a few days.

**Comment by sapatag** [comment]
Shortly: the case is 1.

The db contains old existing tables. (You can see one create table upper.) Some tables are empty, some are not. Vita can't read the int and date fields. Vita can insert new records, but can't read back the int and date fields. The new records inserted by Vita are working perfectly in the existing app.

Some technical background: the existing app handles the SQLite db with pure System.Data.SQLite. Writing the create table stmt is the only thing what we do "manualy". System.Data.SQLite handles perfectly all mappings between table fields and entity properties.

One more comment on vdbtool dbfirst with sqlite: I think, that the sqlite_master table and pragma table_info contains every info to create an entity interface.

I would like to use Vita very mutch. I'm rather old school, working with MSSQL from it's 7.0 version and 6 years with SQLite databases, but Vita is the first ORM witch really appeals to me.

**Comment by rivantsov** [comment]
All right, we are getting somewhere, things are more-less clear now. It is the initial assumptions of my SQLite driver that are the trouble. I will fix that, give me a few days. Ability to read 'old' data should be easy. The bigger challenge is to provide a way to specify the write format for certain types, so that inserted records match the format of records inserted by other pre-existing app. I will try to come up with the solution. 
About dbfirst - will look into this, probably not this release. So give me a few days, will push new version with a lot of other new stuff, need to polish it.

**Comment by sapatag** [comment]
Thank you!

Roman Ivantsov <notifications@github.com> ezt írta (időpont: 2017. jan.
20., Pén 18:33):

**Comment by rivantsov** [comment]
Pls help me understand something. In the Create Table SQL you show above, what the heck this line means: 
adddate date not null default (CURRENT_TIMESTAMP),

There's no date type (or storage class) for dates. So what does it mean? And is this OK with SQLite, to use 'date' as type?
 and what is actual type of values you store in this column? what do you assign to db command parameter - real value? or then when you read from data reader, what value comes out for this column?

**Comment by sapatag** [comment]
Hi, CURRENT_TIMESTAMP means nothing as I know, I inherited it from a college. System.Data.SQLite handles the types, SQLite does not care. Theese tables are working for more then 7 years at hundreds of customers.

**Comment by rivantsov** [comment]
I understand that SQLite does not care, and I do not dispute that your app is working OK. Just want to get some info, because I'm sure you're better expert in this. I do not actually use SQLite on daily basis, so would like to get your expertise
 System.Data.SQLite handles the types - in what sense? You use .NET provider  to send/receive the data.   SQLite provider for .NET implements IDataReader that you use to read coming rows. Something like: 
object value = reader["DateColumn"];
The return type for the reader's method is object, while actual return values have specific type. What is this type of returned value for a date column in your case? 
Secondly, when you need to use date value in SQL query, like 
   WHERE mdf_item.dateadd > ?2017-01-24? ) 
- how exactly you format/express this date constant in SQL?
(I need this exact info, because I have to implement certain conversions at very low level)
My prev question was about using 'date' as type in SQLite Create-table statement. I am really confused here, because docs do not mention 'date' as storage class

**Comment by sapatag** [comment]
The app is using:
string.Format("'{0:yyyy-MM-dd HH:mm:ss}'", date); //2009-11-10 10:05:18

I'm not an expert on SQLite, I inherited a code, witch works, but I have to write some new modules, and I rather use something I like for it.

**Comment by rivantsov** [comment]
Can you please do the following experiment for me?
add this code to file where you setup your Vita app with SQLIte: 

    // when you create dbSettings to connect to db
    dbSettings.Driver.TypeRegistry.Converters.AddConverter<string, DateTime>(SQLiteStringToDate, SQLiteDateToString);

    private object SQLiteDateToString(object x) {
      if(x == null || x == DBNull.Value) //bkpoint here
        return DBNull.Value;
      var dt = (DateTime)x;
      var result = Vita.Common.ConvertHelper.DateTimeToUniString(dt);
      return result;
    }

    private object SQLiteStringToDate(object x) {
      if(x == null || x == DBNull.Value)  //bkpoint here
        return DBNull.Value;
      var str = x as string;
      if(string.IsNullOrWhiteSpace(str))
        return DBNull.Value;
      DateTime result = DateTime.Parse(str, CultureInfo.InvariantCulture); //, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal);
      return result;
    }

and put breakpoints inside methods (see comments in code). This will set the converters inside the driver and would allow you to intercept at the moment when value is read from the database. 
Then run the app against the table with DateTime column. When it stops in SQLiteStringToDate method, copy the coming value, and step thru until the last Parse call, see if it fails and why. 
Pls send me the results. 
I am trying to guess what exactly might be failing, looks like you guys store dates as strings, so it's not clear to me, I checked - with the format you posted, it should work.

**Comment by sapatag** [comment]
'ConvertHelper' does not contain a definition for 'DateTimeToUniString'

**Comment by rivantsov** [comment]
replace this call with 
      var result = dt.ToString( "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffff");

**Comment by sapatag** [comment]
SQLiteStringToDate(object x):
x is already DateTime at the break: x = {2017. 01. 18. 8:53:52}

**Comment by rivantsov** [comment]
all right, thanks! that arrangement looks really strange to me, looks like db contains binary bytes of Datetime, wonder how ordering and dates comparison <> works with this. I will do some more experiments

**Comment by sapatag** [comment]
It all works fine is the existing app:)

**Comment by rivantsov** [comment]
should be fixed now, changed to rely mostly on SQlite.net provider default conversions

**Comment by sapatag** [comment]
It works, thank you!
