### ISSUE TITLE
NewFunction feature

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#183]
This is now possible,

```
[SqlExpression(DbServerType.MsSql, "DATEADD(YEAR, {years}, {dt})")]
[SqlExpression(DbServerType.MySql, "DATE_ADD({dt}, INTERVAL {years} YEAR)")]
[SqlExpression(DbServerType.Postgres, "({dt} + {years} * INTERVAL '1 year')")]
[SqlExpression(DbServerType.Oracle, "ADD_MONTHS({dt}, 12 * {years})")]
[SqlExpression(DbServerType.SQLite, "DATE({dt}, '{years} years')")]
public static DateTime DbAddYears(this DateTime dt, int years) {
CannotCallDirectly();
return default;
}
private static void CannotCallDirectly([CallerMemberName] string methodName = null) {
throw new NotImplementedException(
$"Function '{methodName}' may not be called directly, only in LINQ expressions.");
}
```
I have a Function created in SqlServer and is it possible to converte this function to use the new capability?

`USE [OutraDB1]
GO
/****** Object:  UserDefinedFunction [dbo].[DiasVencidos]    Script Date: 19/06/2021 22:38:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[DiasVencidos] ( @DocumentoID uniqueidentifier ) RETURNS INT 

AS BEGIN

Declare @resultado as int

Select @resultado = ISNULL(DATEDIFF(DAY,Documentos.DataDocumento,GETDATE()),0) From Documentos 
Where Documentos.ID = @DocumentoID AND Documentos.Saldo > 0 AND Anulado = 0 AND Finalizado = 1 AND Suspensa = 0
AND TipoMovimento = 4 AND Assinado = 1
      
Return ISNULL(@resultado,0)
END`

Thanks.

**Comment by rivantsov** [comment]
yes, try it

**Comment by rubenalves** [comment]
That is the problem,

with your example with addyears i canot see where i can use / create the function:

[SqlExpression(DbServerType.MsSql, "DATEADD(YEAR, 5, {table}.LicenseIssuedOn)")] is it here i add my function?

**Comment by rivantsov** [comment]
add property on IDocumentos
	
	[DbComputed(kind: DbComputedKind.NoColumn)]
    [SqlExpression(DbServerType.MsSql, "dbo.DiasVencidos({table}.ID)")]
	int DiasVencidos {get;}
	
then reading this prop on a doc would invoke this function

**Comment by rubenalves** [comment]
Works very well.

Thank You.

**Comment by rivantsov** [comment]
Looking at the SQL expression, it might be suboptimal. I makes a SELECT by docId inside the function to retrieve the record, while there record is essentially already there, we take Id from it. It might be query optimizer accounts for this and optimizes it out, but it might be better to try to put the expression in WHERE directly into the SQLExpression attribute, using {table}.FieldName to reference field names

**Comment by rubenalves** [comment]
The function is only used when i get a list of documents, and it is very fas as it is, so will not be a problem.
Thanks,
Continue the greate work :)

**Comment by rivantsov** [comment]
well, just one factor: you with direct expr you don't need to create the function manually or with script on new installations!
but whatever fits your process... glad it works well

**Comment by rubenalves** [comment]
I am seing a new alert in visual studio that

[Computed(typeof(DocumentoExtensions), nameof(DocumentoExtensions.GetExtenso)), DependsOn(nameof(TotalDocumento))]

is Obsolete,

Os this not the correct way to use it now?

**Comment by rivantsov** [comment]
just switch the order of params in Computed attr

**Comment by rubenalves** [comment]
It works.

Thanks.


Com os melhores cumprimentos,

Ruben Alves
Móvel: 916887379
Email: ***@***.***

De: Roman Ivantsov ***@***.***>
Enviada: 21 de junho de 2021 18:12
Para: rivantsov/vita ***@***.***>
Cc: rubenalves ***@***.***>; Author ***@***.***>
Assunto: Re: [rivantsov/vita] NewFunction feature (#183)


just switch the order of params in Computed attr
