### ISSUE TITLE
[Question] Will computed column re-compute?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#184]
Hi @rivantsov ,

Suppose I have a schema as below:

~~~C#
[Entity]
public interface IBerth
{
  IList<Unloading> Unloadings {get;}
 
  [Computed("CalcUnloadingCosts", typeof(ModuleClass)]
  double UnloadingCosts {get;}

}

public static  double CalcUnloadingCosts( IBerth berth )
{
  return berth.Unloadings.Sum( x => x.Costs );
}
~~~

Will the Berth.UnloadingCosts recalculated whenever there is changes in either Unloadings list, eg, add/remove from the list or changes in any Unloading.Costs ?

Thank you!

**Comment by rivantsov** [comment]
no it won't,

**Comment by jasonlaw** [comment]
Alright, thanks for the clarification.
Guess I have to avoid it and use extensions method instead.
Thanks.
