### ISSUE TITLE
[Question] How to achieve LinkedListNode?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#185]
Hi @rivantsov ,

May I know how to achieve the LinkedListNode for the Unloadings?
~~~C#
[Entity]
public interface IBerth
{
  IList<Unloading> Unloadings {get;}
}
~~~

Thank you!

**Comment by rivantsov** [comment]
what the heck is LinkListNode?!

**Comment by jasonlaw** [comment]
List with Previous/Next supported in the List's element? [Reference](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlistnode-1?view=net-5.0)

Here is what I would like to achieve. 
![image](https://user-images.githubusercontent.com/107820/126416196-eaf47b4c-2a84-475d-899b-c3835f770eeb.png)

**Comment by rivantsov** [comment]
IList<Unloadings> - if it is entity-list type property, list of related entities, then it is implemented as List<T>, not LinkedList, so there are no LinkedListNode's there.

**Comment by jasonlaw** [comment]
Alright, just try my luck here if this is possible or you may have some idea on it. :)
Thanks anyway. 👍
