### ISSUE TITLE
Session.SaveChanges

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#186]
Hi @rivantsov ,

In BookStore GraphQL example, we have  code as below, which checking changes count before saving.

~~~c#
  public void EndRequest(IRequestContext request) {
      if (_session.GetChangeCount() > 0)
        _session.SaveChanges(); 
    }
~~~

This make me think why the checking is not inside session.SaveChanges() method? 
I am sure when there is nothing changes, the SaveChanges should have do nothing, unless I have missing something.

**Comment by rivantsov** [comment]
it does this check, but there is more stuff there; you can have scheduled operations (run-on-Save), fire events etc
this check is useful if only for illustrative purpose; otherwise there would be questions - what if there's no changes?!

**Comment by jasonlaw** [comment]
That make sense, thanks for the clarification!
