### ISSUE TITLE
Search predicate with Or

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#188]
Hi @rivantsov ,

May I know how do we compose a search predicate with Or grouping, for eg: A AND (B OR C)?

In the following code, the result seems like A AND B OR C, which has different meaning.
~~~c#
var where = session.NewPredicate<IAnnouncement>()
                               .And(x => x.Community == community)
                               .AndIfNotEmpty( searchParams.Subject, x => x.Subject.Contains(searchParams.Subject))
                               .OrIfNotNull( searchParams.Content, x => x.Content.Contains(searchParams.Content))
                               .AndIfNotEmpty(searchParams.After, x => x.CreatedOn >= searchParams.After)
                               .AndIfNotEmpty(searchParams.Before, x => x.CreatedOn <= searchParams.Before);
~~~

**Comment by rivantsov** [comment]
sorry for the delayed response; looking into this, good case but apparently not so trivial

**Comment by rivantsov** [comment]
added an example in tests: 
https://github.com/rivantsov/vita/blob/master/src/6.UnitTests/Vita.Testing.ExtendedTests/LinqTests/LinqTests_Search.cs#L106

**Comment by jasonlaw** [comment]
Thanks for the example, it is very helpful!
