### ISSUE TITLE
Just curious .....

### ISSUE THREAD

**Issue by ryanhelms** [rivantsov/vita#19]
Hello,

  I find this project very intriguing and have began using it with my team on a new financial platform. Do you intend to keep this going? We'll surely begin contributing to it as time and feature requirements permits. From what we have seen, we love it. So good job and thanks for what you've done so far.

-Ryan

**Comment by rivantsov** [comment]
thanks. as for continuing - of course, this project is used at my daily job, I depend on it for making a living
