### ISSUE TITLE
[Question] Matching list of strings

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#192]
Hi @rivantsov ,

I would like to have query in MySQL like below.
select * from table where field in ( 'value1', 'value2')

May I know how to achieve that with the EntitySet?

Eg:

var invoices = "001,002,003";
var query = session.EntitySet<IInvoice>().Where( x => x.InvoiceNo In invoices) // How to do here?

Thanks in advance.

**Comment by rivantsov** [comment]
look at TestLinqArrayContains in ExtendedTests project, it contains sample code for this case

**Comment by jasonlaw** [comment]
Cool, thanks!
