### ISSUE TITLE
Query does not get executed

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#196]
I am trying to do this

if (!string.IsNullOrEmpty(Fornecedor))
            {
                var str = Fornecedor.Split(' ');
                query2 = str.Aggregate(query2, (current, s) => current.Where(c => c.Assunto.Contains(s)));
                var listFor = query2.ToList();
                foreach (var fornecedor in listFor)
                {
                    query = query.Where(c => c.Fornecedores.Any(t => c.Id == fornecedor.Id));
                }
                var temp= query.ToList();
            }
the application simpli does nothing, var temp= query.ToList(); does not throw a error but the query is  not executed.

Is there a correct way to do this kind of query?
Thanks.

**Comment by rivantsov** [comment]
what 'listFor' contains after execution of query2? 
what's the meaning of foreach loop - you add multiple WHERE conditions, they will all be AND-ed, so you look for containing every matching Id?

**Comment by rubenalves** [comment]
I use this alot with Sql Server and it works fine, this i am using SqlLite in a little app, can it be a problem of sqllite?

**Comment by rubenalves** [comment]
I get it to work, it was not the best way to do it but it is a very small application and it is woking now.
Thanks for your time .
