### ISSUE TITLE
SqlServer char(11) not null default ' '

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#20]
I also inherited a MSSQL db :(
It's full of colums like:
DAADOSZ char(11) not null default ' ',
vdbtool dbfirst declares:
        [Column("DAADOSZ", DbType = DbType.AnsiStringFixedLength, Size = 11)]
        string DAADOSZ { get; set; }

After session.NewEntity session.SaveChanges fails if DAADOSZ null, or string.Empty, or " " (space).
How can I write theese empty columns? (without real data)

UPDATE: with NullableAttribute
        [Column("DAADOSZ", DbType = DbType.AnsiStringFixedLength, Size = 11), Nullable]
        string DAADOSZ { get; set; }
I can write "" (empty string) to it. I can live with it:)

**Comment by rivantsov** [comment]
With Nullable the app changes column to be nullable; you can live with that - great, but it does not sound right, looks like system automatically replaces space or empty string with Null, I will look into making it controlled by a flag. For AnsiStringFixedLength, Size-11 I guess it should pad it with spaces to 11 space string

**Comment by rivantsov** [comment]
should be fixed now, single space should be allowed
