### ISSUE TITLE
Microsoft.Data.SqlClient 4.0.0

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#201]
If we upgrade Microsoft.Data.SqlClient to 4.0.0 the Vita canot connect to the sql server, some error on certificates.

Not a big problem as we can rolback to 3.0.1 but we have to be carefull on that.

Thanks.

**Comment by rivantsov** [comment]
add
  TrustServerCertificate=True
to the conn string; just tested, it looks like it works. looks like they screwed up smth there

**Comment by rubenalves** [comment]
works very well.
Thanks.

**Comment by rubenalves** [comment]
I have it working in prodution and 0 problems,
Thank you very much for the solution.
