### ISSUE TITLE
Is vita Support SAP Sql Anywhere Database ?

### ISSUE THREAD

**Issue by sravangontla** [rivantsov/vita#206]
Hi Team,
Can you please confirm that vita supports SAP Anywhere Database, If yes guide the documentation how to connect and so on...

Looking for :
Asp.net core 
SAP SQL Anywhere (database)

**Comment by rivantsov** [comment]
no, it does not support it. But I guess since SQL Anywhere is close to SQL Server (same hist origin), and there's ADO.NET provider, building a VITA connector would not be too difficult.
