### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#207]
Hi @rivantsov ,

Could you please add the { get; set; } into the **SearchResults** properties? 
Without it the swagger will not show the schema properly.

Thank you very much!

**Comment by rivantsov** [comment]
I suspect the problem is that by default ASP.NET core uses this new Json serializer (System.Text.Json) they added, which is crappy, it ignores fields. Switch to Newtonsoft json in your project, as described here: 
https://www.ryadel.com/en/use-json-net-instead-of-system-text-json-in-asp-net-core-3-mvc-projects/

**Comment by jasonlaw** [comment]
Thanks, this has been resolved by adding the followoing:

```
services.AddControllers().AddNewtonsoftJson();
services.AddSwaggerGenNewtonsoftSupport();
```
Anyway, I still hope the changes can be made so that we have options for either way.

**Comment by rivantsov** [comment]
well, I'd rather not doing the change for now; because this problem (not serializing fields) will show up on any dto object used in APIs. This is really STUPID on their part to do it this way, create Json serializer that ignores fields, and I am not inclined to compensate for this stupidity

**Comment by jasonlaw** [comment]
It looks like there is an options [IncludeFields](https://github.com/dotnet/runtime/issues/876) added since .NET 5 but somehow didn't apply to swagger.

Some time it can be quite confusing with mixing of NewtonsoftJSON and System.text.Json, especially to control how the output should show, since both has different attribute syntax.

Anyway, this is not a show stopper but rather something really nice to have, will closing this.
