### ISSUE TITLE
[Need advice] Multi-tenant design

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#210]
Hi @rivantsov ,

For a multi-tenant application, if the tenant data are split by database, can we still have another database with only login entities but accessible from the tenant session?

From the MultiTenantTests in the source code, the DB model are identical for the 2 data sources (or tenant), in this case, suppose we have some shared data, eg, login or some master data, how should we handle it?

Thanks in advance.

**Comment by rivantsov** [comment]
Well, all I can suggest is to create a separate EntityApp for this shared db, and use separate IEntitySession instances when working with this database. What you don't have is ability to reference Entity instances across databases; like order.Customer, if IOrder and ICustomer live in different databases, you can't do this; all you have is IOrder.Customer_Id, and you have to query for customer entity explicitly thru another session. 
I thought before about enabling this kind of references, making apps/sessions linked, so you can actually do order.Customer; it seems like it can  be done. But this is for some future.

**Comment by jasonlaw** [comment]
This is helpful, thanks!
