### ISSUE TITLE
Version 3.5 pushed.

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#213]
Details will follow. Sorry it took so long. Big internal refactoring of model building, new Key building process (PK, FK, indexes)
Moved apps, tests to Net6

Details here: 
https://github.com/rivantsov/vita/wiki/Code-changes-history

**Comment by rubenalves** [comment]
Hello,

I have updated to 3.5. and my model does not Build, is there any breaking changes?

**Comment by rivantsov** [comment]
sorry to hear this, lets fix it. There are no breaking changes, everything should be compatible, all changes are internal. 
What's the error messages? 
The easiest and quickest way would be if you can (if possible) send me the SQL script of database (without data) to rivantsov AT gmail dot com, so I can debug the model build phase. I promise non-disclosure and keep it to myself

**Comment by rubenalves** [comment]
The problem is there are no eror messages, only that the model does not Build.
I will try again and se if i can see a error on the debugger

**Comment by rivantsov** [comment]
the exception StartupFailedExc should have list of errors inside

**Comment by rubenalves** [comment]
O got this error:
Initializing EntityApp TsGest 2023.====================================
  Building entity model...
AuditMensagem.ID: Index/key attribute (Vita.Entities.PrimaryKeyAttribute) on member should not have explicit member list.

**Comment by rivantsov** [comment]
so can you pls share the c# source of this property ID of AuditMensagem entity, with its attributes?

**Comment by rivantsov** [comment]
Looks like you just need to remove arguments in Primarykey attribute on this property; the property itself (ID) is the column that is PK

**Comment by rubenalves** [comment]
It hade atributes and thar entity is not needed any more, so it is runing fine now. Thanks.

**Comment by rivantsov** [comment]
More stuff in 3.5 - packed vitaDbTool into a tool nuget package; see more in code changes history
