### ISSUE TITLE
GUID with Auto

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#218]
Hello,

I have definitions o some classes like this
---------------
 [PrimaryKey,Auto]
    Guid ID { get; set; }
etc....
---------------

Id i assingn a new value, it gets override on save changes on create new entoty, is this by design or a eror no my code?

Thanks.

**Comment by rivantsov** [comment]
it is either Auto or not. 
If you put Auto, system assigns new Guid when you create new entity. In this case you don't need the setter on the property, leave only '{get;}' . 
Without Auto, it is like regular property, your code is responsible for assigning new guid value - better do it immediately after you create it through NewEntity.
