### ISSUE TITLE
Allow reference entity without creating foreign key constraint in table

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#221]
Hi @rivantsov ,

Refer to the discussion in #220, here is the issue created for allowing reference entity without creating the foreign key constraint in table.

There are cases where we still want to keep the data even those the reference entity is removed.

Thanks.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

How are you? I hope you are doing fine.

I am just wondering what's your plan for this issue, since it has been quite some time already.

It would be great to have this issue fixed since I am getting more the similar use case.

Thank you very much, really appreciate your great work.

**Comment by rivantsov** [comment]
all right, give me a few days, I'll make a minor release, upgrade refs, packages, all that stuff, it's time anyway. thanks

**Comment by jasonlaw** [comment]
great to hear that, thank you very much!!! :)

**Comment by rivantsov** [comment]
done, v3.7.0; 
to suppress db foreign key, add an attr to a ref member: 
[EntityRef(HasDbForeignKey=false)]

**Comment by jasonlaw** [comment]
It is working great so far, thanks.
