### ISSUE TITLE
ExecuteDelete missing parenthesis

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#224]
Hi @rivantsov ,

The execution query is missing parenthesis which could have different results.

~~~C#
var query = session
        .EntitySet<IAuthSession>()
        .Where(x => (x.Id == authSession.Id) || (x.IdentityId == authSession.IdentityId && x.Expires < MyApp.UtcNow));
 session.ExecuteDelete<IAuthSession>(query);
~~~

From log:

DELETE FROM "vrewards_dev1"."AuthSession" 
    WHERE "Id" = @P0 OR "IdentityId" = @P1 AND "Expires" < @P2; 
-- Parameters: @P0='01H4HHVCP2KG4WPXBHBCG3FCDD', @P1='$01H4GA9VFWMRXEBW699XSZVKZR', @P2=[2023-07-04T22:55:38] 
 -- Time 5.6967 ms, [2023/07/04 22:55:38]

**Comment by rivantsov** [comment]
I think the translation is correct. it all based on Oper precedence I think. Try duplicating last part with OR: 
... ...  && (x.Expires < MyApp.UtcNow || x.Expires < MyApp.UtcNow)

see if parenthesis appear

**Comment by jasonlaw** [comment]
Not sure if this is what you are looking for, but the result is still not right to me.

~~~C#
            var query = context
                            .GetSession()
                            .EntitySet<IAuthSession>()
                            .Where(x => (x.Id == authSession.Id) || (x.IdentityId == authSession.IdentityId && (x.Expires < MyApp.UtcNow || x.Expires < MyApp.UtcNow)));
            context.GetSession().ExecuteDelete<IAuthSession>(query);

~~~

DELETE FROM "vrewards_dev1"."AuthSession" 
    WHERE "Id" = @P0 OR "IdentityId" = @P1 AND ("Expires" < @P2 OR "Expires" < @P3); 
-- Parameters: @P0='01H4JFPQRE725391TX95EZ577X', @P1='$01H4GA9VFWMRXEBW699XSZVKZR', @P2=[2023-07-05T07:38:33], @P3=[2023-07-05T07:38:33] 
 -- Time 3.5525 ms, [2023/07/05 07:38:33]

**Comment by rivantsov** [comment]
then I am puzzled, what is wrong with the result for you? Remember that "=" is operation too, and it has the highest precedence value. AND has higher precedence than OR; so SQL is equivalent to source expression even without parenthesis

**Comment by jasonlaw** [comment]
Ahhh...I didn't aware of the operator precedence...sorry about that.....
Thank you so much for the clarification, and sorry again for the confusion.
