### ISSUE TITLE
3.6 not working correctly

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#227]
I have updated to version 3.6 and i have encontered problems, in some parts of my app it is very slow, and when i try to add a complex object it hangs and does not save to the database.

What changes where made in 3.6?

Regards.

**Comment by rivantsov** [comment]
no idea so far, no cardinal changes. One suspect - I enabled SmartLoad by default in EntitySession. It  causes it to do some read-ahead activity, loading all child objects of the type for all loaded entities. Try adding a flag as parameter to OpenSession: EntitySessionOptions.DisableSmartLoad, let's see if it helps with slowness. 
As for complex object hanging - don't quite understand the scenario, let's see later after disabling smart load. 
One thing - can you pls look at logs and timings of queries and see if some queries clearly take way too much time?
sorry for trouble

**Comment by rubenalves** [comment]
I added DisableSmartLoad and it looks ok now, i will make some more tests.

The complex object is a entity with several rrelated entities, like a invoice.

Thanks.

**Comment by rivantsov** [comment]
so, this DisableSmartLoad workaround - did it fix it all? what about complex objects?
I am planning to revert this SmartLoad auto-ON change, looks like it's more trouble than benefit, just need confirmation that it would fix it all

**Comment by rubenalves** [comment]
Hello,

Yes, i disabled the smartload and it is working as expected.

I did not have much time for furder tests because i am refactoring my app.

Just another unrelated question, 
Where can i find examples on creating Views?

I already have one created for working with acumulated values in products and i am trying to make one for customeres by  year,

**Comment by rivantsov** [comment]
ok, I will revert/fix the change to smart loading. As for views examples - in BookStore app, there are couple of views there, all I have

**Comment by rivantsov** [comment]
Hi again
Just FYI, I decided to keep SmartLoad On by default, I believe it is a more common case and is better default. I hope it does not cause any problems
