### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#228]
Hi @rivantsov ,

I have the following error after upgrading to 3.6.0.

Object reference not set to an instance of an object. 
[09/30/2023 01:44:58] ErrorKind:Internal 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vita.Entities.Logging.WebCallLogEntry.AsText()
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Vita.Entities.EntityApp.OnLogBatchProduced(IList`1 entries)
   at Vita.Entities.Logging.LogBatchingService.Buffer_OnBatchProduced(IList`1 entries)
   at Vita.Entities.Logging.ActiveBatchingBuffer`1.FlushImpl(FlushTrigger trigger)
   at Vita.Entities.Logging.ActiveBatchingBuffer`1.OnFlushTimerElapsed()
   at Vita.Entities.Services.Implementations.TimerService.SafeInvoke(TimerSubscriptionInfo subscr)

I am not too sure if this is Vita issue or my code problem, as I am not sure where or how to debug this.
May I know what should I check first?

Thanks.

**Comment by rivantsov** [comment]
Well, it happens in web log, which is a kind of a 'good' thing - that it's not in mainstream logic, but when we try to dump the batched details of the web calls. Bad thing it's happening suddenly. Are you sure it started with the latest update? I see potential spots why it crashes, I will fix it asap (probably revert SmartLoad auto-on, there are complains already), but wonder why this web log failures started. Do you see web log entries in general, for some other calls - or it crashes on all (unlikely)? Can you spot a pattern which web calls /urls are blowing up the log?
thanks and sorry for troubles

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

It didn't happen before the latest update,  however, I am not 100% sure if this a VITA issue, coz I have also done some changes in my code, but quite a minimum one.

I have attached here the log file, please find "System.NullReferenceException".
[Log.zip](https://github.com/rivantsov/vita/files/12781863/Log.zip)

Thank you very much for looking into this.

**Comment by rivantsov** [comment]
Hi
sorry for the delay in response. Most likely I think, the error happens when logger code tries to format log entry and uses Response object (in web context) but response is not there, because I guess there's some other error prior and the call failed before creating response. I will fix that and push update next week
As for your log file - I have some comments, but better do it in private. Pls write me to rivantsov - at - gmail dot com, I will reply with my thoughts
Roman
