### ISSUE TITLE
Operation Triggers

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#229]
Is there any way i dan get the like a list of inserted, deleted or updated records after the save changes?

This is my need, use database triggers but that is very messy,

Something like a hook i can connecto to so that i know what object was created or deleted, etc...

Here is a pratical example.

I have ProductAcumValues Table, it has the sum of all purchaged and sold for ever month,

Comp01 and Vend01
ComP02 and Vend02
etc...

i need to update AcumValues based on if it is a purchase, invoice, if deleted, etc.

Thanks.

**Comment by rivantsov** [comment]
Use EntityEvents or EntityAppEvents: 
https://github.com/rivantsov/vita/blob/master/src/1.Framework/Vita/1.AppModel/Events/EntityEvents.cs

If you are interested in specific entities, get EntityInfo from Model, then hook to one of events in entityInfo.Events
This will fire each time when this entity type is inserted or updated or deleted

**Comment by rivantsov** [comment]
you can do it even simpler; right before session.SaveChanges you can inspect the list of entities that are about to be updadet. Look at method EntitySessionExtensions.GetChangeCount. You cast session to EntitySession class, and then get the session.RecordsChanged list. you can run thru it and find entity types that are of interest, and if found, put them somewhere in variable and then run these summarization actions after SaveChanges

**Comment by rubenalves** [comment]
Can you just give me a simple exemple?

I canot get the change count list.

Thanks.

Com os melhores cumprimentos,

Ruben Alves
Móvel: 916887379
Chamada para a rede móvel nacional.
Email: ***@***.******@***.***>

***@***.***

De: Roman Ivantsov ***@***.***>
Enviada: 22 de outubro de 2023 16:50
Para: rivantsov/vita ***@***.***>
Cc: rubenalves ***@***.***>; Author ***@***.***>
Assunto: Re: [rivantsov/vita] Operation Triggers (Issue #229)


you can do it even simpler; right before session.SaveChanges you can inspect the list of entities that are about to be updadet. Look at method EntitySessionExtensions.GetChangeCount. You cast session to EntitySession class, and then get the session.RecordsChanged list. you can run thru it and find entity types that are of interest, and if found, put them somewhere in variable and then run these summarization actions after SaveChanges

**Comment by rivantsov** [comment]
here's the link to method: 
https://github.com/rivantsov/vita/blob/9adcc3c807f748df087fee00bae347c9730ab10c/src/1.Framework/Vita/2.Operations/StaticHelpers/EntitySessionExtensions.cs#L73

session.RecordsChanged is the list of changes

**Comment by rubenalves** [comment]
Hello, i did not not understand how to work with that but i found the problem in Vita that was causing lots of problems in my application.

If i delete related rows, like an invoice and i delete a row the sql triggers do not get fired, it only works reliabley on the insert, on the delete or change rows sometins it works and sometimes it does not, not reliable.

I have to, in case of a delete, execute a nonquery or in vita or usind dapper before the session.savechanges to garante that it is deleted.


with updates i also have noticed problems, for example (no truggers in this tables) i change the quantity of a line by one and it works but sometimes when i load the invoice again, the values do not mach, so in this case i save the new quantity to the new value, then save changes, i do not know if vita changed the valu or not but it was already saves with dapper, so it is not reliable, looks thar the values are not marked for the update. in version 1.9 when it worked with stored procedures it was 100% reliable but after that i do trust it that much.

I still love working with Vita but some of the new changes did not make it better.
Sorry for that, but i am a bit frustrated because i am working for more than 2 weeks and the problems where not in my code.

Thanks.

**Comment by rivantsov** [comment]
Hi
I feel like deja vue, we've been there before, you were complaining things were not updating, and then finally found out that the cause was triggers in database; and you said when you disabled triggers, Vita worked perfectly OK. And you said you are removing all triggers. That was probably a year ago. 
Now what - triggers are back?! Why?!
Triggers are really bad thing in databases, it is a horrible antipattern. Triggers used to be popular in early 2000s, but later for at least 15 years they are considered a very bad thing and general advice is to stay away from them. Triggers are really horrible solution for any problem. Vita or any decent ORM, with proper careful coding can solve all problems that triggers suppose to solve. 
 (And by the way, if Vita updates something and trigger does not trigger - this is not Vita's problem, this is db problem!)   

I do not understand at all your scenario with updates, you describe in paragraph starting with 'with updates I also...'. What value, where, in which entities?!

So, step 1, get rid of triggers, completely. Get rid of dapper. Let's start with Vita-only solution.  
Next, enable SQL log, see unit test projects, assign LogPath variable at start. Open the log file in Notepad++ - it will signal you each time file is updated, so after you run thru operation, always check the SQL log. 
Now, in the future, don't say 'I updated value, called SaveChanges, and it was not updated'. Check the SQL log, and then say: 'I changed the value, called SaveChanges, and there were no UPDATE statement for this value in the SQL log'. That is a valid case to investigate in VITA!!! In case if there was an UPDATE, but the value in DB did not change - then something else is happening OUTSIDE Vita, maybe one of your triggers or something else. 

Let's start investigating, it should work correctly.
Roman
 
PS About trust - believe me, for the last 10 or so years I used Vita in multiple db projects and it never gave me problems like 'sometimes it updates, sometimes not'. It's not perfect, it breaks sometimes, but never fails silently, it is reliable. Something you are doing wrong, lets find out what.

**Comment by rivantsov** [comment]
About using entity events instead of triggers - i will write more in details in later post

**Comment by rubenalves** [comment]
Hello,

The triggers are used to calculate sum values on a a diferente table that the one  getting the update, so the data is supposed to get updated, but even is the triggers does not work correctly that value is supposed to be updated in the database. I will try to send you a simple exemple so you can undestad the problema, and i use dapper to be sure that the problema is no vita, but i will change it to executenonquery that does the same this,

Thanks.

Com os melhores cumprimentos,

Ruben Alves
Móvel: 916887379
Chamada para a rede móvel nacional.
Email: ***@***.******@***.***>

***@***.***


De: Roman Ivantsov ***@***.***>
Enviada: 26 de outubro de 2023 05:02
Para: rivantsov/vita ***@***.***>
Cc: rubenalves ***@***.***>; Author ***@***.***>
Assunto: Re: [rivantsov/vita] Operation Triggers (Issue #229)


Hi
I feel like deja vue, we've been there before, you were complaining things were not updating, and then finally found out that the cause was triggers in database; and you said when you disabled triggers, Vita worked perfectly OK. And you said you are removing all triggers. That was probably a year ago.
Now what - triggers are back?! Why?!
Triggers are really bad thing in databases, it is a horrible antipattern. Triggers used to be popular in early 2000s, but later for at least 15 years they are considered a very bad thing and general advice is to stay away from them. Triggers are really horrible solution for any problem. Vita or any decent ORM, with proper careful coding can solve all problems that triggers suppose to solve.
(And by the way, if Vita updates something and trigger does not trigger - this is not Vita's problem, this is db problem!)

I do not understand at all your scenario with updates, you describe in paragraph starting with 'with updates I also...'. What value, where, in which entities?!

So, step 1, get rid of triggers, completely. Get rid of dapper. Let's start with Vita-only solution.
Next, enable SQL log, see unit test projects, assign LogPath variable at start. Open the log file in Notepad++ - it will signal you each time file is updated, so after you run thru operation, always check the SQL log.
Now, in the future, don't say 'I updated value, called SaveChanges, and it was not updated'. Check the SQL log, and then say: 'I changed the value, called SaveChanges, and there were no UPDATE statement for this value in the SQL log'. That is a valid case to investigate in VITA!!! In case if there was an UPDATE, but the value in DB did not change - then something else is happening OUTSIDE Vita, maybe one of your triggers or something else.

Let's start investigating, it should work correctly.
Roman

PS About trust - believe me, for the last 10 or so years I used Vita in multiple db projects and it never gave me problems like 'sometimes it updates, sometimes not'. It's not perfect, it breaks sometimes, but never fails silently, it is reliable. Something you are doing wrong, lets find out what.

**Comment by rubenalves** [comment]
Hello,

Here is a example of the triggers i use

CREATE TRIGGER RemoveAcumCta on LancamentosSNC
AFTER DELETE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ContaID AS NVARCHAR(60)
    DECLARE @Mes AS INT
    DECLARE @Ano AS INT
    DECLARE @CcID AS INT
    DECLARE @Tipo AS INT
    DECLARE @Valor AS DECIMAL(18, 5)

    SELECT @ContaID = ContaSNC_Conta,
           @Mes = DATEPART(MONTH, DataRegisto),
           @Ano = DATEPART(YEAR, DataRegisto),
           @Tipo = TipoLancamento,
           @CcID = CentroCusto_ID,
           @Valor = Valor
    FROM deleted

    DECLARE @SqlStatement AS NVARCHAR(MAX);

    SET @SqlStatement = 'UPDATE AcumuladosContas SET ';

    IF @Tipo = 0
        SET @SqlStatement = @SqlStatement + 'Debito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' = Debito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' - ' + CAST(@Valor AS NVARCHAR);
    ELSE
        SET @SqlStatement = @SqlStatement + 'Credito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' = Credito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' - ' + CAST(@Valor AS NVARCHAR);

    SET @SqlStatement = @SqlStatement + ' WHERE ContaSNC_Conta = @ContaID AND Ano = @Ano AND CentroCusto_ID = @CcID';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @SqlStatement, N'@ContaID NVARCHAR(60), @Ano INT, @CcID INT', @ContaID, @Ano, @CcID;

    SET NOCOUNT OFF;
END

now the insert trigger

CREATE TRIGGER AddAcumCta on LancamentosSNC
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ContaID AS NVARCHAR(60)
    DECLARE @Mes AS INT
    DECLARE @Ano AS INT
    DECLARE @CcID AS INT
    DECLARE @Tipo AS INT
    DECLARE @Valor AS DECIMAL(18, 5)

    SELECT @ContaID = ContaSNC_Conta,
           @Mes = DATEPART(MONTH, DataRegisto),
           @Ano = DATEPART(YEAR, DataRegisto),
           @Tipo = TipoLancamento,
           @CcID = CentroCusto_ID,
           @Valor = Valor
    FROM inserted

    DECLARE @SqlStatement AS NVARCHAR(MAX);

    -- Construct the dynamic SQL statement
    SET @SqlStatement = 'UPDATE AcumuladosContas SET ';

    IF @Tipo = 0
        SET @SqlStatement = @SqlStatement + 'Debito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' = Debito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' + ' + CAST(@Valor AS NVARCHAR);
    ELSE
        SET @SqlStatement = @SqlStatement + 'Credito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' = Credito' + RIGHT('00' + CAST(@Mes AS NVARCHAR), 2) + ' + ' + CAST(@Valor AS NVARCHAR);

    SET @SqlStatement = @SqlStatement + ' WHERE ContaSNC_Conta = @ContaID AND Ano = @Ano AND CentroCusto_ID = @CcID';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @SqlStatement, N'@ContaID NVARCHAR(60), @Ano INT, @CcID INT', @ContaID, @Ano, @CcID;

    SET NOCOUNT OFF;
END

**Comment by rivantsov** [comment]
OMG, OMG.. that looks terrifying! can't believe my eyes - you rely on stuff like that in production?! As impressive as it looks from your SQL skills point of view, from any other point of view it is absolutely terrible. No one, ever, should do stuff like that and use triggers at all. The main principle is that this code is too brittle, and is in a way too risky place (SQL trigger) to be relied upon. And what happens if exception is thrown? what happens with concurrent invocations trying to access the same 'total' field?! how is concurrency solved? what about reading old/new value just updated by another trigger call in the same transaction?

So, lets remove this crap and replace it with code on Vita's side. Send me the entities definitions for these tables and description what should be dynamically updated (totals, etc)

**Comment by rubenalves** [comment]
I have found 2 new solutions, one using Vita and one using calculated columns and sql functions, i am truing them to see what is better, no triggers for sure now. Let you know what i acomplished, just 2 more hours.

Thanks for you time.

**Comment by rubenalves** [comment]
One of my solutions infolves calculated fields that call functions in sql, it works ok but if i try to get a list of liques 2000 products it takes more than 2 minutes to show the results, not a option, lets do to plan B.

I thot what materialized views world me a good option also bur they are calculated every time i read the records.

**Comment by rivantsov** [comment]
ha ha, oh man, you really hoped that would work?! 
so lets go for real solution, pretty sure it's not that complicated. If you need any help, send me entity definitions and outline / description of what totals you want to maintain

**Comment by rubenalves** [comment]
Hello,

I have a working solution 100% Vita

I have this method before i SaveChanges

public static void ProcessarAcumulados(this IDocumento documento)
{
    foreach (ILinhaDocumento linha in documento.Linhas.ToList())
    {
        if (EntityHelper.GetRecord(linha).Status == EntityStatus.New)
        {
            linha.AddAcumArtigo();
        }

        if (EntityHelper.GetRecord(linha).Status == EntityStatus.Deleting)
        {
            linha.RemoveAcumArtigo(false);
        }

        if (EntityHelper.GetRecord(linha).Status == EntityStatus.Modified)
        {
            linha.RemoveAcumArtigo(true);
            linha.AddAcumArtigo();
        }
    }

    foreach (ILancamentoSNC lanc in documento.LancamentosSNC.ToList())
    {
        if (EntityHelper.GetRecord(lanc).Status == EntityStatus.New)
        {
            lanc.AddAcumConta();
        }

        if (EntityHelper.GetRecord(lanc).Status == EntityStatus.Deleting)
        {
            lanc.RemoveAcumConta(false);
        }

        if (EntityHelper.GetRecord(lanc).Status == EntityStatus.Modified)
        {
            lanc.RemoveAcumConta(true);
            lanc.AddAcumConta();
        }
    }
}

Then i just do so,eting like this if the record is modified

public static void RemoveAcumArtigo(this ILinhaDocumento linha, bool modificado)
{
    IAcumuladosArtigo acum = EntityHelper.GetSession(linha).EntitySet<IAcumuladosArtigo>().FirstOrDefault(c =>
        c.Artigo == linha.Artigo && c.Armazem == linha.Armazem && c.Ano == linha.DataRegisto.Year);
    if (acum == null) { return; }

    decimal quantidade;
    decimal valor;

    if (modificado)
    {
        object[] valoresOrigem = EntityHelper.GetRecord(linha).ValuesOriginal;
        quantidade = Convert.ToDecimal(valoresOrigem[10]);
        valor = Convert.ToDecimal(valoresOrigem[47]);
    }
    else
    {
        quantidade = linha.Quantidade;
        valor = linha.TotalBrutoSemIva;
    }


    switch (linha.TipoMovimentoStock)
    {
        case TipoMovimentoStock.Entrada:
            switch (linha.DataRegisto.Month)
            {
                case 1:
                    acum.QtdEnt01 -= quantidade;
                    acum.ValorEnt01 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp01 -= quantidade;
                        acum.ValorComp01 -= valor;
                    }
                    break;
                case 2:
                    acum.QtdEnt02 -= quantidade;
                    acum.ValorEnt02 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp02 -= quantidade;
                        acum.ValorComp02 -= valor;
                    }
                    break;
                case 3:
                    acum.QtdEnt03 -= quantidade;
                    acum.ValorEnt03 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp03 -= quantidade;
                        acum.ValorComp03 -= valor;
                    }
                    break;
                case 4:
                    acum.QtdEnt04 -= quantidade;
                    acum.ValorEnt04 += valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp04 -= quantidade;
                        acum.ValorComp04 -= valor;
                    }
                    break;
                case 5:
                    acum.QtdEnt05 -= quantidade;
                    acum.ValorEnt05 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp05 -= quantidade;
                        acum.ValorComp05 -= valor;
                    }
                    break;
                case 6:
                    acum.QtdEnt06 -= quantidade;
                    acum.ValorEnt06 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp06 -= quantidade;
                        acum.ValorComp06 -= valor;
                    }
                    break;
                case 7:
                    acum.QtdEnt07 -= quantidade;
                    acum.ValorEnt07 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp07 -= quantidade;
                        acum.ValorComp07 -= valor;
                    }
                    break;
                case 8:
                    acum.QtdEnt08 -= quantidade;
                    acum.ValorEnt08 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp08 -= quantidade;
                        acum.ValorComp08 -= valor;
                    }
                    break;
                case 9:
                    acum.QtdEnt09 -= quantidade;
                    acum.ValorEnt09 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp09 -= quantidade;
                        acum.ValorComp09 -= valor;
                    }
                    break;
                case 10:
                    acum.QtdEnt10 -= quantidade;
                    acum.ValorEnt10 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp10 -= quantidade;
                        acum.ValorComp10 -= valor;
                    }
                    break;
                case 11:
                    acum.QtdEnt11 -= quantidade;
                    acum.ValorEnt11 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp11 -= quantidade;
                        acum.ValorComp11 -= valor;
                    }
                    break;
                case 12:
                    acum.QtdEnt12 -= quantidade;
                    acum.ValorEnt12 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Compras)
                    {
                        acum.QtdComp12 -= quantidade;
                        acum.ValorComp12 -= valor;
                    }
                    break;
            }

            break;
        case TipoMovimentoStock.Saida:
            switch (linha.DataRegisto.Month)
            {
                case 1:
                    acum.QtdSai01 -= quantidade;
                    acum.ValorSai01 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend01 -= quantidade;
                        acum.ValorVend01 -= valor;
                    }
                    break;
                case 2:
                    acum.QtdSai02 += quantidade;
                    acum.ValorSai02 += valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend02 -= quantidade;
                        acum.ValorVend02 -= valor;
                    }
                    break;
                case 3:
                    acum.QtdSai03 -= quantidade;
                    acum.ValorSai03 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend03 -= quantidade;
                        acum.ValorVend03 -= valor;
                    }
                    break;
                case 4:
                    acum.QtdSai04 -= quantidade;
                    acum.ValorSai04 -= linha.TotalBrutoSemIva;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend04 -= quantidade;
                        acum.ValorVend04 -= valor;
                    }
                    break;
                case 5:
                    acum.QtdSai05 -= quantidade;
                    acum.ValorSai05 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend05 -= quantidade;
                        acum.ValorVend05 -= valor;
                    }
                    break;
                case 6:
                    acum.QtdSai06 -= quantidade;
                    acum.ValorSai06 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend06 -= quantidade;
                        acum.ValorVend06 -= valor;
                    }
                    break;
                case 7:
                    acum.QtdSai07 -= quantidade;
                    acum.ValorSai07 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend07 -= quantidade;
                        acum.ValorVend07 -= valor;
                    }
                    break;
                case 8:
                    acum.QtdSai08 -= quantidade;
                    acum.ValorSai08 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend08 -= quantidade;
                        acum.ValorVend08 -= valor;
                    }
                    break;
                case 9:
                    acum.QtdSai09 -= quantidade;
                    acum.ValorSai09 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend09 -= quantidade;
                        acum.ValorVend09 -= valor;
                    }
                    break;
                case 10:
                    acum.QtdSai10 -= quantidade;
                    acum.ValorSai10 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend10 -= quantidade;
                        acum.ValorVend10 -= valor;
                    }
                    break;
                case 11:
                    acum.QtdSai11 -= quantidade;
                    acum.ValorSai11 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend11 -= quantidade;
                        acum.ValorVend11 -= valor;
                    }
                    break;
                case 12:
                    acum.QtdSai12 -= quantidade;
                    acum.ValorSai12 -= valor;
                    if (linha.TipoMovimento == TiposMovimento.Vendas)
                    {
                        acum.QtdVend12 -= quantidade;
                        acum.ValorVend12 -= valor;
                    }
                    break;
            }

            break;
    }
}

Then i use a similar method to insert the new values
on my tests it is working very well

**Comment by rubenalves** [comment]
Is there any way to before the  SaveChanges() does te work?

the way i have it is working ok, but i have to review all my code do that i do not forget to process the changes, if there was a event handler like 

Sesion.SavingChanges += OnSaving(), for example.

**Comment by rivantsov** [comment]
Looks like what you're doing is updating some summary table, with quantity, amount values, with separate columns for each month. This big switch statement is to select proper month. I guess this summary table is for reporting purposes. This looks like a perfect case for using PIVOT, so why don't you define a view over the original orders table, a view with PIVOT operator; here is the case, very similar to yours, see the final answer with SQLs and result grids: 

https://stackoverflow.com/questions/7145694/pivot-with-month

I think this query will be performant enough for reporting, even if you have big table, the user can wait for a few seconds
Try it, or tell me why this won't work for you
Roman

**Comment by rivantsov** [comment]
However, if you want to continue with existing design and having this table with per-month totals columns, then your code can be optimized quite a bit. 
You can get rid of this switch cases that select the property by month. There are these extension methods: 
 EntityHelper.GetProperty(entity, propName) and EntityHelper.SetProperty(entity, propName, value)

that get/set prop by name. So you can form the column name from month: 
var propName = "quantVend" + month.ToString("00"); //not sure, lookup how to format 2 digit month
and then use it to get/set the value in entity property

As for 'event' like 'session.SavingChanges', there is an event on EntityApp: 
app.AppEvents.SavingChanges += (your method)
you hook it at startup; then you can inspect entitySesssion.RecordsChanged, find if there are the entities there that need to do this processing, and launch your algorithm

**Comment by rubenalves** [comment]
This looks much cleaner

 if (lanc.TipoLancamento == TipoLancamento.Debito)
 {
     string nomeCol = "Debito" + lanc.DataRegisto.Month.ToString("00");
     decimal varOrigem = Convert.ToDecimal(EntityHelper.GetProperty(acum, nomeCol));
     decimal valnovo = varOrigem + lanc.Valor;
     EntityHelper.SetProperty(acum,nomeCol,valnovo);
 }

 if (lanc.TipoLancamento == TipoLancamento.Credito)
 {
     string nomeCol = "Credito" + lanc.DataRegisto.Month.ToString("00");
     decimal varOrigem = Convert.ToDecimal(EntityHelper.GetProperty(acum, nomeCol));
     decimal valnovo = varOrigem + lanc.Valor;
     EntityHelper.SetProperty(acum, nomeCol, valnovo);
 }

as the SQL log i will look at it, but it never gets more than 4 or 5 workstations at the same time.

I will take a look at the saving changes, do i have to hook every time i create a session?, probaly yes.

thank you very much

**Comment by rivantsov** [comment]
about hooking event - no, this is 'global' event, you hook once at app startup

**Comment by rivantsov** [comment]
GetProperty has overload with Type parameter so you can retrieve decimal directly: 

EntityHelper.GetProperty<Decimal>(ent, propName)

**Comment by rubenalves** [comment]
Hello,

Hpw can i get the the records from the event?

with this i can see it in the debugger but waht is the correct way?

get of type ILancamentoSNC for example?

thanks.

**Comment by rivantsov** [comment]
```c#
    private void AppEvents_SavingChanges(object sender, EntitySessionEventArgs e) {
      var session = (EntitySession) e.Session;
      var lancamentos = session.RecordsChanged
        .Where(rec => rec.EntityInfo.EntityType == typeof(ILancamentoSNC)).ToList(); 
      // do your processing
    }


```

**Comment by rubenalves** [comment]
I think that i got it working 99%, will do some more testes but it is a very clean fast.

Thanks for your time, THANK YOU !!!.

**Comment by rivantsov** [comment]
you are welcome! Cool, and no more triggers please, ever!
And don't forget to check SQL logs while you test

**Comment by rubenalves** [comment]
I have no triggers now, and the problem with some columns not updating remains, in testes it seems to work 99% of the times, in production it is giving lots of problems, i will try to update the columns using executenonquery to see if it goes better.

**Comment by rivantsov** [comment]
it means you have something fundamentally (algorithmically) wrong. Let's start going thru code again, send me entity definitions and the code that updates the totals. If you prefer, we can continue directly thru email, send to rivantsov at gmail

**Comment by rubenalves** [comment]
Hello,

If i use one of this methods does it force Vita to write the new value?

 EntityHelper.SetProperty(linha, nameof(linha.Preco), preco);
 
EntityHelper.MarkAllColumnsChanged(linha);

Thanks.

**Comment by rivantsov** [comment]
should be; just check with Sql logs - that's ultimate check

**Comment by rubenalves** [comment]
This is resolved, can be closed it is working very well now.

**Comment by rivantsov** [comment]
Hi again, I reopening, to share some info.
I ran into a case that might be related to your problem, that summaries on parent rec (sum of child records amounts) - sometimes updated, but sometimes not. That happened to me, so here's what I found. I remember you reported this issue, maybe on another thread before, and also that aggregate query with 'Select Sum(child.Amount)....From ... Group by ' was returning NULL instead of 0 as total when there's no child records. 

But, what happened to me is this. I have the same arrangement, a parent with Total column, and related child records with Amount column. Whenever child is added, removed or edited, I need to update the total on its parent. So I created an update linq-based command (session.ExecuteUpdate<TEnt>(query)). It looked like it worked correctly - until it didn't. What I discovered is that it does not work when you remove the last child. Child list is now empty, so Total should be updated to 0, right? But it did not happen. The reason is that the underlying query on child table with GroupBy(parentId) and Sum(Amount) - this query did not return ANY records, when there are no child records! So Update statement does not update anything, and parent.Total remains unchanged, non-zero. 

It took me a while to figure it out; note it is not Vita bug, it is actually expected behavior, but wrong assumptions about db behavior in this case. So I finally came up with the following fix/workaround.  
I run two update queries: the second query is the same, calculating totals, no change. But before that, I run an update query that sets the total to 0. So if there are child records, then this 0 will be immediately overwritten by the second query with real total. If there are no child records, then the second query would do no update because of the 'problem' described, and the Total will remain zero. 

I hope it helps, just in case
Roman

**Comment by rubenalves** [comment]
Hello,

I think i found a bug in 
App.AppEvents.SavedChanges event.

iam using the registo.StatusBeforeSave and the status is Modified, Deling or New, that is expected, but if i create a new Session and reload the objects it is more logical to be loaded and not cause the related objects where only loaded in thar session and not changed nor modified.

I am using SavedChanges and not because i need to do the assync and the do not have to wait thor the operation to do calculations.

Do not kow if i was clear with that.

My solution is working perfectly but this way it does unessesary calculations that some times can take like 3 to 4 seconds, and you know people alway complaining it is getting slower :)

Any new things comming to Vita ?

Thanks.

**Comment by rivantsov** [comment]
Hi, 
sorry, I did not understand what's the bug and what's going right or wrong with this SavedChanges event; can you pls provide a step by step scenario, with 'expected' vs actual mismatches that indicate a problem/bug?
thx

**Comment by rubenalves** [comment]
It was something was doing wrong, it is working as expected, Sory.
