### ISSUE TITLE
Multiple NewEntity and MSSql identity

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#23]
MSSql, table with identity primary key.
If I'm calling session.NewEntity in a loop, and session.SaveChanges() after the loop, the identity values will not follow the entity creation order. If I want preserve the entity creation order in the identity, I have to call SaveChanges inside the loop.

**Comment by rivantsov** [comment]
so... ?? is it a complaint about bad behavior, or just an observation? How else you would expect it to work? Without VITA, you'd have to call insert directly each time you create new record with identity. VITA allows you to optimize, by submitting all at once and recovering identities afterwards. Don't see how it can be done better. Preserving initial order of creation?... it might be done probably, but would require some extra not so trivial code at SaveChanges I guess. Is it that critical?

**Comment by sapatag** [comment]
It's not critical. Just an observation about an unexpected behaviour. No complaints:)
