### ISSUE TITLE
Version 3.7 is pushed

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#232]
Updated dependencies to latest (db providers packages); also upgraded to latest Arrest and NGraphQL packages. 
Some refactoring to 'latest' style of AspNetCore setup and similar improvements. 
One new feature - option to prevent creation of Db foreign key on Entity-ref property. Just add attribute [EntityRef(HasDbForeignKey=false)].

**Comment by rubenalves** [comment]
Hello,

There is something stange in this version, my code compliles but in visual studio i get lots of erros in the error list, ex, 
- The name 'EntityHelper' does not exist in the current context
- Canot resolve Symbol 'EntitySet'
- Canot resolve symbol 'SaveChanges'
etc..

if i change it to 3.6 it works with no errors in the error list.

do you know what can cause this?

Thanks.

**Comment by rivantsov** [comment]
hmm.. if you say it compiles, then these errors might be from Intellisense parser. For some reason sometimes it breaks and fails to refresh the references. I have seen this too; my quick fix was to change the selection in combo box above error list from "Build + Intellisense" to "Build"; eventually the problem goes away. 

 Try doing 'Solution Clean' (r-click on Solution top node, select Clean), then Rebuild.
If this does not help, exit VS, then delete all bin and obj folders inside projects, restart, rebuild.

**Comment by rubenalves** [comment]
I removed the obj folders and it is working. 
Thanks for the solution.
