### ISSUE TITLE
Check property is modified

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#234]
Hi @rivantsov ,

Is there a way to check if a property is modified?
I use the following code in a on saving event and it is working fine.
However, the same approach doesn't seems to work for entity reference property.
```
var redeemOnMember = record.EntityInfo.GetMember(nameof(voucher.RedeemedOn));
var oldRedeemedOn = record.ValuesOriginal[redeemOnMember.ValueIndex];
MyApp.AbortIf(oldRedeemedOn != DBNull.Value, "Modify is not allowed for an archived voucher.");

```

**Comment by rivantsov** [comment]
You should check rec.ValuesModified, if it is not null - it means the property was modified
do not check for DbNull.Value
It should work for ref properties as well

**Comment by jasonlaw** [comment]
Thanks 🙏
