### ISSUE TITLE
Anybody using QueryFilter ? 

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#235]
Question to everybody - does anybody use QueryFilters? (see TestLinqQueryFilters test); specifically the variation with getting value from OperationContext, like "BookCat" value in the test. I am looking at revising it, maybe cutting off. Seems like too much complexity added with little effect.
If you use it for multi-tenant functionality, then it will be replaced with new Multi-tenant functionality I am designing. 
Please let me know. 
thanks

**Comment by jasonlaw** [comment]
No, not using it. Thanks.

**Comment by rubenalves** [comment]
I do not use it also.
