### ISSUE TITLE
Just a question on linq and datetime comparison

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#24]
What is the rigth way to do this:
Session.EntitySet<ISOMETHING>().Where(x => x.STARTDATE > new DateTime(2017,1,1));
It gives me a Vita.Entities.DataAccessException with the info
"Conversion failed when converting character string to smalldatetime data type."
STARTDATE is DateTime?

**Comment by rivantsov** [comment]
I assume we are talking about SQLite db? For MS SQL it should be working, I remember there's unit test for this case, not sure how it works for SQLite

**Comment by rivantsov** [comment]
one thing to try - assign datetime const to local variable and use this var in query
I will look into this, but I need some more info

**Comment by sapatag** [comment]
It's MSSQL (sorry) and wortk with local variable, thanks!

**Comment by rivantsov** [comment]
hmmm... what's the type of x.StartDate - is it datetime2? or some MS SQL-specific types like smalldate or whatever they have there?

**Comment by rivantsov** [comment]
another thing, pls let me see the generated SQL. ex.ToLogString() should have printout of the SQL (translated from LINQ), it's interesting to see the SQL and why it failed
Or session.LastCommand.CommandText should have the SQL

**Comment by sapatag** [comment]
StartDate is smalldatetime, and the critical part of the SQL is:
WHERE ("STARTDATE" > ('2016-01-01T00:00:00.00000'))

**Comment by rivantsov** [comment]
ok, it looks like the LINQ engine converts date constant to 'standard' presentation of datetime (as single-quoted string), but MS SQL fails to convert it to small date time for comparison with small datetime in the column. Interesting case, will look at this, how to fix cases like these. thanks!

**Comment by sapatag** [comment]
Another question: Is there a way to do something like this:
Session.EntitySet<ISomeEntity>("select * from....")
for a realy complex where in the select?

**Comment by rivantsov** [comment]
you can use DirectDbConnector, see DirectDbTests.cs in Extended project. That gives you access to raw ADO.NET connection. You can't directly instantiate results of query as list of entities; one way to go - retrieve list of IDs from direct SQL query, and then use Vita's LINQ query with 
().Where(ent => idList.Contains(ent.Id).ToList()
