### ISSUE TITLE
Database Triggers

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#25]
Do you have any plans to create database triggers directly in code or linq?

Regards.

**Comment by rivantsov** [comment]
not in the plans. Triggers are out of favor today, considered bad practice, and I personally agree. In Vita, you can hook to entity Saved event, and attach code - it will be equivalent of a db trigger.

**Comment by rubenalves** [comment]
Yes, i agree, but in case of the database be shared on multiple applications it is a real problem.

Regards.

Ruben Alves
NewSofter, Lda - Departamento de Suporte / Programação
Móvel: 916887379 / Empresa: 295 628 832 / Fax: 295 628 833
Viper: 916887379 / Skype: ruben.ml.alves / Facebook: www.facebook.com/ruben.serreta<http://www.facebook.com/ruben.serreta>
Email: ruben.alves@serreta.net<mailto:ruben.alves@serreta.net> / Email: ruben.alves@newsofter.pt<mailto:ruben.alves@newsofter.pt>
Site Pessoal: www.serreta.net<http://www.serreta.net> / Site Empresa: www.newsofter.pt<http://www.newsofter.pt>

De: Roman Ivantsov [mailto:notifications@github.com]
Enviada: 7 de março de 2017 17:10
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Database Triggers (#25)


not in the plans. Triggers are out of favor today, considered bad practice, and I personally agree. In Vita, you can hook to entity Saved event, and attach code - it will be equivalent of a db trigger.
