### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#26]
I have successfully used Vita converting data from some ugly old databases. Sometimes I had to do workarounds, but Vita was a great help. I have two questions about naming the entity properties. 
1. Vita removes the underscores from table and field names. Can I switch it off?
2. A table named B_DESEMENY has two "master" tables B_DJOGVISZ and B_DBESOROL Vita declares the following properties:
IBDJOGVISZ DE { get; set; }
IBDBESOROL DERef { get; set; }
From where come the names DE and DERef? Is there a way to give them a better name?

Thanks!

**Comment by rivantsov** [comment]
this is about dbfirst generator, right? for #1 - not sure, but most likely not; #2 - names come from FK column names most likely. DbFirst generator (inside vdbtool) is quite simple program, look at sources, you can modify it easily to your liking.
