### ISSUE TITLE
Nuget Npgsql Version

### ISSUE THREAD

**Issue by cloudhunter89** [rivantsov/vita#28]
The readme for the Vita.Data.Postgres NuGet says that it explicitly targets Npgsql version 2.1.3 because of performance issues with some newer versions.  However try to run with the NuGet dll, I get a run-time "File Not Found" exception looking for Npgsql 2.2.5

**Comment by rivantsov** [comment]
sorry, my bad, pls disregard this note in readme. It used to be the case, the newer version did not work; then they fixed it and I upgraded to newer version (2.2.5 currently), but forgot to remove this note. Will fix it in next push.

**Comment by cloudhunter89** [comment]
There is also a dependency for the package on Npgsql = 2.1.3

**Comment by rivantsov** [comment]
Ok, duly noted, will fix it

**Comment by rivantsov** [comment]
should be fixed (package dependencies)
