### ISSUE TITLE
Vita wants to create primary key on MS SqlServer views

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#29]
I have an existing MS SqlServer db, with tables and several views on them. Vita wants to create primary key on the views with an alter table, but it's not possible.

**Comment by rivantsov** [comment]
Strange... check your view definition interface - do you have PrimaryKey defined on them?

**Comment by sapatag** [comment]
You are right, thanks!

**Comment by rivantsov** [comment]
right about what? you had PK on view entities?

**Comment by sapatag** [comment]
Yes, but without PK Vita fails to build the modell.
This is the table entity:
[Entity(TableName = "B_EMBER")]
public interface IBEMBER
{
    [Column("DATSZ"), PrimaryKey(IsClustered = true)]
    int DATSZ { get; set; }
...
and the view:

[Entity(TableName ="B_DOLGOZO")]
public interface IBDOLGOZO
{
    [Column("DATSZ"), PrimaryKey(IsClustered = true)]
    int DATSZ { get; set; }
...

**Comment by rivantsov** [comment]
Ah.... Without PKs it fails? what's the error?
My guess - you are trying also to define an index on the view, and it means it should be a materialized view. For materialized view you should define UniqueClusteredIndex, not PrimaryKey. See IBookSales view in bookStore sample. You should specify Materialized flag when you define view: 
      RegisterView<IBookSales>(bookSalesQuery, DbViewOptions.Materialized);
