### ISSUE TITLE
Several Errors ifound vita using SQL Lite

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#31]
Hi,
1º
if i use ToUpper in link if fails with the error no such function: UCASE
i was using 
if (!session.EntitySet<IUnidade>().Any(c => c.ID.ToUpper() == "DZ"))

2º
I am having problems with encrypted data in sql lite
licencaAplicacao.Contribuinte = EntityHelper.GetSession(licencaAplicacao)
                    .NewOrUpdate(licencaAplicacao.Contribuinte, contribuinte, "TsChannel");
The NewOrUpdate is giving foreignh key errors.

Regards.

**Comment by rubenalves** [comment]
If i save changes after every encryped property it does not give error.
The save sanges dows not change the default guid before saving to the database

**Comment by rubenalves** [comment]
If i use DateTime.Date with sql lite it throws

Regards.

**Comment by rivantsov** [comment]
for problem #1 - you should use ForceIgnoreCase option instead: 
session.EntitySet<TEntity>().WithOptions(QueryOptions.ForceIgnoreCase).Where (c => c.Id == "DZ").ToList(); 
In general, remember that not all LINQ is translatable, especially when it uses functions like string.ToUpper. This applies to #3 - DateTime.Date - SQlite does not know about this property - it is implemented in c# but not in SQLite

For #2 - look at the details of exc, it should say which table/column relation is violated. Is it licencaAplicacao.Contribuente? or something else?

**Comment by rubenalves** [comment]
In #2 if i save changes after every property it works, if not all the new Guid are set to the defaults and five a foreign key constrain error.

licencaAplicacao.Contribuente
licencaAplicacao.Nome
licencaAplicacao.Morada

**Comment by rivantsov** [comment]
DateTime.Date - can you pls give a code snippet how you use it?

**Comment by rubenalves** [comment]
I gave up un that, it was to complex to move all the code i hade using sqlserver to sqllite, i do not have any code left of that.

De: Roman Ivantsov [mailto:notifications@github.com]
Enviada: 20 de julho de 2017 16:24
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Several Errors ifound vita using SQL Lite (#31)


DateTime.Date - can you pls give a code snippet how you use it?

**Comment by rivantsov** [comment]
no longer relevant.
