### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#32]
Hi Roman!

One customer reported problem with using using part of our software on his computer because it has only FIPS compliant cryptographic algorithms allowed on his system.

We found that part of our software uses not FIPS compliant cryptographic algorithms. 
As a result of this we performed investigation to find all occurance non-compliant code. One we found in Vita.Data.Driver SqlSourceHasher class that uses MD5 hash algorithms. Documentation to method "Create" says that  "TargetInvocationException" is thrown when the algorithm is used with Federal Information Processing Standards (FIPS) mode enabled, but is not FIPS compatible.

We are using VITA in the service part of our main software. ( The reported issue is not related to this software yet. We are working on it currently.) 

I would like to ask you whether it is possible to replace MD hash algorithm with one FIPS compliant?

If I could, I would bring your attention to this type of algorithm:
"SHA256CryptoServiceProvider"  that is (should be) FIPS compliant.

Best Regards

Milos Suchy

**Comment by rivantsov** [comment]
I will look at this, need to spend some time investigating; for one thing there's this: 
https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/
MS does not recommend using FIPS (anymore). Still, maybe I can make Vita fips compliant without limiting it. I am sure use of MD5 in Vita is just the case MS mentions as use for non-sensitive data (hash keys)

**Comment by rivantsov** [comment]
switched to this SHA stuff
