### ISSUE TITLE
Lock option with join

### ISSUE THREAD

**Issue by sapatag** [rivantsov/vita#33]
The statement
Session.EntitySet<IBEREDMENY>(LockOptions.NoLock)
                    .Where(x => x.ERBKOD == "GBMB" && x.ERDBAZON > 0)
                    .Select(x => new { Value = x.ERFT, Kth = x.ER.DBSZE })
translates to
exec sp_executesql N'SELECT x$."ERFT" AS "Value", t0$."DBSZE" AS "Kth"
FROM "dbo"."B_EREDMENY" x$ WITH(NOLOCK)
 INNER JOIN "dbo"."B_DBESOROL" t0$ ON t0$."DBAZON" = x$."ERDBAZON"
WHERE ((x$."ERBKOD" = @P0) AND (x$."ERDBAZON" > 0))',N'@P0 nvarchar(4)',@P0=N'GBMB'
in MSSQL.
It would be nice if the NOLOCK would apply to the joined table(s) too.

**Comment by rivantsov** [comment]
you can do it if you use explicit join of 2 tables, easier with c# LINQ SQL-like syntax with 'from x in session.EntitySet<?>.WithOptions(...) join ....'
