### ISSUE TITLE
Feature Request: Options to exclude the use of double quotes when for table and column name (for Code First)

### ISSUE THREAD

**Issue by shgohh** [rivantsov/vita#38]
There are many use of database outside of VITA application, such as reporting which normally consists of handwritten query statement, the use of double quotes caused the table and column name become case sensitive, which make life difficult and time consuming.

The following article describe better the reasons of not using double quotes:
http://blog.lerner.co.il/quoting-postgresql/

**Comment by rivantsov** [comment]
that's a good point, will add it in next version. Thanks!

**Comment by rivantsov** [comment]
question - what happens when table/column name collides with one of reserved words? my main experience is with MS SQL Server, and there are many keywords in TSQL (MS flavor) that cannot be used as column/table names (ex: Id). The solution is to quote everything. Are there reserved words in PG like this; if yes - what they are, and what to do if there's collision?

**Comment by shgohh** [comment]
Yes, you're right that "" or [] can be used in quote reserved words in MSSQL, other database such as Oracle used only "" for the same purpose. However in MSSQL, "" or [] is optional for non-reserved words, when executing DML (select / insert / update / delete), and it's also case insensitive, regardless of the case used when creating the table / column.

Surprise, when doing the same testing in PostgreSQL, i found that if the table / column is double quoted with lower case, then it works just like MSSQL,  "" is optional and both upper lower case can be used - without double quote. However, "" is mandatory when one of the character is in upper case, and the same exact word must be used in DML.

So the question, is VITA creating table (and column) with upper case for PostgreSQL,? if yes, then the only change required is to always use lower case word for table and column name, with double quote (to support reserved words and also table / column name with space).

**Comment by rivantsov** [comment]
VITA is preserving initial case. So I will just add All-to-lower flag; should I make it default ON? probably yes

**Comment by shgohh** [comment]
I think defaulting All-to-lower is the best option for PostgreSQL.

Thanks for the changes.

**Comment by mukhlim** [comment]
pleasae implement this (All-to-lower flag) for postgresql

**Comment by rivantsov** [comment]
will do, thanks for reminding. 
About SalesTotal->sales_total, injecting extra underscore? do you think it's necessary?
Size attribute - what do you mean?

**Comment by mukhlim** [comment]
- about 'SalesTotal->sales_total' i think it much more readable.
- [Size(8000)] is not enough for image field. or I miss something?
  how about something like [Size(Size.MAX)] for blob

**Comment by rivantsov** [comment]
Size(8000) - where did you spot this? 
there's [Unlimited] attribute that specifies unlimited text of binary blob

**Comment by mukhlim** [comment]
oh,,my bad.. tq

**Comment by rivantsov** [comment]
the all-lower option is there (in 2.0 .NET core version, just pushed). There's a AllLowNamingPolicy class (sample but realistic) in BookStore project, and commented out code in Test project setup that add this policy - with it you get all-lower names in Postgres
