### ISSUE TITLE
[Feature Request] Compatibility with .Net Core 2.0

### ISSUE THREAD

**Issue by DavidJPatterson** [rivantsov/vita#39]
Hi there just wondering if you have any plans on making Vita compatible with .Net Core 2.0 for more universal use?

**Comment by rivantsov** [comment]
not only plans - actively working on it. Expect it early next year. 
And Happy New Year!

**Comment by DavidJPatterson** [comment]
Excellent :) Looking forward to the release

**Comment by rubenalves** [comment]
Any news on this? New Version comming soon? :)

Regards.

**Comment by rivantsov** [comment]
Ok, time to re-evaluate where I am (actually buried in new linq engine). Give me a couple of days for a more definite answer, I will try to see if I can push some limited version sooner, with old engine. Big issue is still migrating SlimApi (WebApi) functionality.

**Comment by rivantsov** [comment]
I will push something (preview) within a few days

**Comment by rivantsov** [comment]
sorry guys for the delay, few more days, it's coming!

**Comment by rivantsov** [comment]
ok, next week I'll be on 'vacation', so hope to wrap it up and push whatever i have

**Comment by shgohh** [comment]
How is your holiday? looking forward for new release 💪

**Comment by rivantsov** [comment]
yeah, I know, I know. I am sorry, it always takes longer than it takes. vacation was actually looking for a job, open source does not pay bills. I am all right, continuing. trying to finish up minimal presentable version. thank you for your patience

**Comment by shgohh** [comment]
Sorry to hear that, please take your time, thanks again for great product.

**Comment by rivantsov** [comment]
done!

**Comment by Michaellok1992** [comment]
Hi @rivantsov , Amazing update! 👍 If u are free and convenient, possible you that update the readme.md and wiki if any changes. :)

**Comment by rivantsov** [comment]
thanks, but no time for docs now, will be updated later, need to stabilize the code and recover many old features
