### ISSUE TITLE
'IIF' is not a recognized built-in function name for MsSQL 2008

### ISSUE THREAD

**Issue by adjdred** [rivantsov/vita#4]
Currently using the latest version of VITA for MsSQL 2008 but get the following error

"'IIF' is not a recognized built-in function name."

IIF appears to be available from 2012 onwards (https://msdn.microsoft.com/en-gb/library/hh213574.aspx)

**Comment by rivantsov** [comment]
I don't quite get it - you use it in 2008 mode, but IIF as you say appears only in 2012 - ?
next, is this error occurs when you execute SQL (from MS SQL server), or from VITA linq engine? Pls give me some stack trace and more details
