### ISSUE TITLE
Method syntax retrieve all records from table and only apply filter after all records are retrieved

### ISSUE THREAD

**Issue by shgohh** [rivantsov/vita#40]
The following example use ORMBenchmarksTest from https://github.com/exceptionnotfound/ORMBenchmarksTest

When using query syntax,
```
var players = from x in session.EntitySet<IPlayer>()
              where x.Team.Id == teamID
              select x;

-- where clause was used, parameter name is @P0
SELECT "Id", "FirstName", "LastName", "DateOfBirth", "TeamId"
FROM "dbo"."Player"
WHERE ("TeamId" = @P0)
```

However, when using method syntax,
```
var players = session.GetEntities<IPlayer>().Where(x => x.Team.Id == teamID).ToList();

-- no where clause, all records are retrieve from table
SELECT "Id", "FirstName", "LastName", "DateOfBirth", "TeamId" 
FROM "dbo"."Player";
```

I suppose both query and method syntax should produce the same select statement.

**Comment by rivantsov** [comment]
The problem is that you use GetEntities() in the second case - it retrieves ALL records which are then filtered on the client. Use EntitySet<>.
Happy New Year!

**Comment by shgohh** [comment]
Thanks, sorry for careless mistake.
