### ISSUE TITLE
Could be basis of a GraphQL server?

### ISSUE THREAD

**Issue by charring** [rivantsov/vita#41]
Hi,
I found this project while researching GraphQL. Needed a parser and I've used Irony. I didn't know about VITA until today.  VITA looks like it could be the basis of a GraphQL server. I've frankly not found any good GraphQL servers for SQL Server written in .net.  Just an idea I wanted to share and get feedback on.

**Comment by rivantsov** [comment]
Well, you just read thru my plans. It's nice to find out that somebody else is thinking in the same direction! 
Yes, GraphQL is definitely in the plans, for sure. After building a few REST ful API's, getting tired of it (repeating same thing over and over), seeing all shortcomings, I agree with all the reasoning that GraphQL folks present in favor of new approach. I think GraphQL is the answer, and path to the future. Something like VITA-based GraphQL server is in the plans for the next year. And parsing will be involved, so comes back Irony - I will have to refresh it, put official NET Core version, fix some obvious deficiencies/troubles, and then build GQL parser with VITA as engine. 
But first - moving VITA to .NET Core, actively working on it, planning to push early next year. After that - GraphQL it is!
Happy New Year!

**Comment by charring** [comment]
Hi Roman,
That's excellent to hear! I've done much work in the past on generic proxies to RDBMS schemas so perhaps I can assist. But even before that I might assist with Irony - since I'll be migrating a project that uses Irony to .Net Core 2.X very shortly.  I did find this fork [https://github.com/daxnet/irony] which seems to indicate that not much needed to be changed for a minimal port. But not all of Irony was ported.

**Comment by rivantsov** [comment]
finally started looking at GraphQL, and thinking about implementing with VITA. 
Here is initial project, for now just grammar/parser: 
https://github.com/rivantsov/ngraphql

**Comment by mukhlim** [comment]
please implement this feature

**Comment by rivantsov** [comment]
I will, definitely, working on it. But pls understand - it's a huge challenge
