### ISSUE TITLE
Copy Objects

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#42]
I need to sync data from one database to another, is there a way to copy a object from session1 to session2 ?

Regards.

**Comment by rivantsov** [comment]
there's an attach method (attach entity to another session) somewhere in extensions, search for it, it should do what you want

**Comment by rubenalves** [comment]
Can you point me there with some example?

Thanks

**Comment by rivantsov** [comment]
what you probably need is a method to create a 'new' copy of an entity in a different session. Here is a method: 

`    public static TEntity NewCopyOf<TEntity>(this IEntitySession session, TEntity entity) where TEntity: class {
      var copy = session.NewEntity<TEntity>();
      var entityInfo = EntityHelper.GetRecord(entity).EntityInfo; 
      foreach(var member in entityInfo.Members) {
        switch(member.Kind) {
          case EntityMemberKind.Column:
            var value = EntityHelper.GetProperty(entity, member.MemberName);
            EntityHelper.SetProperty(copy, member.MemberName, value);
            break; 
          // do not copy entity references or lists
        }
      }
      return copy;
    }

then you can just call SaveChanges on the other session: 

var bk= db1session.GetEntity<IBook>(bkId); 
var copy = db2session.NewCopyOf(bk);
.db2session.SaveChanges();

**Comment by rubenalves** [comment]
Cold not get it working with that example, i will try to use Dapper, with Vita i will not get there :(

Regards.

**Comment by rivantsov** [comment]
what's the error - when you try to use this?

**Comment by rubenalves** [comment]
I cant even get it to complile in visual studio, TEntity is not found
EntityMemberKind is not found

**Comment by rivantsov** [comment]
TEntity not found - this is generic arg to static method, how it can be not found?! did you copy it right? other not founds - just add usings. I added this method to EntityHelper, it compiles OK, will be there in next release. (but not tested at runtime)

**Comment by rivantsov** [comment]
sorry, looks like some symbols just disappeared from the listing, trying again: 

```c#
public static TEntity NewCopyOf<TEntity>(this IEntitySession session, TEntity entity) where TEntity: class {
      var copy = session.NewEntity<TEntity>();
      var entityInfo = EntityHelper.GetRecord(entity).EntityInfo; 
      foreach(var member in entityInfo.Members) {
        switch(member.Kind) {
          case EntityMemberKind.Column:
            var value = EntityHelper.GetProperty(entity, member.MemberName);
            EntityHelper.SetProperty(copy, member.MemberName, value);
            break; 
          // do not copy entity references or lists
        }
      }
      return copy;
    }
```

**Comment by rubenalves** [comment]
It is working, thanks.

Regards
