### ISSUE TITLE
Question - How to VITA handle this? 

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#43]
Hi Rivantsov,

I like to seek ur advice. i have a scenario, lets say i have a function of "adding player" and "adding username".

function addPlayer() {
// open session
// add player detail
// save change
}

function addUsername() {
// open session
// add username detail
// save change
}

how will VITA ORM handle situation if i want to call "add username" in "add player", like scenario below?

function addPlayer() {
// open session
// add player detail
// save change

// add username if add player success
// if add username fail, rollback add player
addUsername();
}

Regards,
Michael

**Comment by rivantsov** [comment]
Not quite sure I understood it right, but I guess there's some misunderstanding on your part. Nothing is sent to database until you call session.SaveChanges().  So if you do like 
openSession
addPlayerDetails()
addUserName()
session.SaveChanges() 

- on SaveChanges, the session sends all updates to database in one transaction. If any of updates fail (addPlayerDetail?), then trans is rolled back, so nothing is saved. 
hope this helps; if not, pls provide more details..

**Comment by Michaellok1992** [comment]
Currently i having an project using the basic sql command calling..

```
function AddPlayer() {
  try {
    openSqlConnection();
    executeAddPlayerCommand();
    AddUsername();
    commit();
  } catch(exception) {
    rollback();
  }
}

function AddUsername() {
  try {
    openSqlConnection();
    executeAddUsernameCommand();
    commit();
   } catch(exception) {
    rollback();
   }
}
```

if **_"executeAddUsernameCommand()"_** failed, whatever excuted in **_"executeAddPlayerCommand()"_** will be rollbacked.

im trying to switching above code to VITA. Just not sure how to switch it. Because once VITA on SaveChanges, it considered commit not sure rollback-able or not.

**Comment by rivantsov** [comment]
well, I think with VITA it will work exactly as you want, and as I already described (see above). I assumed that methods addPlayerDetails and addUserName in MY listing are manipulations with entities which are in-memory objects, and not SQLs are executed. It is only when you call SaveChanges, the changes/SQLs for BOTH actions are sent to database, within one single transaction. If anything goes wrong, at any step (player or username) - the error is thrown, the transaction is rolled back, and everything is undone - just as you describe it works for you

**Comment by Michaellok1992** [comment]
```
function AddPlayer() {
var session = DatabaseConfig.App.OpenSession();

            try
            {
                var obj1 = session.NewEntity<IPlayer>();
                obj1.Id = new Guid("20F92CCF-C9FD-423D-AB01-EE66C098E674");
                obj1.ContactNumber = "12341234";
                obj1.CreatedDate = DateTime.UtcNow;
                
                AddUsername();
                session.SaveChanges();
            }
            catch (Exception ex)
            {
                //LOGGING - Error
                session.CancelChanges();
                return false;
            }
            
            return false;
}

function AddUsername() {
            var session = DatabaseConfig.App.OpenSession();
            var obj2 = session.NewEntity<IPlayerUsername>();
            obj2.Id = Guid.NewGuid();
            obj2.CreatedDate = DateTime.UtcNow;
            obj2.GameUsername = "125456";
            obj2.IsActive = true;
            obj2.Player = session.GetEntity<IPlayer>(new Guid("20F92CCF-C9FD-423D-AB01-EE66C098E674"));

            //New Player Detail has not added.
            session.SaveChanges();
}
```

The reason i need to split this 2 function apart because other part of the application reusing the function itself.

**Comment by rivantsov** [comment]
Pass the session as parameter to AddUserName, do not call SaveChanges at the end of AddUserName. If you need function AddUserName without parameters, create another overload, without session parameter, and inside open session, call AddUserName with session as parameter, and then saveChanges
Another thing - do not call CancelChanges in catch block, it does nothing usefull

**Comment by Michaellok1992** [comment]
Thanks for your reply and advice, rivantsov. Very much appreciated. 

Do you have any donation portal? I'm interested to make some contribution.

**Comment by rivantsov** [comment]
Hi, glad I could help. Thanks for your offer, but no need for this. The best contribution I can ask for - start using VITA for your real-world apps, and give feedback and suggestions on what can be added or can be done better. And of course find bugs
Good luck and keep in touch. Have fun!
Roman

**Comment by rivantsov** [comment]
thank you, life is OK, busy busy, dragging along, making progress VITA-.NET core, but no date for release for now
