### ISSUE TITLE
[Question] Full Outer Join

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#44]
Hi rivantsov, 

How are you? Hope u doing well. :)

I have question regarding how to use VITA for full outer join?
Example: https://www.w3schools.com/sql/sql_join_full.asp

Thanks.
Regards,
Michael

**Comment by rivantsov** [comment]
Hi
I don't think it's supported, at least directly, never met a case which required this, and I believe original Linq2Sql did not care about this either.  I think if you have a case like this, you can come up with a custom query(ies) that do the same
