### ISSUE TITLE
.NET Core version is pushed!

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#47]
Major changes (other than switch to .NET core) - 
stored procedures are gone for good, now dynamic SQL only, including basic CRUD operations. SPs have good side - precompiled SQL code, compact and nice batch text - just lines of SP calls with parameters; but there's a downside - fixed set of columns, insert-update-select ALL. In many cases, it does not make sense to load entire entity and update-all while changing just one column. Plus, for SELECTs, with a general trend to GraphQL-like flexible API, when column set selected or updated can differ from call to call, it does not make much sense to go through pre-built stored procedures. 
Switching to dynamic SQLs required some major changes in the way CRUD SQLs  are generated. With batch mode, multiple SQL statements are packed together, in one DB command, with command parameters (one set for batch command) injected into SQLs where necessary across multipe CRUD SQLs. So what was needed is a flexible system of generating CRUD SQLs while injecting literals or parameters from 'global' list. 
The other concern with SQL generation is multiple concatenations of SQL pieces into statements and then batches - causing a lot of string garbage generated, and pressure on memory and garbage collector. As a result, a new SQL templating system was built from scratch, to allow final merging of many-many string pieces into final batch at the end. That was quite an effort, the whole thing is a bit shaky, needs some cleanup in the future and clarity of basic concepts, but I think overall it is a good foundation for future development. 
All SELECTs are now LINQ-based - CRUD SQL engine generates directly only insert/update/delete SQLs from templates; for SELECTS - it builds LINQ query (as experssion tree) and lets LINQ engine produce the SQL. 
Big thing - packing multiple inserts into one INSERT statement. The batch engine sorts the updates (inserts,deletes) according to ref constraints (topological order), and then merges multiple inserts into the same table into 1 INSERT statement. Deletes are merged too, so multiple deletes from the same table are done with one DELETE statement - using 'where Id in (....)'. Run the unit tests, and have a look at SQL logs in bin folder - aren't some pieces simply beautiful?! Insertion of all secret questions for Login module - just one statement!
The LINQ engine - still old one, I could not complete the new one on time, so it is old one. But... the part with SQL generation and also integration with drivers (customization for providers) - this part is completely rebuilt with new SQL templating engine. That's a big improvement I think, compared to a mess it was before. I will get back to new LINQ engine soon, and hope to finish it and roll it into main code line.
There are multiple things that used to be there, but not ported yet: 
- Query cache (saving generated SQLs)
- Entity (data) cache
- Include queries
- Authorization framework
- All web functionality (Web API integration)
- Out of many modules, only Login module is ported and tests. Logging module (for saving logs in db) - to be ported soon.
 
SQL Compact Edition is gone for good, SQLite is clearly the winner for in-process database. 
Couple of unit tests are failing in console mode. One is SQLite file being locked although all connections have been closed (hopefully?) - any help in investigation would be appreciated. 
Entity classes generation (classes behind interfaces, IL-generated) - handled by Proxemity package; bridge to Proxemity is Vita.Entities.Emit project/dll, included into main Vita package. The reasoning behind is on some platforms IL generation is not available at all (Apple), so there we can go with pre-compile generation classes as c# code - but this requires separation of IL-gen functionality from the main projects. 
Again, sorry for the long wait, as usual - under-estimate how long things will take, should be better going forward, will deliver regular updates and improvements. Download, try, enjoy, feedback is welcome!

**Comment by mukhlim** [comment]
nuget package is broken. latest version of proximity is 1.0.1, required version is 2.0

Attempting to gather dependency information for package 'Vita.Data.Postgres.2.0.0' with respect to project 'myvita', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 38,48 sec
Attempting to resolve dependencies for package 'Vita.Data.Postgres.2.0.0' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'Proxemity' that is compatible with 'Vita 2.0.0 constraint: Proxemity (>= 2.0.0)'.
At line:1 char:2
+  Install-Package Vita.Data.Postgres -Version 2.0.0
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by rivantsov** [comment]
Yeah, sorry, was just rushing to push the fix, discovered it this morning, but could not get to computer until now. The problem - I referenced bogus version of Proxemity (2.0), which was not there. I just upped Proxemity package to 2.0, pushed it, and verified locally - it now installed successfully. 
So please try again and let me know

**Comment by Michaellok1992** [comment]
Hi @rivantsov , Amazing Update! 

Is there anything i need to take note if i upgrading from 1.9.3.1 version to the latest one? 
im still using .net framework 4.6.2

**Comment by rivantsov** [comment]
Michaellok - thanks!
special notes - nothing I can think of. Full fwk is fully compatible with .net standard libraries, I worked with this combination before, you should be OK. Some namespace ref adjustments might be necessary, but otherwise - should be no changes in you logic. 
What's your db server? read readme.txt notes in the driver projects for your server type, might be something there

**Comment by Michaellok1992** [comment]
> Michaellok - thanks!
> special notes - nothing I can think of. Full fwk is fully compatible with .net standard libraries, I worked with this combination before, you should be OK. Some namespace ref adjustments might be necessary, but otherwise - should be no changes in you logic.
> What's your db server? read readme.txt notes in the driver projects for your server type, might be something there

Microsoft SQL Server 2016 (RTM-GDR)
Express Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: )

**Comment by rivantsov** [comment]
nothing special for MS SQL, should work ok, good luck

**Comment by rubenalves** [comment]
It is All Broquen,

Icanot Use :   directSql.ExecuteDbCommand ,
ExecuteDelete ,
[AsIs, NoInsertUpdate, Nullable]
decimal SaldoAnterior { get; set; }

using Vita.Entities.Web;

And probebbly lots of ohter thing, i am a dead person :(

**Comment by rivantsov** [comment]
Web support is not ported yet. For other things - can you pls be more specific?

**Comment by rivantsov** [comment]
don't worry, we'll fix that, just let me know your priorities, what you need first (to be ported)

**Comment by rubenalves** [comment]
No order. I can held one more week without updating, no broblem.

Ruben Alves
________________________________

**Comment by rivantsov** [comment]
honestly, it won't happen in one week, sorry, too much work yet. 
now, guessing what your problems are, from your list. In general, some api's changed, but there's equivalent to old methods. 
ExecuteDbCommand -> ExecuteNonQuery or ExecuteSelect
ExecuteDelete - it is now extension on IEntitySession, so it will be session.ExecuteDelete(delQ);
what's your problem with this decimal property?! By the way, if it is Nullable, it should be of type 'decimal?'. Vita supports straight decimal but this is not 'natural' way, more like hack around

**Comment by mukhlim** [comment]
first, thanks for continuing this project. 
what about postgres colums and table names. is there any option to make it fully lowercase and UNDERSCORED for every uppercase in entity class and property names?
something like 'sales_order_item' instead of 'salesorderitem'. i think DBA will love it

**Comment by rivantsov** [comment]
I answered it on original thread/item:
the all-lower option is there .There's a AllLowNamingPolicy class (sample but realistic) in BookStore project, and commented out code in Test project setup that add this policy - with it you get all-lower names in Postgres

**Comment by rivantsov** [comment]
MS SQL 2008 is not supported anymore, so version specifier not needed, all versions from 2012 up are the same for VITA (for now). So just remove the parameter

**Comment by rubenalves** [comment]
So i have this code:

var driver = new MsSqlDbDriver(MsSqlVersion.V2012);
                DbSettings = new DbSettings(driver, MsSqlDbDriver.DefaultMsSqlDbOptions, connectionString, upgradeMode: DbUpgradeMode.Always);

how can i make it work?

MsSqlDbDriver dis not exist.

**Comment by rivantsov** [comment]
ah, MS SQL driver is now in a separate package, install Vita.Data.MsSql nuget package

**Comment by rubenalves** [comment]
Worked,

Now one more error,

App.GetService<IDataAccessService>().Events.DataSourceStatusChanging += EventsOnDataSourceChange;

Dives a error at Events.DataSource.....

**Comment by rivantsov** [comment]
App.DataSourceEvents.DataSourceChange += ...

**Comment by rubenalves** [comment]
I am getting another error,

LoginResult = loginService.Login(ctx, AppHelper.UserNameLogin, AppHelper.PasswordLogin, Guid.Empty, null, expira);

UserSessionExpirationType was not foud

Regards

**Comment by rivantsov** [comment]
UserSession module is not ported yet; for login - just remove the param

**Comment by rubenalves** [comment]
I have
----------------
var loginService = empresa.Aplicacao.GetService<ILoginService>();
LoginResult = loginService.Login(ctx, AppHelper.UserNameLogin, AppHelper.PasswordLogin);
----------------
It does not compile,
UserSessionExpirationType is the error.

Regards.

**Comment by rivantsov** [comment]
where's expiration type in this code?!

**Comment by rubenalves** [comment]
no

**Comment by Michaellok1992** [comment]
Hi @rivantsov , just asking but not urgent. Are u planning to push your changes to 4th GITHUB release?

**Comment by rivantsov** [comment]
sorry, don't quite understand what you mean? - 4th GH release?

**Comment by rivantsov** [comment]
ah, this... I forgot about this github feature. But do we/you need this? release is a pack of binaries, and is a good distribution model for other  type of apps (non .net). VITA  distributed thru nuget packages, which is a standard for .net apps, and works well (I think/hope). So I am not sure that's needed at all.

**Comment by Michaellok1992** [comment]
Nuget itself it good enough for .net environment / visual studio. Just maybe cater some (rare) case, which need the binary/compiled file. Not a must. just more convenient for some people. 👍

**Comment by rivantsov** [comment]
well, for this case - it is easy. rename vita.nupkg into vita.zip (nuget package is in fact zip file), and unzip it!
