### ISSUE TITLE
Separation of master database

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#49]
Hi,
First of all, thanks for the great framework!
I want to store all my Tenants information in one single database, but the transaction data will be kept in dedicated database per Tenant, is it doable with the framework? Can we have a single query from different database? 
For now, I am actually creating 2 EntityApp, one for master database and one for transaction database, is it the right way to do?
Thanks in advance.
Jason Law

**Comment by rivantsov** [comment]
I think this is the right way to go. For tenant databases, there's a facility when single entity app can be connected to multiple databases. Just call app.ConnectTo multiple times, but each time provide a different DataSourceName. You can add databases at runtime, as you need, not necessarily at startup
To open session for specific tenant, you should create OperationContext first and set its DataSourceName property, and then create session from this context. 
DataSourceName is not database name, it is a free-form string, might be Id of some kind or string code

**Comment by jasonlaw** [comment]
Thanks for the prompt reply!
Yes, I have seen the case you mentioned above in the MultiTenantTest. Just to clarify, for that case, we can only have all Entities to be in one database at time right?

My case is, I have a master User table to keep all users in a UserMaster database, once the user login, all the transactions will be saved into UserTransaction database, however, in the UserTransaction database I try not to replicate the Users table again. In my code, I have UserMaster entities and UserTransaction entities in 2 separate EntityModule, I guess we can't have different DataSourceName  for these EntityModule to be in one single EntityApp right?

Thanks again for your time to answer my question.

**Comment by rivantsov** [comment]
If I understand it right, - no, you cannot mix UserMaster and UserTransaction entities in one entity session. Session is attached to OperationContext which is attached to entityApp. I used to try to allow mix of entities from different dbs in one session, but it was a real mess, so I abandoned it. Like you open session, you load/modify UserMaster entity, then make similar change in UserTrans entity, then call session.SaveChanges and it all saved in corresponding databases - you can't do this. 
You have to joggle two entity apps with separate sets of entities, and separate sessions.

**Comment by jasonlaw** [comment]
Clear now, thank you very much! :)
