### ISSUE TITLE
Mobile app (Xamarin) login flow

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#50]
I am new to mobile app development.
I want to use this great framework in my mobile app project based on xamarin.
My question is, since we don't keep session in server, are we always create/instantiated the EntityApp for each REST service call?

**Comment by jasonlaw** [comment]
Unfortunately, this is a mobile app, and I plan to use REST service. It suppose to be sessionless or stateless right?

**Comment by rivantsov** [comment]
stateless does not mean there are no global singletons on the server. It means there are no objects per user (UserSession) kept alive between requests. But global EntityApp object, one for all users - it's fine. In fact any server app maintains quite a lot of it's one global long-living objects. I think you're a bit confused about this stateless term.

**Comment by jasonlaw** [comment]
You are right, I am confusing myself. :)
It is clear now, thank you very much!
