### ISSUE TITLE
RowVersion broken for SQL Server with v2.0.0?

### ISSUE THREAD

**Issue by gfreeman1** [rivantsov/vita#51]
I am looking at upgrading my project to use Vita v2.0, but it seems like RowVersion / timestamp fields for SQL Server are currently "broken". I have tested this issue in SQL Server Express 2014, SQL Server Express 2017 and SQL Server Express 2017 LocalDB. In all cases, when Vita v2.0 tries to connect to the database after the first initial connection, it throws the following error:

> Vita.Entities.DataAccessException: Cannot alter column 'RowVersion' to be data type timestamp. ---> System.Data.SqlClient.SqlException: Cannot alter column 'RowVersion' to be data type timestamp.

This error is thrown even when there have been no changes to the entities to cause any sort of schema change. Using Vita v1.9.3.1 with the same code and databases, it connects successfully every time.

I have attached a simple test solution that reliably reproduces the error. This connects to a DB named "VitaRowVersionTest" on a LocalDB instance named "(localdb)\MSSQLLocalDB", which can be changed in the "ConnectionInfo.cs" file at the solution's root folder. What this does is to drop all objects belonging to the "vita_info" and "vita_test" schemas, then proceed to try connecting to the database twice in a row. The first time, it will create all necessary objects. The second time, it should connect without doing anything, since none of the entities have been modified. For Vita v1.9.3.1, this works as expected. However, for Vita v2.0.0, the second connection attempt will cause the error above to be thrown.

Am I doing something wrong or is this a side effect of the major changes for this version?

Test solution:
[VitaTest.zip](https://github.com/rivantsov/vita/files/2428997/VitaTest.zip)

**Comment by rivantsov** [comment]
sorry for trouble, sounds like a bug, does not seem like do something wrong, will look at it tonight and push the fix promptly

**Comment by gfreeman1** [comment]
No worries - v1.9.3.1 still works perfectly for us and there is no hard requirement to upgrade it right now.

Let me know if there is any info I can provide to make it easier to debug.
