### ISSUE TITLE
Need advice for a EntityModule design issue

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#52]
Hi Roman, 

Suppose there are several features in my app which each can be an individual module, for eg, Forum discussion module. However, they are may have some shared entity, such as User. In that case, how would you advise for the model design?

Thank you very much!

**Comment by rivantsov** [comment]
just declare IUser in one of the models and register it in this module. Then just reference it (in properties of entities) in other module entities - that will work. Modules can depend on each other, and reference 'foreign' entities
There's even 'requires' facility, when one module requires that there's another one (on which it depends) - that must be also registered in the app model
