### ISSUE TITLE
Filtered relations

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#54]
Is it possible to have filtered relations?
For eg, say we have Orders and OrderDetails table, besides the main master-details relation Order owns OrderDetails, we may want to add another relation (filtered from Order -< OrderDetails relation) based on certain condition/criteria on OrderDetails, for eg, could be some status.

**Comment by rivantsov** [comment]
Not yet. Filtered list properties were supported in v1.9, but not migrated yet. Look at IPublisher property source (in Books sample) - it has FictionBooks property, filtered list of books, currently commented out. I will bring this support back, hopefully soon

**Comment by jasonlaw** [comment]
Thanks for the clarification!

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

May I know what is the progress of bringing this feature back? 
Really appreciate if this feature can be migrated soon.
Thank you very much!

**Comment by rivantsov** [comment]
So on this issue. Not sure it is that needed, you can always create an extension method against parent entity type, and it does the job

**Comment by jasonlaw** [comment]
Hmm....perhaps it could help with the (N+1) problems where we can use the "include" keyword?

**Comment by rivantsov** [comment]
well, good point, but for N+1 problem I plan a bit more advanced facility, we'll see how it goes
