### ISSUE TITLE
Web API with ASP.Net Core

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#55]
May I know how does the SlimApiController work with the ASP.Net Core?
I am based on the following article to host my Web API,
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1

I have no idea how to make our controller (which inherited from SlimApiController) in library to be part of the controller in web project.

Appreciate your help.

**Comment by rivantsov** [comment]
It does not (work with .NET core), SlimApi is there for backward compatibility so far and is not migrated, most likely will be refactored into a separate project. I would advice start working with regular controller following .NET core WebApi guidelines, so just forget about SlimApi for now

**Comment by jasonlaw** [comment]
Clear now, thanks!
