### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#56]
How do we handle the nested transactions?
Suppose in a module we have 2 methods, both also calling OpenSession and SaveChanges, since each method can be called separately.
I have another method that will call these 2 methods, how do I ensure both methods will be in one single transactions without passing the EntitySession?

**Comment by rivantsov** [comment]
we don't, because SQL Server does not support them, and also none of the other servers. If you open session - you're by definition using a  separate connection, so trans is isolated on this conn. Most likely you don't really need them, at least most devs/apps live without them

**Comment by jasonlaw** [comment]
Ok clear now. Thanks.
