### ISSUE TITLE
Default value for attribute with bool or int type.

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#59]
Can we set default value for attribute with bool or int type?

**Comment by jasonlaw** [comment]
To add on, this is particular useful when having the ManyToMany entity, where the entity are automatically generated by the framework.

**Comment by jasonlaw** [comment]
The default with "1"/"0" is not working, I am using SQLite.
However, the New event does the trick, so it solves my problem, thanks. :)

Just a small request, it would be elegance to be able to define the default value with the Column attr.

**Comment by rivantsov** [comment]
yeah, I know, lots of things missing, small like this and big ones; it's on my todo already for quite some time
