### ISSUE TITLE
Union - SQLite

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#60]
Please can someone help me?
What am I doing  wrong with this query?

var q1 = session.EntitySet<IOrderedSubFingerprint>().Where(f => f.HashTable == fingerprint.HashTable01 && f.OrderId == 1).Select(f => f.Spectrum.Id);
            var q2 = session.EntitySet<IOrderedSubFingerprint>().Where(f => f.HashTable == fingerprint.HashTable02 && f.OrderId == 2).Select(f => f.Spectrum.Id);

var q = q1.Union(q2).Select(f => f).ToArray();

I have the following exception:

"Vita.Data.Linq.Translation.LinqTranslationException: Linq to SQL translation failed: Queryable method Union not supported.\r\nPossibly facilities you are trying to use are not supported. \r\nTry to reformulate/simplify the query. Hint: do not use c# functions/methods inside query directly.  ---> System.Exception: Queryable method Union not supported.\r\n   at Vita.Entities.Util.Throw(String message, Object[] args)\r\n   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeQueryableCall(MethodInfo method, IList`1 parameters, TranslationContext context)\r\n   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeCall(MethodCallExpression expression, IList`1 parameters, TranslationContext context)\r\n   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)\r\n   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, Expression parameter, TranslationContext context)\r\n   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(ExpressionChain expressionChain, Expression parameter, TranslationContext context)\r\n   at Vita.Data.Linq.LinqEngine.TranslateSelectExpression(Expression linqExpr, TranslationContext context)\r\n   at Vita.Data.Linq.LinqEngine.TranslateSelect(EntityCommand command)\r\n   at Vita.Data.Linq.LinqEngine.Translate(EntityCommand command)\r\n   --- End of inner exception stack trace ---\r\n   at Vita.Data.Linq.LinqEngine.Translate(EntityCommand command)\r\n   at Vita.Data.Runtime.Database.ExecuteEntitySelect(EntitySession session, EntityCommand command, DataConnection conn)\r\n   at Vita.Data.Runtime.Database.ExecuteEntityCommand(EntitySession session, EntityCommand command)\r\n   at Vita.Data.Runtime.DataSource.ExecuteLinqCommand(EntitySession session, EntityCommand command)\r\n   at Vita.Entities.Runtime.EntitySession.ExecuteCommand(EntityCommand command, Boolean withIncludes)\r\n   at Vita.Data.Linq.EntityQueryProvider.System.Linq.IQueryProvider.Execute(Expression expression)\r\n   at Vita.Data.Linq.EntityQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)\r\n   at Vita.Entities.Model.EntityQuery`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at MassFrontier.Spectrum.Fingerprint.Repositories.FingerprintRepository.FindByOrderIdOnce(SubFingerprintDto fingerprint)\r\n   at MassFrontier.Spectrum.Fingerprint.Repositories.FingerprintRepository.FindOrderedCandidates(SubFingerprintDto dto, Int32 vote)\r\n   at MassFrontier.Data.Fingerprint.App.ViewModel.TraverseDirectoriesViewModel.<SearchSpectraByFingerprint>d__37.MoveNext() in D:\\Limos\\Downloads\\LSH\\soundfingerprinting-develop\\soundfingerprinting-develop\\src\\Spectrum.Fingerprint\\MassFrontier.Data.Fingerprint.App\\ViewModel\\TraverseDirectoriesViewModel.cs:line 152\r\nException data (Vita.Data.Linq.Translation.LinqTranslationException): \r\n  LinqCommand = (Select) (@P0, @P1) => EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P0) AndAlso (f.OrderId == 1))).Select(f => f.Spectrum.Id).Union(EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P1) AndAlso (f.OrderId == 2))).Select(f => f.Spectrum.Id)).Select(f => f) \r\n  LinqQuery = (@P0, @P1) => EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P0) AndAlso (f.OrderId == 1))).Select(f => f.Spectrum.Id).Union(EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P1) AndAlso (f.OrderId == 2))).Select(f => f.Spectrum.Id)).Select(f => f) \r\n  entity-command = (Select) (@P0, @P1) => EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P0) AndAlso (f.OrderId == 1))).Select(f => f.Spectrum.Id).Union(EntitySet<IOrderedSubFingerprint>.Where(f => ((f.HashTable == @P1) AndAlso (f.OrderId == 2))).Select(f => f.Spectrum.Id)).Select(f => f) \r\n  parameters = [1317732131, 2030738743] \r\n" 

I use VITA 2.0.2 and SQLite database

Thank you in advance

 Milos

**Comment by rivantsov** [comment]
that's what it says - UNION not supported (yet - hopefully will be in the near future). You just have to run 2 separate queries and merge results on c# side.  I do not think it would make any big impact in perf, specifically with SQLite

**Comment by suchym** [comment]
In fact it is 25 queries. I have no problem with this approach. I wondered why "unsupported" when SQLite supports union query. Now it is clear. Thank you for answer.
