### ISSUE TITLE
VITA 1.9.3 PostgreSQL save issue

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#61]
I am moving our solution from MSSql (Express) to PostgresSQL 11.
After some code refactoring I started to test actions on the database.
When I attempted to save our tree data.
I got exception:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Vita
  StackTrace:
   at Vita.Data.Database.CheckRecordIdentityReferencesBeforeUpdate(EntityRecord record) in D:\Dev\MF8\3rd\VITA\1.9.3\vita-master\1.Framework\Vita.Core\Data\Database\Database.cs:line 222

![image](https://user-images.githubusercontent.com/22904904/48197084-e4316300-e354-11e8-9493-e87f6159d11b.png)

As you can see targetEnt equals to DBNull.Value.

Here is what contains ValueTransient list in GetValueDirect method
![image](https://user-images.githubusercontent.com/22904904/48197094-ee536180-e354-11e8-8994-a492b4c6a04a.png)

The entity definition, where save failed, is following:

[Entity(TableName = "SpectralTreeNode"),
        Index(MemberNames = "Id,Stage,TreeId"),
        Index(MemberNames = "Stage", IncludeMembers = "Id,TreeId")//*09/29/2016
    , KeepHistory]
    public interface IPgSpectralTreeNode : IEntity
    {
        [EntityRef(KeyColumns = "TreeId"), CascadeDelete, Index(MemberNames = "TreeId", KeyType = KeyType.Index, IndexName = "IX_SpectralTreeNode_TreeId")]
        IPgSpectralTree SpectralTree { get; set; }

        [Column("Id"), PrimaryKey(IsClustered = true), Identity]
        int Id { get; set; }

        [EntityRef(KeyColumns = "ParentNodeId"), Index, Nullable]
        IPgSpectralTreeNode ParentNode { get; set; }

        [Column("Stage")]
        byte Stage { get; set; }

        IList<IPgSpectrum> Spectra { get; }
    }

The only difference between MSSQL and PostgreSQl database is that in Postgres I created more separated schema (areas).
In MSSQL I had only default 'dbo' and one additional 'pathway'. I do not know if it has any influence.

The code which process data from client and creates entities for save is the same for both database providers. MSSQL works but PostgreSQL do not.

Can you help me please? Any idea what am I doing wrong?

Milos

**Comment by rivantsov** [comment]
Hmm... can I suggest moving to 2.0 version first (with .net core)? Nothing should change for your code.

**Comment by suchym** [comment]
Unfortunately I cannot move to .NET Core yet. 

I think that the problem occurs only under specific conditions (non-batch mode turned on and self-referencing entity) and regardless of the database provider.

I made small change in the VITA code to try to solve the problem. It seems that patch works (at least for me).
Bellow is what I did

![image](https://user-images.githubusercontent.com/22904904/48263258-d5ff4780-e425-11e8-906c-8fc356004a79.png)

**Comment by rivantsov** [comment]
I think you're a bit confused about .NET core. You don't have to move YOUR code to .NET core to use VITA .net core version - you can stay on full fwk version but reference NET core libraries (built on .NET standard 2.0) - unless you are on really old version of full framework. 
I urge you to try to switch to using Vita 2.x net-core version. The reality is - I cannot even patch prev 1.9 version now (cannot create nuget package 1.9.4), the sequence moved on to 2.x. This is kinda screw up on my part, did not want to rename vita packages for net-core, decided to continue with old names. 
So I found the place in old code you point here, but not in new one - things change. I will look more in new version on weekend, will make more advanced unit test for identity values and check - but the patch (if needed) will be only in net core version. 
Another big factor, specific for Postgres, I had a lot of troubles with using Postgres stored procs in the past, really troubled spot there, note all these disputes in postgres forums about auto-de-referencing the cursor returned by stored procs - real mess, they went back and forth multiple times. That was one of the strong incentives to move away from stored procedures completely in v2, for all servers. 
So it should work for you, v2 net core, and if not - I will quickly patch it. 
Again, my apologies for this bug, but... Using identities in db - these are kinda treated as marginal case in Vita, out of dozens of unit tests only a couple test models with identity columns, so this bug slipped thru. Identities are thing of the past IMHO

**Comment by rivantsov** [comment]
Hi - how's it going with this? did you decide to move to 2.0 or staying with 1.9 with your custom fix? does it work for you?

**Comment by suchym** [comment]
Hi Roman!

I will stay with the 1.9 version, but I move on to the 'Core' as soon as
possible.
The fix is working. I tested inserting data. It is a bit slower than MS SQL
version but now it is not a problem.

Now I'm trying to be more familiar with PostgreSQL.
Quite different from MS SQL. I admire how you connected these different
worlds together in the VITA.

Best Regards

Milos

pi 16. 11. 2018 o 18:03 Roman Ivantsov <notifications@github.com>
napísal(a):

**Comment by rivantsov** [comment]
thanks for the update. slowness is likely result of turning off batch execution, PG is not slower than MS SQL in general

**Comment by suchym** [comment]
Yes, I agree, I see it in reading.

**Comment by mdissel** [comment]
> thanks for the update. slowness is likely result of turning off batch execution, PG is not slower than MS SQL in general

Are BatchedUpdates supported in the VITA framework for PostgreSQL?

**Comment by rivantsov** [comment]
batching for pg - yes, fully supported
