### ISSUE TITLE
Error with MySQL

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#62]
Hi,

I encountered the following error when using MySQL, it works fine with SQLite and MSSQL.

Vita.Entities.DataAccessException
  HResult=0x80131500
  Message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"community"' at line 1
  Source=Vita
  StackTrace:
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)

I debug and found the sql syntax is like following (from ApplyUpgrades method, script.Sql):
"CREATE SCHEMA \"community\";"

What could be the problem?

Thanks in advance.

**Comment by jasonlaw** [comment]
Fyi, I am using the following version of mysql:
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper

**Comment by rivantsov** [comment]
hmmm... i'm using MySql 5.7.22 Community Server; just ran this in MySql Workbench:
CREATE SCHEMA "community";

success... can you try the same directly from MySql Wbench or whatever tool you have? 
see if it fails, try without quotes - it runs ok for me.
There might be a server setting or smth regading quotes - my best guess. Let me know the result and then we'll google I guess

**Comment by rivantsov** [comment]
editLine wrapper - what is this? maybe it adds some extra symbols when it sends string to server?

**Comment by jasonlaw** [comment]
I found a readme in the Driver folder and it specify to include the ANSI_QUOTES for sql_modes. After adding that it is working now. :)
Really appreciate your support. Many thanks.
