### ISSUE TITLE
Version 2.1 pushed

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#64]
ORACLE

**Comment by rivantsov** [comment]
Some details and wining is here: 
https://github.com/rivantsov/vita/wiki/Code-changes-history

**Comment by Michaellok1992** [comment]
Hi @rivantsov , great work! thanks for the hard work. very appreciate and it help me in development alot.

I will branching my current system out to test the version 2 + 2.1 of VITA. Will be logging few issue to you soon.

Thanks again for your effort!
