### ISSUE TITLE
How to name index in Vita (Vita version 2.1)

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#65]
Hi @rivantsov , how can i put a name for my index? 

![image](https://user-images.githubusercontent.com/40017655/49882760-40176c00-fe6c-11e8-9cc5-a1c9f0b09129.png)

Note: migrated from vita 1.9.x

**Comment by Michaellok1992** [comment]
Not urgent. Im still in testing phase for vita version2

**Comment by rivantsov** [comment]
should be fixed now

**Comment by Michaellok1992** [comment]
Cant verify this ticket due to #68
