### ISSUE TITLE
Query error (Vita Version 2.1)

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#66]
Hi @rivantsov ,

i encounter this error.

Exception message: Incorrect syntax near ')'.

`SELECT  COUNT_BIG(x$."BankTransactionType_Id" = 1 AND x$."DepositType_Id" = 1)
FROM "dbo"."BankTransaction" x$
     INNER JOIN "dbo"."SysUser" t0$ ON t0$."Id" = x$."CreatedBySysUser_Id"
WHERE x$."IsActive" = 1 AND t0$."Organization_Id" = @P0 AND x$."BankAccount_Id" = @P1 AND @P2 <= x$."CreatedDate" AND @P3 >= x$."CreatedDate" AND x$."BankTransactionType_Id" = 1 AND x$."DepositType_Id" = 1;`

Let me know if you need additional information.

**Comment by Michaellok1992** [comment]
-- Case 2 --
Exception message:
Incorrect syntax near ')'.
Incorrect syntax near the keyword 'AND'.


SELECT  COUNT_BIG(x$."BankTransactionType_Id" = 1 AND x$."DepositType_Id" = 1)
FROM "dbo"."BankTransaction" x$
     INNER JOIN "dbo"."SysUser" t0$ ON t0$."Id" = x$."CreatedBySysUser_Id"
     LEFT JOIN "dbo"."PlayerUsername" t1$ ON t1$."Id" = x$."PlayerUsername_Id"
WHERE x$."IsActive" = 1 AND t0$."Organization_Id" = @P0 AND x$."BankAccount_Id" = @P1 AND @P2 <= x$."CreatedDate" AND @P3 >= x$."CreatedDate" AND t1$."GameUsername" = @P4 AND EXISTS 
  (SELECT  *
FROM "dbo"."BankAccount" t2$, "dbo"."OrganizationBankAccount" y$
WHERE y$."BankAccount_Id" = t2$."Id" AND y$."Organization_Id" = @P5) AND x$."BankTransactionType_Id" = 1 AND x$."DepositType_Id" = 1;

**Comment by rivantsov** [comment]
I suspect your query uses Count(expr) variation; it is not supported - it is in fact a bug, it should be treated as filter expr, but it puts it directly into argument of COUNT_BIG (there are cases I think when it makes sense but not here)
So try to moving the condition from Count(...) to Where(...), that should work

**Comment by Michaellok1992** [comment]
Your suggestion is... 

Instead of : `list.Count(x => x.id == '234123')`
Do this: `list.Where(x =>x.id == "123123").Count()`

Is this workaround? or u will fix this bug?

**Comment by rivantsov** [comment]
yes, 
bug - already fixing, so this is temp workaround, but really these 2 ways are equivalent, so you can leave it like this forever

**Comment by Michaellok1992** [comment]
Alright. Thanks!

**Comment by rivantsov** [comment]
hi! anything else for me? I've fixed all that and preparing patch push

**Comment by Michaellok1992** [comment]
I got 1 or 2 more. But im not sure is bug or my coding not right. I will open an issue for you tonight. Feel free to push the update. :)

Thanks.

**Comment by rivantsov** [comment]
Count(...) error had been fixed

**Comment by Michaellok1992** [comment]
Working now. Thanks
