### ISSUE TITLE
Patch version 2.1.1 pushed

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#67]
Fixes: 
1. Allowing filter expression in Count(filter) LINQ expression
2. Fixed setting explicit key/index name using DbKeyName property of Index attribute
Only Vita package is updated, version set to 2.1.1
Other packages have no changes

**Comment by Michaellok1992** [comment]
So far so good. It seems like some old issue before version 2 has no longer there. 👍 

Good work! @rivantsov
