### ISSUE TITLE
Failed to index due to column not found (Vita Version 2.1.1)

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#68]
Encounter error message: Member game_id not found in entity IPlayerUsername.

In the class:
![image](https://user-images.githubusercontent.com/40017655/50013339-d928bd00-fffb-11e8-93f1-0a5297c84080.png)

In the Database:
![image](https://user-images.githubusercontent.com/40017655/50013379-f2316e00-fffb-11e8-9b14-6ddbb1122736.png)

**Comment by rivantsov** [comment]
you should use 'Game' in memberNames, not Game_id, property name

**Comment by Michaellok1992** [comment]
I see. May i suggest that this INDEX should have a documentation as well for future developer. 😃

**Comment by rivantsov** [comment]
I know, I know... some day, it will be there. but in general, remember that in entity model, it's all about entities (interfaces) and properties, db columns do not exist yet, they come later when we merge with db driver and naming policy and lots of other things... so almost everywhere (almost) you reference properties, not db columns
