### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by preguntoncojonero** [rivantsov/vita#7]
What's about Performance ?

https://www.exceptionnotfound.net/dapper-vs-entity-framework-vs-ado-net-performance-benchmarking/

Why Vita, wht not DApper ?

any good patterns and practices using Vita? 

I use Enterprise Library 5.0 in ASP.NET 4.6.1 

Suggestions: full source code useful, complete and sample using patterns & practices about it.

About it Vita, any step-by-step guide, or Getting Started – Quick Start that can be completed in 15-20 minutes?

I get you a good step-by-step guide sample like https://berniecook.wordpress.c...

I wanted to quickly cover off several assumptions before we get started:
install (requisites, tools required), configure, an running quickly.
Target will be an “go and ready” sample. Maybe better an real application sample

Mindly notes:

Any good getting started about it? step by step in 10 minutes?

IMHO, better samples for minimize learning curve are real applications with full source code and good patterns and practices

Full source code sample REAL application? not Demo, only real applications?

Like for small to medium applications development, but open source, if you
can sharing or maybe another real project or production-ready
application using main influences, are full of innovative ideas that can free our minds to explore new techniques, patterns and paradigms.

You want to use technologies that allow for rapid development, constant
iteration, maximal efficiency, speed, robustness and more. You want to
be lean and you want to be agile. You want to use technologies that will help you succeed in the short and long term. And those technologies are not always easy to pick out.

Thanks a lot for your big efforts.

**Comment by rivantsov** [comment]
hi
sorry did not see your post, don't understand why github did not alert me. something wrong there. Answering your questions: 
Quick startup guide - look at documentation on old site: 
https://vita.codeplex.com/documentation
it has quick-start guide, and some intro guides. Documentation still not migrated to github, no time for anything. 
Another way to start - look at sample bookStore app in download zip, and also unit tests - giving all kinds of examples of use. Look at BookStore.UI app, demonstrates use of WebApi RESTful service with Angular front-end. 
Real world apps - they exist, but not open source. My company (my daytime job) we have several apps already, in the cloud, one in active development, and one flying on space station! Unfortunately, these are closed source, proprietary. Plus, they are quite specialized, not very useful for wide audience. 
Feel free to ask any questions here

**Comment by rivantsov** [comment]
About best practices, rapid development etc. VITA offers one technology not found anywhere else - component-based development for data apps. Look a Vita.Modules assembly, and how it is used in sample BookStore app. LoginModule is imported into the app, with all its tables and functionality (quite substantial).

**Comment by Almeonamy** [comment]
Do you have any performance analisis?

**Comment by rivantsov** [comment]
Honestly, never did formal benchmarks, like ORM-Battle (now defunct). Just always kept an eye on logs (with SQLs and execution time with # of records). The numbers look quite good. For application performance in general, it's not only execution time of single statement that matters, but also features like Includes, batch execution, data cache, SQL cache etc. VITA supports all of these (although some are not migrated yet, but coming very soon). I also kept an eye on implementation of perf features in other ORMs, and for some of them VITA's impl is better. As an example, EF does Includes by creating one huge join to all included tables, and in any non-trivial case (3+ tables) results in really inefficient SQL and too much data returned (repeated data!). Or entity tracking - it is a known issue in EF that if you turn on entity tracking, the system slows down considerably. Not the case in VITA. 
So, run unit tests or your own test app, look at the logs, play with settings (batch on/off), and make your judgement.
