### ISSUE TITLE
[ExecuteSearch] SearchResult TotalCount is wrong when exceeding the number of records

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#74]
I think I have encountered a bug in SearchResult for ExecuteSearch.

If I have 15 records in my table, with the following search parameters values:
1. Skip = 0, Take = 10 => Return 10 records, TotalCount = 15 (correct)
2. Skip = 1, Take = 10 => Return 5 records, TotalCount = 15 (correct)
3. Skip = 2, Take = 10 => Return 0 record, TotalCount = 20 (wrong)
4. Skip = 3, Take = 10 => Return 0 record, TotalCount = 30 (wrong)

I am using the latest 2.2 build.

Thank you.

**Comment by rivantsov** [comment]
ha ha, really funny and stupid bug. Good catch! What's funny - it's so obvious why it happens, I knew what's wrong as soon as I saw your message; and so stupid that I overlooked it and it never occurred to me that it might happened
thanks for catching this. I pushed the fix.

**Comment by jasonlaw** [comment]
Thanks for the quick fix, really appreciate it!
