### ISSUE TITLE
Things not migrated to 2.2.0

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#75]
I am trying to convert my applications to version 2.2 from 1.9.xxx

I see that there are lots of thing not converted,
Some examples:
- directSql.ExecuteDbCommand(cmd, DbExecutionType.NonQuery);

   On table definition:
- [AsIs, NoInsertUpdate, Nullable] ---- whas it changed to NoUpdate
        decimal QtdEntradas { get; }

    On table definition:
 - [Column(DbType = DbType.Binary), Nullable, Unlimited]
        byte[] ImagemStore { get; set; }
- [Nullable, Column(DbType = DbType.Date)] - Error on dbtype
        DateTime? DataExportado { get; set; }
- [Entity(Name = "Documento", TableName = "Documentos"), ClusteredIndex("DataCriacao,ID")]
    [Unique("Serie,Numero,Ano,Loja", **IndexName** = "idx_SerieNumeroAno")]
    [Display("{NumeroSAFT}")]
    public interface IDocumento...... IndexName dos not existe anymore

-  query.ExecuteDelete<IFamilia>(); - Execute delete dos not existe anymore

Thanks
Ruben

**Comment by rubenalves** [comment]
App.CacheSettings.LocalSparseCacheTypes.Add(typeof(ICaixa)); - No caching?

**Comment by rubenalves** [comment]
App.GetService<IDataAccessService>().Events.DataSourceStatusChanging += EventsOnDataSourceChange; - no Events?

**Comment by rivantsov** [comment]
Hi

* directSql.ExecuteDbCommand(cmd, DbExecutionType.NonQuery);
     -- Use ExecuteNonQuery(cmd)
     
  On table definition:
* [AsIs, NoInsertUpdate, Nullable] ---- whas it changed to NoUpdate
  decimal QtdEntradas { get; }
     -- Just remove the attribute; it provided some automatic check that value is not modified by code in insert or update ops; so just don't do it in code and you'll be fine
  On table definition:
* [Column(DbType = DbType.Binary), Nullable, Unlimited]
  byte[] ImagemStore { get; set; }
      -- DbType is gone; use DbTypeSpec to specify exact Db column type;
        if you remove DbType here; the system will assume varbinary(max) type; if you need smth else, specify it in DbTypeSpec 
* [Nullable, Column(DbType = DbType.Date)] - Error on dbtype
  DateTime? DataExportado { get; set; }
     -- Same here, use DbTypeSpec = "date" instead 
* [Entity(Name = "Documento", TableName = "Documentos"), ClusteredIndex("DataCriacao,ID")]
  [Unique("Serie,Numero,Ano,Loja", **IndexName** = "idx_SerieNumeroAno")]
      -- use DbKeyName instead
  [Display("{NumeroSAFT}")]
  public interface IDocumento...... IndexName dos not existe anymore
* query.ExecuteDelete(); - Execute delete dos not existe anymore
      -- session.ExecuteDelete(query);
      
* App.CacheSettings.LocalSparseCacheTypes.Add(typeof(ICaixa)); - No caching? 
      -- yes, data cache is not migrated yet; try going without it, hope your server can sustain the extra load; cache will be back (reimplemented in a different way), soon
      
* App.GetService().Events.DataSourceStatusChanging += EventsOnDataSourceChange; - no Events?
      --  App.DataSourceEvents.DataSourceChange += ....

again, sorry for troubles

**Comment by rubenalves** [comment]
I see another error

using Vita.Modules.EncryptedData;
licencaAplicacao.Numero = EntityHelper.GetSession(licencaAplicacao)
                .NewOrUpdate(licencaAplicacao.Numero, numero, "TsChannel");

The encrypted data is not ported yeat or does it work diferent?

Thank you.

**Comment by rubenalves** [comment]
There are some modules that no longer exists.

public EncryptedDataModule EncryptedDataModule;
public IncidentLogModule IncidentLogModule { get; set; }
public DbUpgradeLogModule DbChangedModule { get; set; }
public ErrorLogModule ErrorLogModule;
public TemplateModule TemplateModule;
ErrorLogModule LogModule;
public LoginLogModule LoginLogModule;

Thanks

**Comment by rivantsov** [comment]
Encrypted data - not migrated, and will not be. I think I announced some time ago, that it is deprecated; the solution with a separate table for encrypted data did not work well. But... you can just copy the code from old version, move the EncyptedData entity module into your code base and use it.  
Logging modules - not migrated yet, but will be, with some adjustments

**Comment by rubenalves** [comment]
I have made the application to compile and create the database, but now i get this error:
---------------------
Initializing EntityApp TsGest 2019.====================================
  Building entity model...
Entity model built successfully.
App TsGest 2019 initialized.
  Connecting to data source (Default).
ERROR: Failed to map member type System.Byte[] to DB type; member FormHeader.LogoTalao -  error: Invalid DbTypeSpec ({0}, expected size parameter.
ERROR: Failed to map member type System.Byte[] to DB type; member FormHeader.LogoDocumentos -  error: Invalid DbTypeSpec ({0}, expected size parameter.
--------------------------------

Do you have any idea of what the problem can be?

Thanks for your time.

**Comment by rivantsov** [comment]
Looks like you are missing Size attr on these two props; it should be either Size or Unlimited. Pls post the property definitions here, I would be able to advise more

**Comment by rubenalves** [comment]
[Column(DbTypeSpec = "binary"), Nullable, Unlimited]
        byte[] LogoTalao { get; set; }

        [Column(DbTypeSpec = "binary"),Nullable, Unlimited]
        byte[] LogoDocumentos { get; set; }

That is part of the table declaration

**Comment by rivantsov** [comment]
ah, remove DbTypeSpec, it should then map to 'varbinary(max)'

**Comment by rubenalves** [comment]
Now it gives this error:
-----
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
-----

**Comment by rivantsov** [comment]
when you run which query?! is it still startup? or already runtime and you are running queries?
pls post call stack, or whatever you have. 
Another question - are you trying to map to existing db, with DbUpdateMode = Never, without modifying schema, or your app updates/adjusts db schema?

**Comment by rivantsov** [comment]
looks like somewhere you have nvarchar type (column? linq param? view definition?), but in another place it is varbinary(max). try to find where's mismatch

**Comment by rubenalves** [comment]
I am inserting a new entity on the table.
I am using the auto update the db schema.
i will do some more tests and confirm the column type on all tables.
Regards.

**Comment by rivantsov** [comment]
Ok, so it is already runtime, db update finished. Check db tables, that all column types are as expected. Then look at entity-insert code and entity def. Log file must contain failed SQL statement, it might help. 
Post here whatever you can, I am here to help

**Comment by rubenalves** [comment]
varbinary(max) is created in sql table definition on byte[] type in code,

**Comment by rivantsov** [comment]
yep, that's expected, and I guess that's what you want; now where's nvarchar is coming from?! do you do linq-based inserts? just wild guess

**Comment by rubenalves** [comment]
[AsIs, NoUpdate, Nullable]
decimal DebitoReabertura { get; }

I think that the problem is in... NoUpdate and it was NoInsertUpdate before. When i try to insert i get a error, 
Vita.Entities.DataAccessException: 'The column "DebitoReabertura" cannot be modified because it is either a computed column or is the result of a UNION operator.
The column "CreditoReabertura" cannot be modified because it is either a computed column or is the result of a UNION operator.

Regards.

**Comment by rivantsov** [comment]
so, what's the column definition in db? AsIs means do not try to change the column definition, leave it as-is;  so try removing NoUpdate attribute, see how it goes and also look at column def, let me know

**Comment by rubenalves** [comment]
The columns is a database computed column.

I have removed the NoUpdate and it is the same error.

Before the NoInsertUpdate worked fine.

**Comment by rivantsov** [comment]
ok, I see, give me some time to figure it out

**Comment by rivantsov** [comment]
ah, now the attribute is called ReadOnlyAttribute (former NoInsertUpdate), try it

**Comment by rubenalves** [comment]
I got it working.
Now there is a list with .ToList() - With OrderBy in linq query and OderByDescenting, there probably are mote.
Thanks.

**Comment by rivantsov** [comment]
good, 
but did not quite get what you mean by this OrderBy and ToList() sentence

**Comment by rubenalves** [comment]
One example:
var taxa = linha.Iva?.Taxas.OrderByDescending(c => c.Data).FirstOrDefault(c => c.Data <= linha.DataIVA);
i get a error: System.ArgumentException....The destination array was not long enough. Check destIndex, the length and the lower bounds of the array.

**Comment by rivantsov** [comment]
can you pls send me a stack trace and full ex info from log file? (or do ex.ToLogString() in catch block)

**Comment by rubenalves** [comment]
I can only find this:
----------
   em System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   em System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   em System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   em System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   em System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   em TsGest.DL.Domain.Extentions.LinhaDocumentoExtension.GetTaxaIva(ILinhaDocumento linha) em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest.DL\Domain\Extentions\LinhaDocumentoExtension.cs:line 93
------------------
Thans.

**Comment by rivantsov** [comment]
strange, looks like it happens inside linq/enumerable code. 
One thing I noticed - you first order-by, then filter (arg of FirstOrDefault) and then take first. For perf it might be better to filter first. So try: 

var taxa = linha.Iva?.Taxas
   .Where(c => c.Data <= linha.DataIVA)
   .OrderByDescending(c => c.Data)
    .FirstOrDefault();

and it might fix error?

**Comment by rubenalves** [comment]
It works.

New Problem: 
LancamentosSNC.DataSource = Documento.LancamentosSNC.OrderBy(c => c.DataCriacao);
---- Error: 
   em System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   em System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   em System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   em System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   em System.Windows.Forms.BindingSource.GetListFromEnumerable(IEnumerable enumerable)
   em System.Windows.Forms.BindingSource.ResetList()
   em System.Windows.Forms.BindingSource.set_DataSource(Object value)
   em TsGest.BL.ModelView.Documentos.EditorDocumentoViewModel.BindListas() em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest.BL\ModelView\Documentos\EditorDocumentoViewModel.cs:line 653
   em TsGest.BL.ModelView.Documentos.EditorDocumentoViewModel..ctor(Guid id, String serie, IDocumento docTransfer, ILinhaDocumento linha, Boolean mesmoTerceiro, Boolean ligarDoc) em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest.BL\ModelView\Documentos\EditorDocumentoViewModel.cs:line 100
   em TsGest.NewForms.Documentos.formEditorDocumentos..ctor(Guid id, String serie, IDocumento docTransfer, ILinhaDocumento linha, Boolean mesmoTerceiro, Boolean ligarDoc) em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest\NewForms\Documentos\formEditorDocumentos.cs:line 33
   em TsGest.Forms.FormsHelper.EditarDocumento(RibbonForm parent, DocumentoLista documento) em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest\Forms\FormsHelper.cs:line 64
   em TsGest.NewForms.Documentos.formListaDocumentos.EditarDocumento() em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest\NewForms\Documentos\formListaDocumentos.cs:line 224
   em TsGest.NewForms.Documentos.formListaDocumentos.gridDocumentos_DoubleClick(Object sender, EventArgs e) em C:\Dropbox\TerceiraSoft\2019\TsGest\TsGest\NewForms\Documentos\formListaDocumentos.cs:line 229
   em System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   em DevExpress.XtraEditors.Container.EditorContainer.OnDoubleClick(EventArgs e)
   em DevExpress.XtraGrid.GridControl.OnDoubleClick(EventArgs ev)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   em DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rivantsov** [comment]
the query ends with OrderBy(), so it means it is IQueryable<TEnt>, it is not executed yet at the moment of binding. Should you add .ToList() at the end?

**Comment by rubenalves** [comment]
I have resolved almost every thing.
If i find someting else i will  report the error

Thank you.
