### ISSUE TITLE
Default string size

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#76]
May I know how to change the default string size? I think it is defaulted to 50 now.

**Comment by rivantsov** [comment]
I would strongly suggest against using this, I plan to kill this feature, there should be no default I think. 
Use explicit size, or 'named' size - value defined in Sizes dictionary. Just from my own experience, having default for all brings more harm than benefit.

**Comment by jasonlaw** [comment]
I found the way to change the default value. I think it is a good feature, pls keep it.
