### ISSUE TITLE
1.9.* version

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#78]
Will Version 1.9.* receive any bug fixes or is it realy dead?
Version 2.* killed very good features and my aplication was built for the past 4 years with those features and for i need to rewrite all the data layer.

Thanks.

**Comment by rivantsov** [comment]
hi
I was hoping 1.9 will slowly go to end of life.
what bugs are you talking about in 1.9? do you have any particular show stoppers? I thought you migrated to 2.0?
so let's work out the plan: 
1. If you stay on 1.9, what bugs there do you have? I can resurrect it and patch if it is a really serious issue
2. For 2.x - what features are you missing and cannot move without? my guess is SlimApi might be the one. I plan to publish soon the first iteration - a sample with .NET core api controllers (full controllers), this will show you migration path, a bit painful but still migration, not rewrite. SlimApi will come later
Let's work on this, we can figure it out

**Comment by rubenalves** [comment]
My app is working fine in 1.9. No bugs deteced till now.
The features that is very important is the "data encription" -  "EncryptedDataModule" - that will not be in 2 as you stated. 
If 1.9 is not dead for bug fixes it is ok for me.

**Comment by rivantsov** [comment]
Ok, I'll make it a priority, I will put back EncryptedDataModule in the next push, hopefully within a month

**Comment by rubenalves** [comment]
Are you still planing to put back EncryptedDataModule? not urgent, just to know.
Thanks.

**Comment by rivantsov** [comment]
yes, I'm rounding up next version, with Web api stuff, EncrData will be there. Should be out before the end of the year

**Comment by rivantsov** [comment]
done, v3 is published, EncryptedData is there, in Vita.Modules.Legacy package/project
