### ISSUE TITLE
Moving To latest VITA Fraamework

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#79]
Hi Roman!

I went to the latest version of Vita Framework. Just a moment ago.
After the necessary refactoring, I started the program.
 And I got an exception "Invalid key / order spec 'CompoundId, Id', entity ..., member CompoundId not found.

'CompoundId, Id' belongs to the index definition. This is a PostgreSQL database. I assume it's something like https://github.com/rivantsov/vita/issues/38.

I tried to change the column name of the index to small letters, but it didn't work.

I watched the code samples and also the code in Vita, but there are the same names as I do.

What should I do? Is there any solution?

Best Regards

Milos

**Comment by rivantsov** [comment]
what's the source (entity/prop def)? 
I suspect you have an entity Ref Compound with underlying CompoundId column - then you should use property name, not column name. Also remove space after comma; I think I fixed this but just in case

**Comment by suchym** [comment]
Here is part of entity definition:

 [Entity(TableName = "Pathway"),
        ClusteredIndex("CompoundId,Id"/*, IndexName = "CIX_Pathway_CompoundId_Id"*/)]
    public interface IPgFragmentationPathway : IEntity
    {
        [EntityRef(KeyColumns = "CompoundId"), CascadeDelete/*, OneToMany,*/]
        IPgCompound Compound { get; set; }

        [Column, PrimaryKey, Identity]
        int Id { get; set; }

        [Column]
        byte Polarity { get; set; }

I commented out the index name because I did not know workaround, but I found solution here. 
Do you think that I have to change CompoundId to Compound, but in what place? Clustered index definition or key columns part?

**Comment by rivantsov** [comment]
yes, change to Compound in ClusteredIndex list, and then it should work. Again, you should use PROPERTY names there, not column names

**Comment by suchym** [comment]
I applied recommendation on one entity and it disappeared from exception.
It seems it works. I go to change rest of index definitions.
Thanks for your help.
