### ISSUE TITLE
Exception when trying to run the demo

### ISSUE THREAD

**Issue by adjdred** [rivantsov/vita#8]
I am trying to run the demo to see how your implementation of views works however I get the below exception.

"System.NullReferenceException: Object reference not set to an instance of an object.
   at Vita.Data.MsSql.MsSqlDbSqlBuilder.BuildSelectAllPagedCommand2008(EntityCommand entCommand)"

After a bit of debugging it appears that the order is trying to use the primary key on the table (for a view) but the property is null.

Line 55 in MsSqlDbSqlBuilder.cs
if (string.IsNullOrEmpty(strOrderBy))
                    strOrderBy = "ORDER BY " + table.PrimaryKey.KeyColumns.GetSqlNameList();

Connecting to a MsSQL 2008 database and the issue was raised for the vBookSales view.

**Comment by adjdred** [comment]
Found that if I add the OrderBy attribute to all of the views the demo works.

**Comment by rivantsov** [comment]
definitely a bug, will fix it asap. Preparing for a new push this weekend, will be fixed.
thanks for reporting it

**Comment by rivantsov** [comment]
should be fixed now in 1.9, try it without explicit order by

**Comment by adjdred** [comment]
Thanks. I will take a look over the weekend.
