### ISSUE TITLE
RegisterSize in EntityModule

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#80]
RegisterSize works still in VITA?
I get an exception: Unknown size code 'AppVersion', entity / member: PgTreeAggregatedData.Version.
 'AppVersion' size is registered in the same module as IPgTreeAggregatedData entity which refers to it.

I looked up VITA solution. There is one entry where 'EventType' size is registered but no usage found.

**Comment by rivantsov** [comment]
I will double-check and fix it by next push. For now, just use direct size number

**Comment by rivantsov** [comment]
should be fixed in 2.3.1
