### ISSUE TITLE
Could not load type 'Vita.Entities.Services.IDbInfoService' from assembly 'Vita, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'. 

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#81]
I am trying to get service to the running state. Above exception is raised when creating my entity application instance in code. 
I suspect WCF that it does not allow to  call .NET Standrad libraries from WCF Service, but I can not find any relevant source.

Also in Test Explorer in VS I tried to perform simple test which consisted of creating entity app, operation context and opening session to the database and executing query .
It passed. 

Have you any idea what with this ?

**Comment by rivantsov** [comment]
there must be something more in this error, some explanation why - not found? not compatible? not authorized? Try accessing type(s) directly from code, like: 
var dbInfoType = typeof(Vita.Entities.Services.IDbInfoService); 
try other types, not interfaces. Have a look at Debug Output window in VS, it should have trace of type resolving-loading process, etc. Something with environment I guess, or folders/paths? Research-google TypeLoadException in link with WCF

**Comment by suchym** [comment]
I apologize for rushing with previous issue.
I moved a little forward.
 I would like to ask if you know from where this comes into the project.
 It happened when I installed VITA.Data.SQLite (2.2.0). 
I did not see anything like this in your solution.

![image](https://user-images.githubusercontent.com/22904904/55083708-3e348a00-50a4-11e9-862b-ce97cd5f4ca9.png)

I do not start service because I cannot initialize connection to the SQLite database.

One of exceptions: You need to call SQLitePCL.raw.SetProvider(). If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().

then I found on the web that I have to call : 
 SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_e_sqlite3());
before connection is openend. I did.

Now I get:
System.TypeLoadException: 'Method 'sqlite3_blob_open' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.

Never ending story...

**Comment by rivantsov** [comment]
by the way, it did work well with Vita 1.9 in exactly the same app/service? then it's really puzzling and might point to .NET core or CLR host env, smth like this as primary suspect. By the way, WCF? is is possible to switch to smth more modern like Web api? WCF is a piece of shh... trouble in itself, and generally people try to move away from it as quick as possible

**Comment by suchym** [comment]
I cannot leave WCF at least for this moment.
SQLite worked perfectly in version 1.9. 
NuGet packages are terrible...
I will try to uninstall all packages including VITA and add VITA's necessary projects to the solution and then add necessary references.
Then I see what happen.
So far, thank you for your help

**Comment by rivantsov** [comment]
From the picture you provided, looks like all this packages are for PCL (Portable Class LIbrary) - which is quite different from my primary target .NET core; PCL I think is much more restrictive and quite different. So, is this your environment? I'm a bit confused.. are you doing some win phone app or smth? But I think the core of the issue is the target platform, check the compatibility of the platform with .NET Standard and especially with SQLite. Also, you are on x64, not x86?
