### ISSUE TITLE
DateTime string convesion error in SQLite

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#82]
What is wrong with this date time string format?
Data comes from SQLite database created with previous version of VITA (1.9.3)
and now after migrating to the 2.2.1 I have this exception.

Vita.Entities.DataAccessException: Failed to convert column value '2019-02-05 13:06:51.3061386Z', type System.String. Converter for column type System.String, property type System.DateTime. ---> System.Exception: Failed to convert column value '2019-02-05 13:06:51.3061386Z', type System.String. Converter for column type System.String, property type System.DateTime. ---> System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at Vita.Data.SQLite.SQLiteTypeRegistry.ParseDateTime(Object value) in D:\Dev\MF8\3rd\VITA\2.2.1\vita-master\vita-master\2.Drivers\Vita.Data.SQLite\SQLiteTypeRegistry.cs

**Comment by rivantsov** [comment]
Looks like I changed unintentionally the default format for date storage. From error message the old format used 7 digits in fraction of a second. The format is in static property SQLiteTypeRegistry.DateTimeFormat, and is set to: 

    public static string DateTimeFormat = "yyyy'-'MM'-'dd' 'HH':'mm':'ss.fff";

try adding more f's up to seven, directly from your code, set it to smth like: 
SQLiteTypeRegistry.DateTimeFormat = "yyyy'-'MM'-'dd' 'HH':'mm':'ss.fffffff";

I will see how to fix this in the next push - will try make it more forgiving on reading data

**Comment by rivantsov** [comment]
should be fixed now, with 2.3
