### ISSUE TITLE
Unicode support for MySQL

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#86]
Hi @rivantsov ,

I am using the latest version. I tested with MySQL and it seems not support for the unicode.

Here is my table structure:
![image](https://user-images.githubusercontent.com/107820/58065600-dd639280-7bb8-11e9-97f3-e3050046e36d.png)

And the data is failed to store as unicode:
![image](https://user-images.githubusercontent.com/107820/58065650-01bf6f00-7bb9-11e9-826d-5a0fc78af9fb.png)

Here is my connection string:
 "DbSettings": {
    "ServerType": "MySql", //MsSql,MySql,Postgres,SQLite"
    "ConnectionString": "Server= xxx.xxx.xxx.xxx; Port= 3306; Uid= xxx; Pwd= xxx; Old Guids= true; SslMode= none",
    "DatabaseName": "CommunityTest"
  }

May I know what had I missed and how to fix the problem?
Many thanks in advance.

Jason Law

**Comment by rivantsov** [comment]
MySql does not have nvarchar, seems like; instead, you specify character set; what I had in mind here is database-wide config of defaulting to unicode, here: 
https://dev.mysql.com/doc/refman/8.0/en/charset-applications.html

CREATE DATABASE mydb
  CHARACTER SET latin1
  COLLATE latin1_swedish_ci;

So try re-creating db
I will add this to Readme, I think I had this info before but it got lost.

**Comment by rivantsov** [comment]
ah, just saw you have unicode there already, should be working... hm... try saving English word - does it work and shows OK?

**Comment by rivantsov** [comment]
just tried with BasicTests project, tried with Russian chars - saved and read back - it works

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Just found the solution, it works after I added CharSet=utf8 into the connection strings.
Thanks for looking into this.

Jason Law
