### ISSUE TITLE
Primary key in many-to-many object

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#87]
Hi @rivantsov ,

I would like to have a single Id primary for all of my entity, but I am not sure how to define it for many-to-many entity. 
Appreciate your advice on how to do that.

Thank you very much.

Jason Law

**Comment by rivantsov** [comment]
just declare it like in any other 'regular' entity, 

[PrimaryKey, Auto]
Guid Id {get;}

Using composite key in link entities is a convenience trick, not a requirement

**Comment by jasonlaw** [comment]
thanks for the advice, and this cool framework!
