### ISSUE TITLE
Computed attribute for object reference?

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#88]
Hi,
May I know does the computed attribute support for object reference? I have User and Community object, and CommunityUser being the many-to-many object. In user, I have a attribute CurrentCommunity that store the community object. I want a computed attribute CurrentCommunityUser which will depends on the CurrentCommunity. However, when I do that, there will be an exception when creating the db. Normal Computed attribute is working.
Appreciate your comments on this.

**Comment by rivantsov** [comment]
yeah, looks like this attribute is not working for this kind of props, code conflicts inside. I would suggest to avoid this facility in general, an extension method is a simple and reliable alternative; and you can step-in and debug it
