### ISSUE TITLE
When to use EntitySet, GetEntities and ExecuteSearch

### ISSUE THREAD

**Issue by adjdred** [rivantsov/vita#9]
Not a bug but need some advice as to when to use EntitySet, GetEntities and ExecuteSearch.

I had an issue earlier where I was using GetEntities to get my records and using .Where to filter them. I later found that GetEntities was not converting the Where to SQL but EntitySet does. To get around this I decided to use the ExecuteSearch as I had the requirement to filter by more than one property so it made more sense to do it this way.

If I only wanted to get one record from table e.g. tblConfiguration which approach would you use and would it be cached?

session.EntitySet(of IConfiguration).FirstOrDefault(function(c) c.ConfigKey = key)
session.GetEntities(of IConfiguration).FirstOrDefault(function(c) c.ConfigKey = key)
session.ExecuteSearch(of SearchResults(of IConfiguration))(where,params)

**Comment by rubenalves** [comment]
I use it like this
session.GetEntity<IConfiguration>(key)

**Comment by adjdred** [comment]
Sadly the config key is not the primary key so using GetEntity is not possible.

Also is GetEntities meant to ignore the where when generating the SQL?

**Comment by rubenalves** [comment]
Ok,

When it not the primary key i use the where clause,

session.EntitySet<IConfiguration>().Where(c => c.key == key).FirstOrDefault()

**Comment by rivantsov** [comment]
ok, here is sum up: 
var ent = session.GetEntity<T>(entId); 
        -- gets a single entity by PrimaryKey value, using stored procedure (if enabled). Works only by PK!
var ent = session.EntitySet<T>().Where(e => e.Id == entId).FirstOrDefault(); 
          -- gets a single entity using dynamic SQL built on the fly (LINQ); can use to search by any property
var ent = session.GetEntities<T>().Where(e => e.Id == entId).FirstOrDefault();
  -- NO NO NO - never do this. What it does - it retrieves ALL entities of this type (entire) table, and then searches the retrieved list for a single entity matching the criteria. 
var results = session.ExecuteSearch(.....); -- special method to execute Search queries, constructed on-the-fly from optional search parameters - in search forms. So the query depends on which boxes on search form user filled in. ExecuteSearch returns 2 things: list of result records/entities, usually page size (skip/take parameters); TotalCount - # of matching records without Skip/Take parameters. This is for Search Pages where you want to show a page of results, and total # of matches. Note that ExecuteSearch runs 2 SQL queries to get these 2 things (sometimes 1 if we hit the last record - returned resultset is less than page size). 
Caching - what do you mean? any record/entity returned from DB is cached inside session; and if new query returns the same record as retrieved previously, the command returns the same 'old' cached instance from first query. This is entity single instance principle (for a given record in db there's always a single entity object representing it, no matter how you retrieve it, multiple times using different method)

**Comment by adjdred** [comment]
Thanks for the advice. I have passed that onto the team here.
