### ISSUE TITLE
[Suggestion] Dont select *, instead select null

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#92]
Hi @rivantsov , i realized the sql when u used for checking EXISTS, u tend to select *. which i don think a good idea. I would like to suggest null.

What do u think?

**Comment by rivantsov** [comment]
will look at it, thanks

**Comment by Michaellok1992** [comment]
Suggestion as
from:
`EXISTS(SELECT * FROM table)`

to:
`EXISTS(SELECT null FROM table)`

**Comment by rivantsov** [comment]
As far as I can see, it does not matter actually. Db server is smart enough to figure out that it does not need to actually select any data from the table (I believe). It all is executed on the server, only bool or single flag value is returned to client. So I decided not to mess up existing code. Let me know if you disagree. thanks for the suggestion anyway

**Comment by Michaellok1992** [comment]
After discussed with my colleagues, they are agreed that Db server should be able to handle it.  👍
