### ISSUE TITLE
[BUG] Incorrect condition due to bracketing

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#93]
Code:
`bankTransaction = bankTransaction.Where(x =>
                    (currentStartDate <= x.UpdatedDate && x.CreatedDate == x.UpdatedDate && x.UpdatedDate >= x.TransactionTime) ||
                    (currentStartDate <= x.TransactionTime && x.CreatedDate == x.UpdatedDate && x.UpdatedDate < x.TransactionTime) ||
                    (currentStartDate <= x.UpdatedDate && x.UpdatedDate > x.CreatedDate))`

`bankTransaction = bankTransaction.Where(x =>
                    (currentEndDate >= x.UpdatedDate && x.CreatedDate == x.UpdatedDate && x.UpdatedDate >= x.TransactionTime) ||
                    (currentEndDate >= x.TransactionTime && x.CreatedDate == x.UpdatedDate && x.UpdatedDate < x.TransactionTime) ||
                    (currentEndDate >= x.UpdatedDate && x.UpdatedDate > x.CreatedDate));`

version 1.9.x
`AND (
('2019-08-31 16:00:00' <= bt$."UpdatedDate" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" >= bt$."TransactionTime") OR 
('2019-08-31 16:00:00' <= bt$."TransactionTime" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" < bt$."TransactionTime") OR 
('2019-08-31 16:00:00' <= bt$."UpdatedDate" AND bt$."UpdatedDate" > bt$."CreatedDate")) AND 
(('2019-09-01 15:59:59' >= bt$."UpdatedDate" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" >= bt$."TransactionTime") OR 
('2019-09-01 15:59:59' >= bt$."TransactionTime" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" < bt$."TransactionTime") OR 
('2019-09-01 15:59:59' >= bt$."UpdatedDate" AND bt$."UpdatedDate" > bt$."CreatedDate"))`

version 2.3.1
`AND '2019-08-31 16:00:00' <= bt$."UpdatedDate" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" >= bt$."TransactionTime" 
OR '2019-08-31 16:00:00' <= bt$."TransactionTime" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" < bt$."TransactionTime" 
OR '2019-08-31 16:00:00' <= bt$."UpdatedDate" AND bt$."UpdatedDate" > bt$."CreatedDate" 
AND '2019-09-01 15:59:59' >= bt$."UpdatedDate" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" >= bt$."TransactionTime" 
OR '2019-09-01 15:59:59' >= bt$."TransactionTime" AND bt$."CreatedDate" = bt$."UpdatedDate" AND bt$."UpdatedDate" < bt$."TransactionTime" 
OR'2019-09-01 15:59:59' >= bt$."UpdatedDate" AND bt$."UpdatedDate" > bt$."CreatedDate"`

**Comment by Michaellok1992** [comment]
Without the bracketing the result return is wrong.

**Comment by rivantsov** [comment]
ok, thanks for reporting, looking at it

**Comment by rivantsov** [comment]
By the way, thanks for so detail reporting, with SQL for both versions, makes it much easier to investigate!!

**Comment by Michaellok1992** [comment]
Sure no problem. I moving from 1.9.3.1 to latest since it more stable now. Hopefully i can get to use the latest. 

By the way, if possible, i would like to get this up as soon as possible, if you are free. Thanks for the effort.

**Comment by rivantsov** [comment]
fixed, pushed, nuget packages updated, v 2.3.2
it was actually a problem of chaining Where calls like in  your example, not bracketing/operation precedence by itself. 
TestBugFixes test has an extra test for this case.

**Comment by Michaellok1992** [comment]
Will update after i tested my system. Thanks alot!

**Comment by Michaellok1992** [comment]
In short, it work! Thanks!~

So far so good. But since i moved from 1.9.x to 2.3.2, there is some linq/lambda i need to rewrite.

For example, 
from 1.9.x
`x.BankAccount.OrganizationBankAccounts.Any(y => y.Organization.Id == organizationId)`

to 2.3.2
`x.BankAccount.OrganizationBankAccounts.Any(y => y.Organization.Id == organizationId && y.BankAccount.Id == x.BankAccount.Id)`

Previous 1.9.x, it will help include it.

**Comment by rivantsov** [comment]
Can you please elaborate more on this need to change? why? seems like a potential bug

**Comment by Michaellok1992** [comment]
*Note: Partial of the code is taken

C# :
`session.EntitySet<IBankTransaction>().Where(x =>x.BankAccount.OrganizationBankAccounts.Any(y => y.Organization.Id == organizationId && y.BankAccount.Id == x.BankAccount.Id)`

The SQL output for following version

In 1.9.x:

`((SELECT COUNT_BIG(*)
FROM "dbo"."OrganizationBankAccount" t3$
 INNER JOIN "dbo"."BankAccount" t2$ ON t2$."Id" = x$."BankAccount_Id"
WHERE (t3$."BankAccount_Id" = t2$."Id") AND (t3$."Organization_Id" = @P0))`

In 2.3.2:
`EXISTS 
  (SELECT  *
FROM "dbo"."BankAccount" ba$, "dbo"."OrganizationBankAccount" oba$
WHERE oba$."BankAccount_Id" = ba$."Id" AND oba$."Organization_Id" = @P0)`

**Comment by rivantsov** [comment]
can you pls send me entity definitions (c# interfaces) for all entities involved? 
rivantsov at gmail dot com

**Comment by Michaellok1992** [comment]
Sent.

**Comment by Michaellok1992** [comment]
@rivantsov any update on your end?

**Comment by rivantsov** [comment]
not yet, will get to it on weekend, sorry, very busy at work

**Comment by rivantsov** [comment]
Hi. I've spent quite some time trying to repro your case with sample Bookstore app, trying all kinds of combinations of attached lists and any conditions, so far no luck, the SQL looks correct. 
I will try to repro with your entities directly, in a separate entityapp. sorry for the delay

**Comment by Michaellok1992** [comment]
Are you comparing with 1.9.x and 2.3.x? 

I try open another simple project to try simulate the issue that i mention above.

**Comment by rivantsov** [comment]
I do not compare with old version; things changed for better, for one thing - new version now uses EXISTS instead of (COUNT > 0) - which is a big improvement; also expressing joins improved - LINQ engine tries to use JOIN whenever possible (I believe), instead of WHERE;
 I just try to catch the invalid SQL translation case in new version

**Comment by Michaellok1992** [comment]
Let put this topic ([BUG] Incorrect condition due to bracketing) into a closure. since the main bug has been solved.

For the issue that i mentioned in above comment,
https://github.com/rivantsov/vita/issues/93#issuecomment-535041223

I will open another ticket/issue with more detail in the future. :)
