### ISSUE TITLE
[QUESTION] Export / Output / Log SQL Generated

### ISSUE THREAD

**Issue by Michaellok1992** [rivantsov/vita#95]
Hi @rivantsov ,

Besides from using session.LastCommand(), is there other way i can generate/output/log the sql to a file/database/destination? 

it is abit hard for me to view sql in lastcommand() everytime i step to next line of code. It will be great that i can view it in 1 list in 1 shot instead step by step line of code.

**Comment by rivantsov** [comment]
you can send it to a file, look at test projects, they dump all to file, in bin folder. There's property LogFilePath (or smth) on EntityApp, if you set it, system will start wrting to it
