### ISSUE TITLE
[Question] Nullable field

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#98]
Hi @rivantsov ,

One quick question, for nullable field, we should use the [Nullable] attribute tag or just defined as nullable datatype, such "string?" or "datetime?" ?
What is the different between this?

Thanks in advance.

**Comment by rivantsov** [comment]
1. For string and byte[] members, Nullable results in: Nullable column in database, and allowing you to assign null to entity property; without this attr, column is not nullable, and you can't assign null or empty string
2. For nullable value types (Datetime?, int?) - Nullable is not needed, fwk infers that it is nullable column
3. string? - I assume that this is from latest c# version (nullable ref types), this stuff is not supported, so don't use it
4. If you put Nullable on value type (without question mark), then underlying column will be nullable; the zero/default value for the entity property (ex: 0 for int type) will be replaced with NULL when writing to db; when reading, NULL value will be replaced with 0. But I would advise to avoid this arrangement

**Comment by jasonlaw** [comment]
Clear now, thank you very much, really appreciate it.
