### ISSUE TITLE
Unable to delete record, foreign key contraints

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#99]
Hi @rivantsov ,

I have 2 entities(simplify) as below:

```
[Entity]
public interface IBillingUnit : IEntityTable
{	
	[Nullable]
	IBillingAccount ActiveBillingAccount { get; set; }
	
	IList<IBillingAccount> BillingAccounts { get; }
}

[Entity]
public interface IBillingAccount : IEntityTable
{
	[NoUpdate, CascadeDelete]
	IBillingUnit BillingUnit { get; set; }
}
```
It is a one-to-many relationship, ie, BillingUnit (one) to BillingAccount (many).
At the same time, the BillingUnit should have a relation to the active BillingAccount (only one active is allowed).

I can populate the records without problem, however, when I try to delete 1 record from BillingUnit, I hit the follow error:

**Cannot delete or update a parent row: a foreign key constraint fails ("communitydev"."BillingUnit", CONSTRAINT "FK_BillingUnit_BillingAccount" FOREIGN KEY ("ActiveBillingAccount_Key") REFERENCES "BillingAccount" ("Key"))**

Is it a bug of the framework (latest version)? 
Could it be my entity design is wrong? Could you please advise the correct way to design such use case?

Thanks in advance.

Jason Law

**Comment by jasonlaw** [comment]
Update: I am using MySQL.

**Comment by rivantsov** [comment]
You cannot delete parent (BillingUnit) until you delete all children referencing it. This is relational database restriction. You have to delete all children first, and in your case, also set to null the ActiveBillingAccount; then you can delete the parent. Alternatively you can try CascadeDelete attribute, on IBillingAccount.BillingUnit property, but it might not work (not sure) because of your ActiveBillingAccount reference;
essentially you have circular reference here, so it's hard to say will it work or not with cascade delete

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks for the prompt reply.
In fact I am using CascadeDelete and it won't work, I guess the circular reference design here is a big mistake.

Btw, I have tried to use the Computed attribute on it, but the framework complaints about it.
Entity:

```
  [Entity]
    public interface IBillingUnit : IEntityTable
    {
        [Nullable]
        Guid ActiveBillingAccountKey { get; set; }
        [Computed(typeof(IBillingUnitExtensions), "GetBillingAccount"), DependsOn("ActiveBillingAccountKey")]
        IBillingAccount ActiveBillingAccount { get; }
    }
```

Error:
`ERROR: Invalid key member ActiveBillingAccount, entity MyCommunityWebApi.Modules.Billing.IBillingUnit: must be a property matched to a database column.`

Are we not allowed to use Computed on reference object?

Thanks again!

**Comment by rivantsov** [comment]
yes, Computed would not work here (on ref member). 
Circular ref is not a mistake by itself, it's quite common situation, reflects the business case; you just need to manage it carefully. 
In your case, you must first nullify it (no active account), commit it (SaveChanges), and only then delete Accounts and parent Unit entity

**Comment by jasonlaw** [comment]
Ok all clear now. Thank you very much for the advice, and this great framework! Really appreciate it!
